In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#AIRBNB MAR 25

In [ ]:
import pandas as pd

##listings

In [ ]:
#listings = pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/listings.csv")
listings = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/listings.csv.gz")

Listings csv, es un archivo con 18 columas, pero faltan columnas que tienen relevancia para el análisis general, por lo que usaremos listing.csv.gz para utilizar toda la información posible.

In [ ]:
listings

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,35797,Villa Dante,153786,Dici,NaN,Cuajimalpa de Morelos,19.382830,-99.271780,Entire home/apt,3982.0,1,0,NaN,NaN,1,363,0,NaN
1,44616,Condesa Haus,196253,Fernando,NaN,Cuauhtémoc,19.411620,-99.177940,Entire home/apt,NaN,1,65,2025-01-01,0.40,9,364,1,NaN
2,56074,Great space in historical San Rafael,265650,Maris,NaN,Cuauhtémoc,19.439770,-99.156050,Entire home/apt,585.0,15,84,2025-02-27,0.49,1,361,1,NaN
3,67703,"2 bedroom apt. deco bldg, Condesa",334451,Nicholas,NaN,Cuauhtémoc,19.411520,-99.168570,Entire home/apt,NaN,2,50,2024-10-30,0.31,2,307,2,NaN
4,70644,Beautiful light Studio Coyoacan- full equipped !,212109,Trisha,NaN,Coyoacán,19.354480,-99.162170,Entire home/apt,1015.0,3,132,2024-12-28,0.83,3,245,9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26062,1379327529227113949,Cama en Dorm mixto de 4 personas,261044377,Casa Pepe,NaN,Cuauhtémoc,19.430390,-99.134282,Shared room,529.0,1,0,NaN,NaN,8,344,0,NaN
26063,1379338090263773362,loft #307 excelente ubicación ideal para descanso,175442219,Lando,NaN,Cuauhtémoc,19.439520,-99.152520,Private room,472.0,1,0,NaN,NaN,1,324,0,NaN
26064,1379781424660291699,Cozy room in Roma Norte,34664434,Macarena,NaN,Cuauhtémoc,19.417618,-99.166841,Private room,399.0,1,0,NaN,NaN,2,340,0,NaN
26065,1379807014531191212,Stylish suite w private terrace close to Polanco,515054008,Joaquin,NaN,Miguel Hidalgo,19.428857,-99.177626,Entire home/apt,1494.0,1,0,NaN,NaN,32,362,0,NaN
26066,1379814270520534429,Depto. en el corazón de Roma N,189134785,Emiliano,NaN,Cuauhtémoc,19.416223,-99.156934,Entire home/apt,1722.0,3,0,NaN,NaN,1,81,0,NaN

##Listings GZ Marzo 25

In [ ]:
#listings_gz_MAR = pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/listings.csv.gz")
listings_gz_MAR = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/listings.csv.gz")

In [ ]:
listings_gz_MAR

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,35797,https://www.airbnb.com/rooms/35797,20250319150644,2025-03-21,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Santa Fe Shopping Mall, Interlomas Park and th...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
1,44616,https://www.airbnb.com/rooms/44616,20250319150644,2025-03-20,previous scrape,Condesa Haus,A new concept of hosting in mexico through a b...,NaN,https://a0.muscache.com/pictures/251410/ec75fe...,196253,...,4.78,4.98,4.47,NaN,f,9,4,2,0,0.40
2,56074,https://www.airbnb.com/rooms/56074,20250319150644,2025-03-20,city scrape,Great space in historical San Rafael,This great apartment is located in one of the ...,Very traditional neighborhood with all service...,https://a0.muscache.com/pictures/3005118/60dac...,265650,...,4.94,4.76,4.79,NaN,f,1,1,0,0,0.49
3,67703,https://www.airbnb.com/rooms/67703,20250319150644,2025-03-20,previous scrape,"2 bedroom apt. deco bldg, Condesa","Comfortably furnished, sunny, 2 bedroom apt., ...",NaN,https://a0.muscache.com/pictures/3281720/6f078...,334451,...,4.92,4.98,4.92,NaN,f,2,2,0,0,0.31
4,70644,https://www.airbnb.com/rooms/70644,20250319150644,2025-03-22,city scrape,Beautiful light Studio Coyoacan- full equipped !,COYOACAN designer studio quiet & safe! well eq...,Coyoacan is a beautiful neighborhood famous fo...,https://a0.muscache.com/pictures/f397d2da-d045...,212109,...,4.98,4.96,4.92,NaN,f,3,2,1,0,0.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26062,1379327529227113949,https://www.airbnb.com/rooms/1379327529227113949,20250319150644,2025-03-22,city scrape,Cama en Dorm mixto de 4 personas,Casa Pepe is a hotel with a hostel vocation th...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,261044377,...,NaN,NaN,NaN,NaN,t,8,0,4,4,NaN
26063,1379338090263773362,https://www.airbnb.com/rooms/1379338090263773362,20250319150644,2025-03-20,city scrape,loft #307 excelente ubicación ideal para descanso,Very nice room for 2 people (children under 12...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,175442219,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
26064,1379781424660291699,https://www.airbnb.com/rooms/1379781424660291699,20250319150644,2025-03-20,city scrape,Cozy room in Roma Norte,Located in the Colonia Roma Norte (Roma-Condes...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,34664434,...,NaN,NaN,NaN,NaN,f,2,0,2,0,NaN
26065,1379807014531191212,https://www.airbnb.com/rooms/1379807014531191212,20250319150644,2025-03-22,city scrape,Stylish suite w private terrace close to Polanco,Tucked away in the lively neighborhood of Anzu...,Anzures is situated in the heart of Mexico Cit...,https://a0.muscache.com/pictures/prohost-api/H...,515054008,...,NaN,NaN,NaN,NaN,t,32,32,0,0,NaN
26066,1379814270520534429,https://www.airbnb.com/rooms/1379814270520534429,20250319150644,2025-03-20,city scrape,Depto. en el corazón de Roma N,"Apartment with 2 bedrooms, 2 bathrooms, 2 doub...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,189134785,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [ ]:
calendar_gz_MAR =  pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/calendar.csv.gz")

/tmp/ipython-input-2311257996.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  calendar_gz_MAR =  pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/calendar.csv.gz")

In [ ]:
#Guardamos como csv para una revisión en excell
output_path = '/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/listings_gz_MAR.csv'
listings_gz_MAR.to_csv(output_path, index=False)

print(f"Attempting to save df_MAR to {output_path}")

Attempting to save df_MAR to /content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/listings_gz_MAR.csv

In [ ]:
https://github.com/duranueva/Proyecto-Airbnb

In [ ]:
listings_gz_MAR.to_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/listings_gz_MAR.csv", index=False)

In [ ]:
listings_gz_MAR

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,35797,https://www.airbnb.com/rooms/35797,20250319150644,2025-03-21,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Santa Fe Shopping Mall, Interlomas Park and th...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
1,44616,https://www.airbnb.com/rooms/44616,20250319150644,2025-03-20,previous scrape,Condesa Haus,A new concept of hosting in mexico through a b...,NaN,https://a0.muscache.com/pictures/251410/ec75fe...,196253,...,4.78,4.98,4.47,NaN,f,9,4,2,0,0.40
2,56074,https://www.airbnb.com/rooms/56074,20250319150644,2025-03-20,city scrape,Great space in historical San Rafael,This great apartment is located in one of the ...,Very traditional neighborhood with all service...,https://a0.muscache.com/pictures/3005118/60dac...,265650,...,4.94,4.76,4.79,NaN,f,1,1,0,0,0.49
3,67703,https://www.airbnb.com/rooms/67703,20250319150644,2025-03-20,previous scrape,"2 bedroom apt. deco bldg, Condesa","Comfortably furnished, sunny, 2 bedroom apt., ...",NaN,https://a0.muscache.com/pictures/3281720/6f078...,334451,...,4.92,4.98,4.92,NaN,f,2,2,0,0,0.31
4,70644,https://www.airbnb.com/rooms/70644,20250319150644,2025-03-22,city scrape,Beautiful light Studio Coyoacan- full equipped !,COYOACAN designer studio quiet & safe! well eq...,Coyoacan is a beautiful neighborhood famous fo...,https://a0.muscache.com/pictures/f397d2da-d045...,212109,...,4.98,4.96,4.92,NaN,f,3,2,1,0,0.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26062,1379327529227113949,https://www.airbnb.com/rooms/1379327529227113949,20250319150644,2025-03-22,city scrape,Cama en Dorm mixto de 4 personas,Casa Pepe is a hotel with a hostel vocation th...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,261044377,...,NaN,NaN,NaN,NaN,t,8,0,4,4,NaN
26063,1379338090263773362,https://www.airbnb.com/rooms/1379338090263773362,20250319150644,2025-03-20,city scrape,loft #307 excelente ubicación ideal para descanso,Very nice room for 2 people (children under 12...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,175442219,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
26064,1379781424660291699,https://www.airbnb.com/rooms/1379781424660291699,20250319150644,2025-03-20,city scrape,Cozy room in Roma Norte,Located in the Colonia Roma Norte (Roma-Condes...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,34664434,...,NaN,NaN,NaN,NaN,f,2,0,2,0,NaN
26065,1379807014531191212,https://www.airbnb.com/rooms/1379807014531191212,20250319150644,2025-03-22,city scrape,Stylish suite w private terrace close to Polanco,Tucked away in the lively neighborhood of Anzu...,Anzures is situated in the heart of Mexico Cit...,https://a0.muscache.com/pictures/prohost-api/H...,515054008,...,NaN,NaN,NaN,NaN,t,32,32,0,0,NaN
26066,1379814270520534429,https://www.airbnb.com/rooms/1379814270520534429,20250319150644,2025-03-20,city scrape,Depto. en el corazón de Roma N,"Apartment with 2 bedrooms, 2 bathrooms, 2 doub...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,189134785,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [ ]:
listings_gz_MAR[listings_gz_MAR["bathrooms_text"].notna()]

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,35797,https://www.airbnb.com/rooms/35797,20250319150644,2025-03-21,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Santa Fe Shopping Mall, Interlomas Park and th...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
1,44616,https://www.airbnb.com/rooms/44616,20250319150644,2025-03-20,previous scrape,Condesa Haus,A new concept of hosting in mexico through a b...,NaN,https://a0.muscache.com/pictures/251410/ec75fe...,196253,...,4.78,4.98,4.47,NaN,f,9,4,2,0,0.40
2,56074,https://www.airbnb.com/rooms/56074,20250319150644,2025-03-20,city scrape,Great space in historical San Rafael,This great apartment is located in one of the ...,Very traditional neighborhood with all service...,https://a0.muscache.com/pictures/3005118/60dac...,265650,...,4.94,4.76,4.79,NaN,f,1,1,0,0,0.49
3,67703,https://www.airbnb.com/rooms/67703,20250319150644,2025-03-20,previous scrape,"2 bedroom apt. deco bldg, Condesa","Comfortably furnished, sunny, 2 bedroom apt., ...",NaN,https://a0.muscache.com/pictures/3281720/6f078...,334451,...,4.92,4.98,4.92,NaN,f,2,2,0,0,0.31
4,70644,https://www.airbnb.com/rooms/70644,20250319150644,2025-03-22,city scrape,Beautiful light Studio Coyoacan- full equipped !,COYOACAN designer studio quiet & safe! well eq...,Coyoacan is a beautiful neighborhood famous fo...,https://a0.muscache.com/pictures/f397d2da-d045...,212109,...,4.98,4.96,4.92,NaN,f,3,2,1,0,0.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26062,1379327529227113949,https://www.airbnb.com/rooms/1379327529227113949,20250319150644,2025-03-22,city scrape,Cama en Dorm mixto de 4 personas,Casa Pepe is a hotel with a hostel vocation th...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,261044377,...,NaN,NaN,NaN,NaN,t,8,0,4,4,NaN
26063,1379338090263773362,https://www.airbnb.com/rooms/1379338090263773362,20250319150644,2025-03-20,city scrape,loft #307 excelente ubicación ideal para descanso,Very nice room for 2 people (children under 12...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,175442219,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
26064,1379781424660291699,https://www.airbnb.com/rooms/1379781424660291699,20250319150644,2025-03-20,city scrape,Cozy room in Roma Norte,Located in the Colonia Roma Norte (Roma-Condes...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,34664434,...,NaN,NaN,NaN,NaN,f,2,0,2,0,NaN
26065,1379807014531191212,https://www.airbnb.com/rooms/1379807014531191212,20250319150644,2025-03-22,city scrape,Stylish suite w private terrace close to Polanco,Tucked away in the lively neighborhood of Anzu...,Anzures is situated in the heart of Mexico Cit...,https://a0.muscache.com/pictures/prohost-api/H...,515054008,...,NaN,NaN,NaN,NaN,t,32,32,0,0,NaN
26066,1379814270520534429,https://www.airbnb.com/rooms/1379814270520534429,20250319150644,2025-03-20,city scrape,Depto. en el corazón de Roma N,"Apartment with 2 bedrooms, 2 bathrooms, 2 doub...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,189134785,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [ ]:
# Baños fue como referencia de un trabajo previo, que dicha variable tiene mucho peso, entonces revisamos con cual quedarnos.
df_baths = listings_gz_MAR.loc[:, ["bathrooms_text", "bathrooms"]].copy()
df_baths.head()

  bathrooms_text  bathrooms
0         1 bath        1.0
1      5.5 baths        NaN
2         1 bath        1.0
3         1 bath        NaN
4         1 bath        1.0

In [ ]:
df_baths

       bathrooms_text  bathrooms
0              1 bath        1.0
1           5.5 baths        NaN
2              1 bath        1.0
3              1 bath        NaN
4              1 bath        1.0
...               ...        ...
26062   1 shared bath        1.0
26063  1 private bath        1.0
26064   1 shared bath        1.0
26065          1 bath        1.0
26066         2 baths        2.0

[26067 rows x 2 columns]

In [ ]:
# Filas donde al menos una de las dos columnas es nula
df_baths_na = df_baths[df_baths.isna().any(axis=1)]

# Mantener solo filas donde ambas NO son nulas
df_boths_present = df_baths.dropna(subset=["bathrooms_text", "bathrooms"], how="any")

# Guardar a CSV
#df_baths.to_csv("bathrooms_subset.csv", index=False)

In [ ]:
df_baths_na

       bathrooms_text  bathrooms
1           5.5 baths        NaN
3              1 bath        NaN
5      1 private bath        NaN
9              1 bath        NaN
10            2 baths        NaN
...               ...        ...
25446          1 bath        NaN
25512          1 bath        NaN
25514       1.5 baths        NaN
25529          1 bath        NaN
25697             NaN        NaN

[4018 rows x 2 columns]

In [ ]:
df_boths_present

       bathrooms_text  bathrooms
0              1 bath        1.0
2              1 bath        1.0
4              1 bath        1.0
6             5 baths        5.0
7      1 private bath        1.0
...               ...        ...
26062   1 shared bath        1.0
26063  1 private bath        1.0
26064   1 shared bath        1.0
26065          1 bath        1.0
26066         2 baths        2.0

[22049 rows x 2 columns]

Finalmente **bathrooms_tex** contiene mas informacion que **bathrooms** y con menos valores faltantes.

In [ ]:
print(len(listings_gz_MAR["host_id"].unique())) # Podemos observar que en total de la base de datos es probable que el host_id se repita mas de una vez.

11821

In [ ]:
listings_gz_MAR.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26067 entries, 0 to 26066
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            26067 non-null  int64
 1   listing_url                                   26067 non-null  object
 2   scrape_id                                     26067 non-null  int64
 3   last_scraped                                  26067 non-null  object
 4   source                                        26067 non-null  object
 5   name                                          26067 non-null  object
 6   description                                   25300 non-null  object
 7   neighborhood_overview                         14391 non-null  object
 8   picture_url                                   26067 non-null  object
 9   host_id                                       26067 non-null  int64
 10  host_url                                      26067 non-null  object
 11  host_name                                     26062 non-null  object
 12  host_since                                    26062 non-null  object
 13  host_location                                 20587 non-null  object
 14  host_about                                    15610 non-null  object
 15  host_response_time                            22563 non-null  object
 16  host_response_rate                            22563 non-null  object
 17  host_acceptance_rate                          23328 non-null  object
 18  host_is_superhost                             24724 non-null  object
 19  host_thumbnail_url                            26062 non-null  object
 20  host_picture_url                              26062 non-null  object
 21  host_neighbourhood                            13875 non-null  object
 22  host_listings_count                           26062 non-null  float64
 23  host_total_listings_count                     26062 non-null  float64
 24  host_verifications                            26062 non-null  object
 25  host_has_profile_pic                          26062 non-null  object
 26  host_identity_verified                        26062 non-null  object
 27  neighbourhood                                 14391 non-null  object
 28  neighbourhood_cleansed                        26067 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      26067 non-null  float64
 31  longitude                                     26067 non-null  float64
 32  property_type                                 26067 non-null  object
 33  room_type                                     26067 non-null  object
 34  accommodates                                  26067 non-null  int64
 35  bathrooms                                     22062 non-null  float64
 36  bathrooms_text                                26040 non-null  object
 37  bedrooms                                      25096 non-null  float64
 38  beds                                          22045 non-null  float64
 39  amenities                                     26067 non-null  object
 40  price                                         22068 non-null  object
 41  minimum_nights                                26067 non-null  int64
 42  maximum_nights                                26067 non-null  int64
 43  minimum_minimum_nights                        26067 non-null  int64
 44  maximum_minimum_nights                        26067 non-null  int64
 45  minimum_maximum_nights                        26067 non-null  int64
 46  maximum_maximum_nights                        26067 non-null  int64
 47  minimum_nights_avg_ntm                        26067 non-null  float64
 48  maximum_nights_avg_ntm                        26067 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              25076 non-null  object
 51  availability_30                               26067 non-null  int64
 52  availability_60                               26067 non-null  int64
 53  availability_90                               26067 non-null  int64
 54  availability_365                              26067 non-null  int64
 55  calendar_last_scraped                         26067 non-null  object
 56  number_of_reviews                             26067 non-null  int64
 57  number_of_reviews_ltm                         26067 non-null  int64
 58  number_of_reviews_l30d                        26067 non-null  int64
 59  availability_eoy                              26067 non-null  int64
 60  number_of_reviews_ly                          26067 non-null  int64
 61  estimated_occupancy_l365d                     26067 non-null  int64
 62  estimated_revenue_l365d                       22068 non-null  float64
 63  first_review                                  22806 non-null  object
 64  last_review                                   22806 non-null  object
 65  review_scores_rating                          22806 non-null  float64
 66  review_scores_accuracy                        22805 non-null  float64
 67  review_scores_cleanliness                     22805 non-null  float64
 68  review_scores_checkin                         22805 non-null  float64
 69  review_scores_communication                   22805 non-null  float64
 70  review_scores_location                        22805 non-null  float64
 71  review_scores_value                           22805 non-null  float64
 72  license                                       0 non-null      float64
 73  instant_bookable                              26067 non-null  object
 74  calculated_host_listings_count                26067 non-null  int64
 75  calculated_host_listings_count_entire_homes   26067 non-null  int64
 76  calculated_host_listings_count_private_rooms  26067 non-null  int64
 77  calculated_host_listings_count_shared_rooms   26067 non-null  int64
 78  reviews_per_month                             22806 non-null  float64
dtypes: float64(21), int64(24), object(34)
memory usage: 15.7+ MB

In [ ]:
#Cuantifica valores faltantes por columna.
print('Missing values in data')
valores = listings_gz_MAR.isnull().sum()

Missing values in data

In [ ]:
valores.head(50)

id                                  0
listing_url                         0
scrape_id                           0
last_scraped                        0
source                              0
name                                0
description                       767
neighborhood_overview           11676
picture_url                         0
host_id                             0
host_url                            0
host_name                           5
host_since                          5
host_location                    5480
host_about                      10457
host_response_time               3504
host_response_rate               3504
host_acceptance_rate             2739
host_is_superhost                1343
host_thumbnail_url                  5
host_picture_url                    5
host_neighbourhood              12192
host_listings_count                 5
host_total_listings_count           5
host_verifications                  5
host_has_profile_pic                5
host_identity_verified              5
neighbourhood                   11676
neighbourhood_cleansed              0
neighbourhood_group_cleansed    26067
latitude                            0
longitude                           0
property_type                       0
room_type                           0
accommodates                        0
bathrooms                        4005
bathrooms_text                     27
bedrooms                          971
beds                             4022
amenities                           0
price                            3999
minimum_nights                      0
maximum_nights                      0
minimum_minimum_nights              0
maximum_minimum_nights              0
minimum_maximum_nights              0
maximum_maximum_nights              0
minimum_nights_avg_ntm              0
maximum_nights_avg_ntm              0
calendar_updated                26067
dtype: int64

In [ ]:
df_MAR = listings_gz_MAR.copy()

In [ ]:
df_MAR.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

###Traducción de las columnas.

id → id del anuncio

listing_url → URL del anuncio

scrape_id → id de extracción (crawleo)

last_scraped → fecha de última extracción

source → fuente de datos

name → título del anuncio

description → descripción

neighborhood_overview → descripción del vecindario

picture_url → URL de la foto principal

host_id → id del anfitrión

host_url → URL del perfil del anfitrión

host_name → nombre del anfitrión

host_since → anfitrión desde (fecha de alta)

host_location → ubicación del anfitrión

host_about → acerca del anfitrión

host_response_time → tiempo de respuesta del anfitrión

host_response_rate → tasa de respuesta del anfitrión (%)

host_acceptance_rate → tasa de aceptación del anfitrión (%)

host_is_superhost → es superanfitrión (sí/no)

host_thumbnail_url → URL de miniatura del anfitrión

host_picture_url → URL de la foto del anfitrión

host_neighbourhood → barrio del anfitrión

host_listings_count → nº de anuncios activos del anfitrión

host_total_listings_count → nº total de anuncios del anfitrión

host_verifications → verificaciones del anfitrión (lista)

host_has_profile_pic → el anfitrión tiene foto de perfil (sí/no)

host_identity_verified → identidad verificada (sí/no)

neighbourhood → barrio del anuncio

neighbourhood_cleansed → barrio normalizado/limpiado

neighbourhood_group_cleansed → grupo de barrio (normalizado)

latitude → latitud

longitude → longitud

property_type → tipo de propiedad

room_type → tipo de habitación

accommodates → capacidad (nº de huéspedes)

bathrooms → baños (número)

bathrooms_text → detalle de baños (texto)

bedrooms → dormitorios

beds → camas

amenities → amenidades/servicios

price → precio por noche (moneda local)

minimum_nights → noches mínimas

maximum_nights → noches máximas

minimum_minimum_nights → mínimo de las noches mínimas

maximum_minimum_nights → máximo de las noches mínimas

minimum_maximum_nights → mínimo de las noches máximas

maximum_maximum_nights → máximo de las noches máximas

minimum_nights_avg_ntm → noches mínimas promedio (próximos 12 meses)

maximum_nights_avg_ntm → noches máximas promedio (próximos 12 meses)

calendar_updated → actualización del calendario (texto)

has_availability → tiene disponibilidad (sí/no)

availability_30 → días disponibles próximos 30 días

availability_60 → días disponibles próximos 60 días

availability_90 → días disponibles próximos 90 días

availability_365 → días disponibles próximos 365 días

calendar_last_scraped → última extracción del calendario (fecha)

number_of_reviews → nº total de reseñas

number_of_reviews_ltm → nº de reseñas en los últimos 12 meses

number_of_reviews_l30d → nº de reseñas en los últimos 30 días

availability_eoy → disponibilidad a fin de año (EOY)

number_of_reviews_ly → nº de reseñas el año pasado

estimated_occupancy_l365d → ocupación estimada en los últimos 365 días (%)

estimated_revenue_l365d → ingresos estimados en los últimos 365 días (moneda local)

first_review → fecha de la primera reseña

last_review → fecha de la última reseña

review_scores_rating → puntuación global

review_scores_accuracy → puntuación de exactitud

review_scores_cleanliness → puntuación de limpieza

review_scores_checkin → puntuación de check-in

review_scores_communication → puntuación de comunicación

review_scores_location → puntuación de ubicación

review_scores_value → puntuación de relación calidad-precio

license → licencia/permiso (número)

instant_bookable → reservación instantánea (sí/no)

calculated_host_listings_count → conteo calculado de anuncios del anfitrión

calculated_host_listings_count_entire_homes → conteo calculado de viviendas completas

calculated_host_listings_count_private_rooms → conteo calculado de habitaciones privadas

calculated_host_listings_count_shared_rooms → conteo calculado de habitaciones compartidas

reviews_per_month → reseñas por mes

Aqui seleccionamos de manera subjetiva que variables eliminar para hacer predicciones.

VARIABLES QUE SE QUEDAN
* source
* description ¿SI?
* neighborhood_overview → descripción del vecindario
* host_since → anfitrión desde (fecha de alta)

* host_location → ubicación del anfitrión

* host_about → acerca del anfitrión
*  host_is_superhost → es superanfitrión (sí/no)
* host_neighbourhood → barrio del anfitrión
--------
* eighbourhood_cleansed → barrio normalizado/limpiado


* neighbourhood_group_cleansed → grupo de barrio (normalizado)

* latitude → latitud

* longitude → longitud

* property_type → tipo de propiedad

* room_type → tipo de habitación

* accommodates → capacidad (nº de huéspedes)

* bathrooms → baños (número)

* bathrooms_text → detalle de baños (texto)

* bedrooms → dormitorios

* beds → camas

* amenities → amenidades/servicios

* price → precio por noche (moneda local)

* minimum_nights → noches mínimas

* maximum_nights → noches máximas

* minimum_minimum_nights → mínimo de las noches mínimas

* maximum_minimum_nights → máximo de las noches mínimas

* minimum_maximum_nights → mínimo de las noches máximas

* maximum_maximum_nights → máximo de las noches máximas

* minimum_nights_avg_ntm → noches mínimas promedio (próximos 12 meses)

* maximum_nights_avg_ntm → noches máximas promedio (próximos 12 meses)
-------
* has_availability → tiene disponibilidad (sí/no)

* availability_30 → días disponibles próximos 30 días

* availability_60 → días disponibles próximos 60 días

* availability_90 → días disponibles próximos 90 días

* availability_365 → días disponibles próximos 365 días

* estimated_occupancy_l365d → ocupación estimada en los últimos 365 días (%)

* estimated_revenue_l365d → ingresos estimados en los últimos 365 días (moneda local)

* review_scores_location → puntuación de ubicación

* review_scores_value → puntuación de relación calidad-precio
* license → licencia/permiso (número)

* instant_bookable → reservación instantánea (sí/no)



* calculated_host_listings_count_entire_homes → conteo calculado de viviendas completas

* calculated_host_listings_count_private_rooms → conteo calculado de habitaciones privadas

* calculated_host_listings_count_shared_rooms → conteo calculado de habitaciones compartidas

VARIABLES QUE SE VAN
* id

*  listing_url

* scrape_id → id de extracción (crawleo)

* last_scraped → fecha de última extracción

* name → título del anuncio

* picture_url → URL de la foto principal

* host_id → id del anfitrión
* host_url → URL del perfil del anfitrión
* host_name → nombre del anfitrión
* host_response_time → tiempo de respuesta del anfitrión ¿si?
* host_response_rate → tasa de respuesta del anfitrión (%)¿si?
* host_acceptance_rate → tasa de aceptación del anfitrión (%) ¿si?

* host_thumbnail_url → URL de miniatura del anfitrión

* host_picture_url → URL de la foto del anfitrión

* ost_listings_count → nº de anuncios activos del anfitrión

* host_total_listings_count → nº total de anuncios del anfitrión

* host_verifications → verificaciones del anfitrión (lista)

* host_has_profile_pic → el anfitrión tiene foto de perfil (sí/no)

* host_identity_verified → identidad verificada (sí/no)

* neighbourhood → barrio del anuncio
* calendar_updated → actualización del calendario (texto)
* calendar_last_scraped → última extracción del calendario (fecha)
* number_of_reviews → nº total de reseñas

* number_of_reviews_ltm → nº de reseñas en los últimos 12 meses

* number_of_reviews_l30d → nº de reseñas en los últimos 30 días

* availability_eoy → disponibilidad a fin de año (EOY)

* number_of_reviews_ly → nº de reseñas el año pasado
* first_review → fecha de la primera reseña

* last_review → fecha de la última reseña

* review_scores_rating → puntuación global

* review_scores_accuracy → puntuación de exactitud

* review_scores_cleanliness → puntuación de limpieza

* review_scores_checkin → puntuación de check-in

* review_scores_communication → puntuación de comunicación

* calculated_host_listings_count → conteo calculado de anuncios del anfitrión

* reviews_per_month → reseñas por mes

Claramos que esta fue la primera revisión y decision sobre que variables eliminar como primera fase.

###continuamos con el análisis.

In [ ]:
df_MAR["source"]

0            city scrape
1        previous scrape
2            city scrape
3        previous scrape
4            city scrape
              ...
26062        city scrape
26063        city scrape
26064        city scrape
26065        city scrape
26066        city scrape
Name: source, Length: 26067, dtype: object

In [ ]:
listings_gz_MAR["number_of_reviews"]

0          0
1         65
2         84
3         50
4        132
        ...
26062      0
26063      0
26064      0
26065      0
26066      0
Name: number_of_reviews, Length: 26067, dtype: int64

In [ ]:
#Pasamos el nombre de todas las columnas que procederemos a eliminar.
#Es importante notar que esta lista se irán anadiendo nuevas columnas más adelante,
#se determinen que deben eliminarse.
cols_to_drop = [
    "id",
    "listing_url",
    "scrape_id",
    "last_scraped",
    "name",
    "picture_url",
    "host_id",
    "host_url",
    "host_name",
    "host_response_time",
    "host_response_rate",
    "host_acceptance_rate",
    "host_thumbnail_url",
    "host_picture_url",
    "host_listings_count",
    "ost_listings_count",
    "host_total_listings_count",
    "host_verifications",
    "host_has_profile_pic",
    "host_identity_verified",
    "neighbourhood",
    "calendar_updated",
    "calendar_last_scraped",
    #"number_of_reviews", ## No se borraron estas variables puesto que se ocupan para hacer un análisis descriptivo porteriormente.
    "number_of_reviews_ltm",
    "number_of_reviews_l30d",
    "availability_eoy",
    "number_of_reviews_ly",
    "first_review",
    "last_review",
    #"review_scores_rating",###
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "calculated_host_listings_count",
    "reviews_per_month",
    "neighbourhood_group_cleansed",
    "license",
    "description",
    "neighborhood_overview",

    "host_about", # Se agregaron estas columnas puesto que eran descripcion.
    "host_neighbourhood",
    "source",
    "has_availability",
    "host_location", # Se agrego esta columna puesto que en la limpieza de sus valores nuelos me percate que solo toma el valor de ciudad de mexico, es decir, una columna de un solo valor.
    "estimated_occupancy_l365d" , #Se eliminaron estas columnas puesto que solo aparecen en la informacion de los meses del año 2025.
"estimated_revenue_l365d",
  "bathrooms"
]

In [ ]:
df_MAR.drop(columns=cols_to_drop, inplace=True, errors="ignore")

In [ ]:
df_MAR

,host_since,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,...,availability_60,availability_90,availability_365,review_scores_rating,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,2010-06-28,f,Cuajimalpa de Morelos,19.382830,-99.271780,Entire villa,Entire home/apt,2,1.0,1 bath,...,58,88,363,NaN,NaN,NaN,f,1,0,0
1,2010-08-09,f,Cuauhtémoc,19.411620,-99.177940,Entire home,Entire home/apt,14,NaN,5.5 baths,...,59,89,364,4.59,4.98,4.47,f,4,2,0
2,2010-10-19,f,Cuauhtémoc,19.439770,-99.156050,Entire condo,Entire home/apt,2,1.0,1 bath,...,56,86,361,4.87,4.76,4.79,f,1,0,0
3,2011-01-04,t,Cuauhtémoc,19.411520,-99.168570,Entire rental unit,Entire home/apt,4,NaN,1 bath,...,2,32,307,4.90,4.98,4.92,f,2,0,0
4,2010-08-24,t,Coyoacán,19.354480,-99.162170,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,6,23,245,4.92,4.96,4.92,f,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26062,2019-05-10,f,Cuauhtémoc,19.430390,-99.134282,Shared room in hotel,Shared room,4,1.0,1 shared bath,...,60,90,344,NaN,NaN,NaN,t,0,4,4
26063,2018-02-26,f,Cuauhtémoc,19.439520,-99.152520,Private room in loft,Private room,2,1.0,1 private bath,...,22,49,324,NaN,NaN,NaN,f,0,1,0
26064,2015-05-31,t,Cuauhtémoc,19.417618,-99.166841,Private room in rental unit,Private room,1,1.0,1 shared bath,...,35,65,340,NaN,NaN,NaN,f,0,2,0
26065,2023-05-16,t,Miguel Hidalgo,19.428857,-99.177626,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,57,87,362,NaN,NaN,NaN,t,32,0,0
26066,2018-05-12,f,Cuauhtémoc,19.416223,-99.156934,Entire rental unit,Entire home/apt,6,2.0,2 baths,...,51,81,81,NaN,NaN,NaN,f,1,0,0

In [ ]:
#Cuantifica valores faltantes por columna.
print('Missing values in data')
valores = df_MAR.isnull().sum()

Missing values in data

In [ ]:
valores.head(50)

host_since                                         5
host_is_superhost                               1343
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms_text                                    27
bedrooms                                         971
beds                                            4022
amenities                                          0
price                                           3999
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
number_of_reviews                                  0
review_scores_rating                            3261
review_scores_location                          3262
review_scores_value                             3262
instant_bookable                                   0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
dtype: int64

In [ ]:
unique_values_count = df_MAR.nunique()
unique_values_df = pd.DataFrame(unique_values_count, columns=['Unique Values Count'])
display(unique_values_df)

                                              Unique Values Count
host_since                                                   4123
host_is_superhost                                               2
neighbourhood_cleansed                                         16
latitude                                                    17167
longitude                                                   16091
property_type                                                  82
room_type                                                       4
accommodates                                                   16
bathrooms_text                                                 58
bedrooms                                                       24
beds                                                           30
amenities                                                   24260
price                                                        4068
minimum_nights                                                 72
maximum_nights                                                201
minimum_minimum_nights                                         74
maximum_minimum_nights                                         75
minimum_maximum_nights                                        165
maximum_maximum_nights                                        170
minimum_nights_avg_ntm                                        205
maximum_nights_avg_ntm                                        554
availability_30                                                31
availability_60                                                61
availability_90                                                91
availability_365                                              366
number_of_reviews                                             550
review_scores_rating                                          140
review_scores_location                                        136
review_scores_value                                           150
instant_bookable                                                2
calculated_host_listings_count_entire_homes                    54
calculated_host_listings_count_private_rooms                   36
calculated_host_listings_count_shared_rooms                    10

"host_since" Como pasamos a variables, solo ocupamos el año, en concreto para categorizarlo
"host_is_superhost" PAsar a valores binarios
"neighbourhood_cleansed" Será buena idea pasarlo a variables categoricas? son 16 valores
"property_type" Analizar porque toma 82 valores diferentes
"instant_bookable" Pasar a valores binarios
"room_type" Pasar a valores categoricos 1,2,3,4

In [ ]:
import pandas as pd
import numpy as np

# --- Columnas Numéricas ---
# Seleccionamos las columnas que son de tipo numérico (incluye enteros y flotantes)
columnas_numericas = df_MAR.select_dtypes(include=np.number).columns.tolist()

# --- Columnas Categóricas ---
# 'category', que son los tipos más comunes para datos categóricos.
columnas_categoricas = df_MAR.select_dtypes(include=['object', 'category']).columns.tolist()

print("✅ Columnas Numéricas:")
print(columnas_numericas)

print("\n-------------------------\n")

print("✅ Columnas Categóricas:")
print(columnas_categoricas)

✅ Columnas Numéricas:
['latitude', 'longitude', 'accommodates', 'bedrooms', 'beds', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'number_of_reviews', 'review_scores_rating', 'review_scores_location', 'review_scores_value', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms']

-------------------------

✅ Columnas Categóricas:
['host_since', 'host_is_superhost', 'neighbourhood_cleansed', 'property_type', 'room_type', 'bathrooms_text', 'amenities', 'price', 'instant_bookable']

*Variables Categoricas a numericas*

In [ ]:

# Sobrescribir la columna con solo el año
df_MAR["host_since"] = pd.to_datetime(df_MAR["host_since"], format="%Y-%m-%d", errors="coerce")\
                       .dt.year.astype("Int64")
df_MAR["host_since"] = 2025 - df_MAR["host_since"]

In [ ]:
df_MAR["host_since"]

0        15
1        15
2        15
3        14
4        15
         ..
26062     6
26063     7
26064    10
26065     2
26066     7
Name: host_since, Length: 26067, dtype: Int64

In [ ]:
df_MAR['host_is_superhost'] = (df_MAR['host_is_superhost'] == 't').astype(int)

In [ ]:
df_MAR['instant_bookable'] = (df_MAR['instant_bookable'] == 't').astype(int)

In [ ]:
df_MAR['host_is_superhost']

0        0
1        0
2        0
3        1
4        1
        ..
26062    0
26063    0
26064    1
26065    1
26066    0
Name: host_is_superhost, Length: 26067, dtype: int64

In [ ]:
df_MAR['instant_bookable']

0        0
1        0
2        0
3        0
4        0
        ..
26062    1
26063    0
26064    0
26065    1
26066    0
Name: instant_bookable, Length: 26067, dtype: int64

In [ ]:
df_MAR['price']

0        $3,982.00
1              NaN
2          $585.00
3              NaN
4        $1,015.00
           ...
26062      $529.00
26063      $472.00
26064      $399.00
26065    $1,494.00
26066    $1,722.00
Name: price, Length: 26067, dtype: object

In [ ]:
#Llimpieza de la columna de precios
df_MAR['price'] = df_MAR['price'].replace({'\$': '', ',': ''}, regex=True).astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipython-input-1720859638.py:2: SyntaxWarning: invalid escape sequence '\$'
  df_MAR['price'] = df_MAR['price'].replace({'\$': '', ',': ''}, regex=True).astype(float)

In [ ]:
# Extraer el número de la columna de texto
df_MAR['bathrooms_text'] = df_MAR['bathrooms_text'].str.extract('(\d+\.?\d*)').astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipython-input-173143769.py:2: SyntaxWarning: invalid escape sequence '\d'
  df_MAR['bathrooms_text'] = df_MAR['bathrooms_text'].str.extract('(\d+\.?\d*)').astype(float)

In [ ]:
df_MAR['bathrooms_text']

0        1.0
1        5.5
2        1.0
3        1.0
4        1.0
        ...
26062    1.0
26063    1.0
26064    1.0
26065    1.0
26066    2.0
Name: bathrooms_text, Length: 26067, dtype: float64

In [ ]:
df_MAR['latitude'] = pd.to_numeric(df_MAR['latitude'], errors='coerce')
df_MAR['longitude'] = pd.to_numeric(df_MAR['longitude'], errors='coerce')

In [ ]:
import pandas as pd
import numpy as np

# --- Columnas Numéricas ---
# Seleccionamos las columnas que son de tipo numérico (incluye enteros y flotantes)
columnas_numericas = df_MAR.select_dtypes(include=np.number).columns.tolist()

# --- Columnas Categóricas ---

# 'category', que son los tipos más comunes para datos categóricos.
columnas_categoricas = df_MAR.select_dtypes(include=['object', 'category']).columns.tolist()

print("✅ Columnas Numéricas:")
print(columnas_numericas)

print("\n-------------------------\n")

print("✅ Columnas Categóricas:")
print(columnas_categoricas)

✅ Columnas Numéricas:
['host_since', 'host_is_superhost', 'latitude', 'longitude', 'accommodates', 'bathrooms_text', 'bedrooms', 'beds', 'price', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'number_of_reviews', 'review_scores_rating', 'review_scores_location', 'review_scores_value', 'instant_bookable', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms']

-------------------------

✅ Columnas Categóricas:
['neighbourhood_cleansed', 'property_type', 'room_type', 'amenities']

In [ ]:
unique_values_count = df_MAR.nunique()
unique_values_df_MAR = pd.DataFrame(unique_values_count, columns=['Unique Values Count'])
display(unique_values_df_MAR)

                                              Unique Values Count
host_since                                                     17
host_is_superhost                                               2
neighbourhood_cleansed                                         16
latitude                                                    17167
longitude                                                   16091
property_type                                                  82
room_type                                                       4
accommodates                                                   16
bathrooms_text                                                 34
bedrooms                                                       24
beds                                                           30
amenities                                                   24260
price                                                        4068
minimum_nights                                                 72
maximum_nights                                                201
minimum_minimum_nights                                         74
maximum_minimum_nights                                         75
minimum_maximum_nights                                        165
maximum_maximum_nights                                        170
minimum_nights_avg_ntm                                        205
maximum_nights_avg_ntm                                        554
availability_30                                                31
availability_60                                                61
availability_90                                                91
availability_365                                              366
number_of_reviews                                             550
review_scores_rating                                          140
review_scores_location                                        136
review_scores_value                                           150
instant_bookable                                                2
calculated_host_listings_count_entire_homes                    54
calculated_host_listings_count_private_rooms                   36
calculated_host_listings_count_shared_rooms                    10

In [ ]:
df_MAR

,host_since,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,...,availability_60,availability_90,availability_365,review_scores_rating,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,2010,0,Cuajimalpa de Morelos,19.382830,-99.271780,Entire villa,Entire home/apt,2,1.0,1.0,...,58,88,363,NaN,NaN,NaN,0,1,0,0
1,2010,0,Cuauhtémoc,19.411620,-99.177940,Entire home,Entire home/apt,14,NaN,5.5,...,59,89,364,4.59,4.98,4.47,0,4,2,0
2,2010,0,Cuauhtémoc,19.439770,-99.156050,Entire condo,Entire home/apt,2,1.0,1.0,...,56,86,361,4.87,4.76,4.79,0,1,0,0
3,2011,0,Cuauhtémoc,19.411520,-99.168570,Entire rental unit,Entire home/apt,4,NaN,1.0,...,2,32,307,4.90,4.98,4.92,0,2,0,0
4,2010,0,Coyoacán,19.354480,-99.162170,Entire rental unit,Entire home/apt,2,1.0,1.0,...,6,23,245,4.92,4.96,4.92,0,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26062,2019,0,Cuauhtémoc,19.430390,-99.134282,Shared room in hotel,Shared room,4,1.0,1.0,...,60,90,344,NaN,NaN,NaN,0,0,4,4
26063,2018,0,Cuauhtémoc,19.439520,-99.152520,Private room in loft,Private room,2,1.0,1.0,...,22,49,324,NaN,NaN,NaN,0,0,1,0
26064,2015,0,Cuauhtémoc,19.417618,-99.166841,Private room in rental unit,Private room,1,1.0,1.0,...,35,65,340,NaN,NaN,NaN,0,0,2,0
26065,2023,0,Miguel Hidalgo,19.428857,-99.177626,Entire rental unit,Entire home/apt,2,1.0,1.0,...,57,87,362,NaN,NaN,NaN,0,32,0,0
26066,2018,0,Cuauhtémoc,19.416223,-99.156934,Entire rental unit,Entire home/apt,6,2.0,2.0,...,51,81,81,NaN,NaN,NaN,0,1,0,0

In [ ]:
#Cuantifica valores faltantes por columna.
print('Missing values in data')
valores = df_MAR.isnull().sum()

Missing values in data

In [ ]:
valores

host_since                                         5
host_is_superhost                                  0
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                       4005
bathrooms_text                                   111
bedrooms                                         971
beds                                            4022
amenities                                          0
price                                           3999
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
review_scores_rating                            3261
review_scores_location                          3262
review_scores_value                             3262
instant_bookable                                   0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
dtype: int64

###¿Ahora qué hacemos con los valores nulos ?

In [ ]:
# Calculamos la moda en la columna 'host_since', pues al ser 5 datos faltantes podemos imputar.
mode_host_since = df_MAR['host_since'].mode()[0]

# rellenamos con la moda dichos datos
df_MAR['host_since'] = df_MAR['host_since'].fillna(mode_host_since).astype(int)

# Verificamos
print('Valores nulos despues de la imputation:', df_MAR['host_since'].isnull().sum())

Valores nulos despues de la imputation: 0

In [ ]:
df_MAR

,host_since,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,...,availability_60,availability_90,availability_365,review_scores_rating,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,2010-06-28,f,Cuajimalpa de Morelos,19.382830,-99.271780,Entire villa,Entire home/apt,2,1.0,1.0,...,58,88,363,NaN,NaN,NaN,f,1,0,0
1,2010-08-09,f,Cuauhtémoc,19.411620,-99.177940,Entire home,Entire home/apt,14,NaN,5.5,...,59,89,364,4.59,4.98,4.47,f,4,2,0
2,2010-10-19,f,Cuauhtémoc,19.439770,-99.156050,Entire condo,Entire home/apt,2,1.0,1.0,...,56,86,361,4.87,4.76,4.79,f,1,0,0
3,2011-01-04,t,Cuauhtémoc,19.411520,-99.168570,Entire rental unit,Entire home/apt,4,NaN,1.0,...,2,32,307,4.90,4.98,4.92,f,2,0,0
4,2010-08-24,t,Coyoacán,19.354480,-99.162170,Entire rental unit,Entire home/apt,2,1.0,1.0,...,6,23,245,4.92,4.96,4.92,f,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26062,2019-05-10,f,Cuauhtémoc,19.430390,-99.134282,Shared room in hotel,Shared room,4,1.0,1.0,...,60,90,344,NaN,NaN,NaN,t,0,4,4
26063,2018-02-26,f,Cuauhtémoc,19.439520,-99.152520,Private room in loft,Private room,2,1.0,1.0,...,22,49,324,NaN,NaN,NaN,f,0,1,0
26064,2015-05-31,t,Cuauhtémoc,19.417618,-99.166841,Private room in rental unit,Private room,1,1.0,1.0,...,35,65,340,NaN,NaN,NaN,f,0,2,0
26065,2023-05-16,t,Miguel Hidalgo,19.428857,-99.177626,Entire rental unit,Entire home/apt,2,1.0,1.0,...,57,87,362,NaN,NaN,NaN,t,32,0,0
26066,2018-05-12,f,Cuauhtémoc,19.416223,-99.156934,Entire rental unit,Entire home/apt,6,2.0,2.0,...,51,81,81,NaN,NaN,NaN,f,1,0,0

In [ ]:
# Define the desired output path and filename
output_path = '/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/df_MAR2.csv'

df_MAR.to_csv(output_path, index=False)

print(f"Archivo guardado  df_MAR en {output_path}")

Attempting to save df_MAR to /content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/df_MAR2.csv

In [ ]:
df_MAR['bathrooms_text']

0        1.0
1        5.5
2        1.0
3        1.0
4        1.0
        ...
26062    1.0
26063    1.0
26064    1.0
26065    1.0
26066    2.0
Name: bathrooms_text, Length: 26067, dtype: float64

In [ ]:

df_baths = listings_gz_MAR.loc[:, ["bathrooms_text", "bathrooms"]].copy()

  bathrooms_text  bathrooms
0         1 bath        1.0
1      5.5 baths        NaN
2         1 bath        1.0
3         1 bath        NaN
4         1 bath        1.0

In [ ]:
# Filas donde al menos una de las dos columnas es nula
df_baths_na = df_baths[df_baths.isna().any(axis=1)]

# Mantener solo filas donde ambas NO son nulas
df_boths_present = df_baths.dropna(subset=["bathrooms_text", "bathrooms"], how="any")

In [ ]:
df_baths_na

       bathrooms_text  bathrooms
1           5.5 baths        NaN
3              1 bath        NaN
5      1 private bath        NaN
9              1 bath        NaN
10            2 baths        NaN
...               ...        ...
25446          1 bath        NaN
25512          1 bath        NaN
25514       1.5 baths        NaN
25529          1 bath        NaN
25697             NaN        NaN

[4018 rows x 2 columns]

In [ ]:
import numpy as np
import pandas as pd

def parse_bathrooms_text(s):
    s = s.astype(str).str.lower().str.strip()
    out = pd.Series(np.nan, index=s.index, dtype=float)
    # “half bath” sin número
    out[s.str.contains("half") & ~s.str.contains(r"\d")] = 0.5
    num = pd.to_numeric(s.str.extract(r"(\d+(\.\d+)?)")[0], errors="coerce")
    return out.fillna(num)

df_baths["bathrooms_parsed"] = parse_bathrooms_text(df_baths["bathrooms_text"])

In [ ]:
df_baths

       bathrooms_text  bathrooms  bathrooms_parsed
0              1 bath        1.0               1.0
1           5.5 baths        NaN               5.5
2              1 bath        1.0               1.0
3              1 bath        NaN               1.0
4              1 bath        1.0               1.0
...               ...        ...               ...
26062   1 shared bath        1.0               1.0
26063  1 private bath        1.0               1.0
26064   1 shared bath        1.0               1.0
26065          1 bath        1.0               1.0
26066         2 baths        2.0               2.0

[26067 rows x 3 columns]

#AIRBNB JUN 2025

In [ ]:
listings_gz_JUN = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /25 JUN 2025/listings.csv.gz")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /25 JUN 2025/listings.csv.gz'

In [ ]:
calendar_gz_JUN =  pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /25 JUN 2025/calendar.csv.gz")

In [ ]:
output_path = '/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/listings_gz_JUN.csv'

listings_gz_JUN.to_csv(output_path, index=False)

Attempting to save df_MAR to /content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/listings_gz_JUN.csv

In [ ]:
# Sobrescribir la columna con solo el año
listings_gz_JUN["host_since"] = pd.to_datetime(listings_gz_JUN["host_since"], format="%Y-%m-%d", errors="coerce")\
                       .dt.year.astype("Int64")
lis

In [ ]:
# La idea de este algoritmo es que a partir de la base de datos original "listings_gz_JUN", el "host_id"
#se repite es mas de una fila, por lo que podriamos buscar si en alguna de estas filas el valor en la columna
#"host_since" es no nulo, para rellenar esos 914 valores nulos.


df = listings_gz_JUN.copy()
df['host_id'] = df['host_id'].astype('string')  # pasamos a como año nada mas

#  Medimos faltantes o nulos
mask_null_orig = df['host_since'].isna()
n_missing_orig = int(mask_null_orig.sum())


donor_map = (
    df.dropna(subset=['host_since'])
      .groupby('host_id', as_index=True)['host_since']
      .min()   # año más antiguo observado para ese host
)


# Calcular imputaciones solo para las filas que estaban nulas
imputaciones = (
    df.loc[mask_null_orig, ['host_id']]
      .assign(imputed_year = lambda d: d['host_id'].map(donor_map))
      .dropna(subset=['imputed_year'])
)

imputaciones = imputaciones.sort_values(['imputed_year','host_id']).reset_index(drop=True)

host_since_filled = df['host_since'].copy()
host_since_filled = host_since_filled.fillna(
    pd.to_numeric(df['host_id'].map(donor_map), errors='coerce')
).astype('Int64')

df['host_since_filled'] = host_since_filled

#  Resumen
n_recovered = len(imputaciones)          # cuántas filas nulas recibieron valor
n_still_null = int(df['host_since_filled'].isna().sum())

print(f"Faltantes originales: {n_missing_orig}")
print(f"Recuperados con otros anuncios del mismo host: {n_recovered}")
print(f"Persisten nulos tras imputar: {n_still_null}")

print('\nImputaciones (host_id -> año):')
print(imputaciones)


anios_imputados_unicos = sorted(imputaciones['imputed_year'].unique().tolist())
print('\nAños imputados únicos:', anios_imputados_unicos)

Faltantes originales: 914
Recuperados con otros anuncios del mismo host: 0
Persisten nulos tras imputar: 914

Imputaciones (host_id -> año):
Empty DataFrame
Columns: [host_id, imputed_year]
Index: []

Años imputados únicos: []

In [ ]:
import pandas as pd


listings_gz_JUN = listings_gz_JUN.copy()
listings_gz_JUN['host_id'] = listings_gz_JUN['host_id'].astype(str)
listings_gz_JUN['host_since'] = pd.to_datetime(listings_gz_JUN['host_since'], errors='coerce')

# 1) host_id de filas con host_since nulo
mask_null = listings_gz_JUN['host_since'].isna()
host_ids_null = listings_gz_JUN.loc[mask_null, 'host_id'].dropna().unique()

# 2) ¿Se repiten con host_since NO nulo en otras filas de JUN?
repetidos_no_nulos_JUN = listings_gz_JUN.loc[
    (~listings_gz_JUN['host_since'].isna()) &
    (listings_gz_JUN['host_id'].isin(host_ids_null)),
    ['host_id', 'host_since']
].sort_values(['host_id','host_since'])

# 3) Resumen por host_id (cuántas veces aparecen nulos/no nulos en JUN)
resumen_JUN = (
    listings_gz_JUN
      .assign(is_null=listings_gz_JUN['host_since'].isna())
      .groupby('host_id')['is_null']
      .value_counts()
      .unstack(fill_value=0)
      .rename(columns={False:'non_null_rows_JUN', True:'null_rows_JUN'})
      .loc[host_ids_null]              # solo los host_id que tenían algún nulo
      .sort_values(['non_null_rows_JUN','null_rows_JUN'], ascending=False)
)

In [ ]:
resumen_JUN

is_null    non_null_rows_JUN  null_rows_JUN
host_id
302431514                  0             80
5755202                    0             39
35255741                   0             25
150172688                  0             25
359943588                  0             23
...                      ...            ...
409324242                  0              1
67107337                   0              1
75567625                   0              1
702120436                  0              1
442011462                  0              1

[306 rows x 2 columns]

In [ ]:
df_JUN = listings_gz_JUN.copy()

In [ ]:
df_JUN.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [ ]:
cols_to_drop = [
    "id",
    "listing_url",
    "scrape_id",
    "last_scraped",
    "name",
    "picture_url",
    "host_id",
    "host_url",
    "host_name",
    "host_response_time",
    "host_response_rate",
    "host_acceptance_rate",
    "host_thumbnail_url",
    "host_picture_url",
    "host_listings_count",
    "ost_listings_count",
    "host_total_listings_count",
    "host_verifications",
    "host_has_profile_pic",
    "host_identity_verified",
    "neighbourhood",
    "calendar_updated",
    "calendar_last_scraped",
    #"number_of_reviews",
    "number_of_reviews_ltm",
    "number_of_reviews_l30d",
    "availability_eoy",
    "number_of_reviews_ly",
    "first_review",
    "last_review",
    #"review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "calculated_host_listings_count",
    "reviews_per_month",
    "neighbourhood_group_cleansed",
    "license",
    "description",
    "neighborhood_overview",

    "host_about", # Se agregaron estas columnas puesto que eran descripcion.
    "host_neighbourhood",
    "source",
    "has_availability",
    "host_location", # Se agrego esta columna puesto que en la limpieza de sus valores nuelos me percate que solo toma el valor de ciudad de mexico, es decir, una columna de un solo valor.
    "estimated_occupancy_l365d" , #Se eliminaron estas columnas puesto que solo aparecen en la informacion de los meses del año 2025.
"estimated_revenue_l365d",
"bathrooms"
]

In [ ]:
df_JUN.drop(columns=cols_to_drop, inplace=True, errors="ignore")

In [ ]:
df_JUN

,host_since,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,...,availability_30,availability_60,availability_90,availability_365,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,1970-01-01 00:00:00.000002010,f,Cuajimalpa de Morelos,19.382830,-99.271780,Entire villa,Entire home/apt,2,1.0,1 bath,...,29,59,89,364,NaN,NaN,f,1,0,0
1,1970-01-01 00:00:00.000002010,f,Cuauhtémoc,19.411620,-99.177940,Entire home,Entire home/apt,14,5.5,5.5 baths,...,29,59,89,360,4.98,4.47,f,4,2,0
2,1970-01-01 00:00:00.000002010,f,Cuauhtémoc,19.439770,-99.156050,Entire condo,Entire home/apt,2,1.0,1 bath,...,3,33,63,338,4.76,4.79,f,1,0,0
3,1970-01-01 00:00:00.000002011,f,Cuauhtémoc,19.411520,-99.168570,Entire rental unit,Entire home/apt,4,1.0,1 bath,...,3,4,32,267,4.98,4.92,f,2,0,0
4,1970-01-01 00:00:00.000002010,t,Coyoacán,19.354480,-99.162170,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,10,25,25,211,4.96,4.92,f,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26396,1970-01-01 00:00:00.000002018,f,Azcapotzalco,19.490670,-99.174150,Entire condo,Entire home/apt,6,1.0,1 bath,...,29,57,84,359,4.00,5.00,t,1,0,0
26397,1970-01-01 00:00:00.000002020,NaN,Benito Juárez,19.391438,-99.181881,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,29,59,89,364,NaN,NaN,t,14,0,0
26398,1970-01-01 00:00:00.000002024,t,Cuauhtémoc,19.419767,-99.175294,Entire rental unit,Entire home/apt,4,1.0,1 bath,...,29,59,89,364,NaN,NaN,f,3,3,0
26399,1970-01-01 00:00:00.000002014,f,Cuauhtémoc,19.441713,-99.161810,Entire loft,Entire home/apt,2,1.0,1 bath,...,6,36,66,341,NaN,NaN,f,1,0,0
26400,1970-01-01 00:00:00.000002025,f,Miguel Hidalgo,19.427570,-99.175410,Entire rental unit,Entire home/apt,6,2.0,2 baths,...,30,60,90,270,NaN,NaN,f,1,0,0

In [ ]:
#Cuantifica valores faltantes por columna.
print('Missing values in data')
valores = df_JUN.isnull().sum()

Missing values in data

In [ ]:
valores.head(50)

host_since                                       914
host_is_superhost                               1359
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                       3281
bathrooms_text                                    31
bedrooms                                         924
beds                                            3297
amenities                                          0
price                                           3274
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                            20
maximum_minimum_nights                            20
minimum_maximum_nights                            20
maximum_maximum_nights                            20
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
review_scores_location                          3375
review_scores_value                             3375
instant_bookable                                   0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
dtype: int64

In [ ]:
unique_values_count = df_JUN.nunique()
unique_values_df = pd.DataFrame(unique_values_count, columns=['Unique Values Count'])
display(unique_values_df)

                                              Unique Values Count
host_since                                                     17
host_is_superhost                                               2
neighbourhood_cleansed                                         16
latitude                                                    17536
longitude                                                   16455
property_type                                                  80
room_type                                                       4
accommodates                                                   16
bathrooms                                                      34
bathrooms_text                                                 59
bedrooms                                                       24
beds                                                           32
amenities                                                   25044
price                                                        3957
minimum_nights                                                 69
maximum_nights                                                192
minimum_minimum_nights                                         72
maximum_minimum_nights                                         75
minimum_maximum_nights                                        163
maximum_maximum_nights                                        167
minimum_nights_avg_ntm                                        204
maximum_nights_avg_ntm                                        605
availability_30                                                31
availability_60                                                61
availability_90                                                91
availability_365                                              366
review_scores_location                                        128
review_scores_value                                           155
instant_bookable                                                2
calculated_host_listings_count_entire_homes                    54
calculated_host_listings_count_private_rooms                   34
calculated_host_listings_count_shared_rooms                    13

In [ ]:
import pandas as pd
import numpy as np

# --- Columnas Numéricas ---
# Seleccionamos las columnas que son de tipo numérico (incluye enteros y flotantes)
columnas_numericas = df_JUN.select_dtypes(include=np.number).columns.tolist()

# --- Columnas Categóricas ---
# 'category', que son los tipos más comunes para datos categóricos.
columnas_categoricas = df_JUN.select_dtypes(include=['object', 'category']).columns.tolist()

print("✅ Columnas Numéricas:")
print(columnas_numericas)

print("\n-------------------------\n")

print("✅ Columnas Categóricas:")
print(columnas_categoricas)

✅ Columnas Numéricas:
['latitude', 'longitude', 'accommodates', 'bedrooms', 'beds', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'number_of_reviews', 'review_scores_rating', 'review_scores_location', 'review_scores_value', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms']

-------------------------

✅ Columnas Categóricas:
['host_since', 'host_is_superhost', 'neighbourhood_cleansed', 'property_type', 'room_type', 'bathrooms_text', 'amenities', 'price', 'instant_bookable']

In [ ]:

# Sobrescribir la columna con solo el año
df_JUN["host_since"] = pd.to_datetime(df_JUN["host_since"], format="%Y-%m-%d", errors="coerce")\
                       .dt.year.astype("Int64")
df_JUN["host_since"] = 2025 - df_JUN["host_since"]

In [ ]:
df_JUN["host_since"]

0        15
1        15
2        15
3        14
4        15
         ..
26396     7
26397     5
26398     1
26399    11
26400     0
Name: host_since, Length: 26401, dtype: Int64

In [ ]:
df_JUN['host_is_superhost'] = (df_JUN['host_is_superhost'] == 't').astype(int)

In [ ]:
df_JUN['instant_bookable'] = (df_JUN['instant_bookable'] == 't').astype(int)

In [ ]:
#Llimpieza de la columna de precios
df_JUN['price'] = df_JUN['price'].replace({'\$': '', ',': ''}, regex=True).astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipython-input-4228675643.py:2: SyntaxWarning: invalid escape sequence '\$'
  df_JUN['price'] = df_JUN['price'].replace({'\$': '', ',': ''}, regex=True).astype(float)

In [ ]:
# Extraer el número de la columna de texto (ejemplo simple)
df_JUN['bathrooms_text'] = df_JUN['bathrooms_text'].str.extract('(\d+\.?\d*)').astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipython-input-3561386506.py:2: SyntaxWarning: invalid escape sequence '\d'
  df_JUN['bathrooms_text'] = df_JUN['bathrooms_text'].str.extract('(\d+\.?\d*)').astype(float)

In [ ]:
df_JUN['latitude'] = pd.to_numeric(df_JUN['latitude'], errors='coerce')
df_JUN['longitude'] = pd.to_numeric(df_JUN['longitude'], errors='coerce')

In [ ]:
import pandas as pd
import numpy as np

# --- Columnas Numéricas ---
# Seleccionamos las columnas que son de tipo numérico (incluye enteros y flotantes)
columnas_numericas = df_JUN.select_dtypes(include=np.number).columns.tolist()

# --- Columnas Categóricas ---

# 'category', que son los tipos más comunes para datos categóricos.
columnas_categoricas = df_JUN.select_dtypes(include=['object', 'category']).columns.tolist()

print("✅ Columnas Numéricas:")
print(columnas_numericas)

print("\n-------------------------\n")

print("✅ Columnas Categóricas:")
print(columnas_categoricas)

✅ Columnas Numéricas:
['host_since', 'host_is_superhost', 'latitude', 'longitude', 'accommodates', 'bathrooms_text', 'bedrooms', 'beds', 'price', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'number_of_reviews', 'review_scores_rating', 'review_scores_location', 'review_scores_value', 'instant_bookable', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms']

-------------------------

✅ Columnas Categóricas:
['neighbourhood_cleansed', 'property_type', 'room_type', 'amenities']

In [ ]:
unique_values_count = df_JUN.nunique()
unique_values_df_JUN = pd.DataFrame(unique_values_count, columns=['Unique Values Count'])
display(unique_values_df_JUN)

                                              Unique Values Count
host_since                                                      1
host_is_superhost                                               2
neighbourhood_cleansed                                         16
latitude                                                    17536
longitude                                                   16455
property_type                                                  80
room_type                                                       4
accommodates                                                   16
bathrooms                                                      34
bathrooms_text                                                 34
bedrooms                                                       24
beds                                                           32
amenities                                                   25044
price                                                        3957
minimum_nights                                                 69
maximum_nights                                                192
minimum_minimum_nights                                         72
maximum_minimum_nights                                         75
minimum_maximum_nights                                        163
maximum_maximum_nights                                        167
minimum_nights_avg_ntm                                        204
maximum_nights_avg_ntm                                        605
availability_30                                                31
availability_60                                                61
availability_90                                                91
availability_365                                              366
review_scores_location                                        128
review_scores_value                                           155
instant_bookable                                                2
calculated_host_listings_count_entire_homes                    54
calculated_host_listings_count_private_rooms                   34
calculated_host_listings_count_shared_rooms                    13

In [ ]:
#df_JUN[df_JUN['host_location'] != 'Mexico City, Mexico']

In [ ]:
df_JUN

,host_since,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,...,availability_30,availability_60,availability_90,availability_365,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,1970,0,Cuajimalpa de Morelos,19.382830,-99.271780,Entire villa,Entire home/apt,2,1.0,1.0,...,29,59,89,364,NaN,NaN,0,1,0,0
1,1970,0,Cuauhtémoc,19.411620,-99.177940,Entire home,Entire home/apt,14,5.5,5.5,...,29,59,89,360,4.98,4.47,0,4,2,0
2,1970,0,Cuauhtémoc,19.439770,-99.156050,Entire condo,Entire home/apt,2,1.0,1.0,...,3,33,63,338,4.76,4.79,0,1,0,0
3,1970,0,Cuauhtémoc,19.411520,-99.168570,Entire rental unit,Entire home/apt,4,1.0,1.0,...,3,4,32,267,4.98,4.92,0,2,0,0
4,1970,1,Coyoacán,19.354480,-99.162170,Entire rental unit,Entire home/apt,2,1.0,1.0,...,10,25,25,211,4.96,4.92,0,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26396,1970,0,Azcapotzalco,19.490670,-99.174150,Entire condo,Entire home/apt,6,1.0,1.0,...,29,57,84,359,4.00,5.00,1,1,0,0
26397,1970,0,Benito Juárez,19.391438,-99.181881,Entire rental unit,Entire home/apt,2,1.0,1.0,...,29,59,89,364,NaN,NaN,1,14,0,0
26398,1970,1,Cuauhtémoc,19.419767,-99.175294,Entire rental unit,Entire home/apt,4,1.0,1.0,...,29,59,89,364,NaN,NaN,0,3,3,0
26399,1970,0,Cuauhtémoc,19.441713,-99.161810,Entire loft,Entire home/apt,2,1.0,1.0,...,6,36,66,341,NaN,NaN,0,1,0,0
26400,1970,0,Miguel Hidalgo,19.427570,-99.175410,Entire rental unit,Entire home/apt,6,2.0,2.0,...,30,60,90,270,NaN,NaN,0,1,0,0

In [ ]:
print(df_JUN["host_since"].unique())

<IntegerArray>
[1970, <NA>]
Length: 2, dtype: Int64

In [ ]:
#Cuantifica valores faltantes por columna.
print('Missing values in data')
valores = df_JUN.isnull().sum()

Missing values in data

In [ ]:
valores

host_since                                       914
host_is_superhost                                  0
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                       3281
bathrooms_text                                   123
bedrooms                                         924
beds                                            3297
amenities                                          0
price                                           3274
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                            20
maximum_minimum_nights                            20
minimum_maximum_nights                            20
maximum_maximum_nights                            20
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
review_scores_location                          3375
review_scores_value                             3375
instant_bookable                                   0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
dtype: int64

In [ ]:
import pandas as pd
import numpy as np

# ----- 1) Contar nulos por fila y decidir qué filas eliminar -----
thr = 7  # umbral de nulos por fila
row_na = df_JUN.isna().sum(axis=1)

# filas candidatas a eliminar (≥5 nulos)
idx_drop = row_na[row_na >= thr].index
pct_drop = 100 * len(idx_drop) / len(df_JUN)
2
print(f"Filas con ≥{thr} nulos: {len(idx_drop)} ({pct_drop:.2f}%)")

# Si decides eliminarlas:
df_JUN2 = df_JUN.loc[row_na < thr].copy()

Filas con ≥7 nulos: 4 (0.02%)

In [ ]:
# columnas más ausentes dentro de las filas problemáticas
if len(idx_drop) > 0:
    print(df_JUN.loc[idx_drop].isna().sum().sort_values(ascending=False).head(15))

price                     4
beds                      4
bedrooms                  4
bathrooms                 4
review_scores_value       4
review_scores_location    4
bathrooms_text            3
host_since                1
accommodates              0
room_type                 0
property_type             0
longitude                 0
latitude                  0
amenities                 0
neighbourhood_cleansed    0
dtype: int64

#AIRBNB DIC 24

In [ ]:
listings_gz_DIC = pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /27 DIC 24/listings.csv.gz")

In [ ]:
calendar_gz_DIC =  pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /27 DIC 24/calendar.csv.gz")

In [ ]:
output_path = '/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/listings_gz_DIC.csv'
listings_gz_DIC.to_csv(output_path, index=False)
print(f"Attempting to save df_MAR to {output_path}")

Attempting to save df_MAR to /content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/listings_gz_DIC.csv

In [ ]:
listings_gz_DIC.to_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/listings_gz_DIC.csv", index=False)

In [ ]:
df_DIC = listings_gz_DIC.copy()

In [ ]:
df_DIC.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [ ]:
cols_to_drop = [
    "id",
    "listing_url",
    "scrape_id",
    "last_scraped",
    "name",
    "picture_url",
    "host_id",
    "host_url",
    "host_name",
    "host_response_time",
    "host_response_rate",
    "host_acceptance_rate",
    "host_thumbnail_url",
    "host_picture_url",
    "host_listings_count",
    "ost_listings_count",
    "host_total_listings_count",
    "host_verifications",
    "host_has_profile_pic",
    "host_identity_verified",
    "neighbourhood",
    "calendar_updated",
    "calendar_last_scraped",
    #"number_of_reviews",
    "number_of_reviews_ltm",
    "number_of_reviews_l30d",
    "availability_eoy",
    "number_of_reviews_ly",
    "first_review",
    "last_review",
   # "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "calculated_host_listings_count",
    "reviews_per_month",
    "neighbourhood_group_cleansed",
    "license",
    "description",
    "neighborhood_overview",
    "host_about",
    "host_neighbourhood",
    "source",
    "has_availability",
    "host_location" # Se agrego esta columna puesto que en la limpieza de sus valores nuelos me percate que solo toma el valor de ciudad de mexico, es decir, una columna de un solo valor.
    "bathrooms"

]

In [ ]:
df_DIC.drop(columns=cols_to_drop, inplace=True, errors="ignore")

In [ ]:
df_DIC

,host_since,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,...,availability_30,availability_60,availability_90,availability_365,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,2010-06-28,f,Cuajimalpa de Morelos,19.382830,-99.271780,Entire villa,Entire home/apt,2,1.0,1 bath,...,28,58,88,363,NaN,NaN,f,1,0,0
1,2010-08-09,t,Cuauhtémoc,19.411620,-99.177940,Entire home,Entire home/apt,14,5.5,5.5 baths,...,22,52,82,357,4.98,4.48,f,4,1,0
2,2011-01-04,t,Cuauhtémoc,19.411520,-99.168570,Entire rental unit,Entire home/apt,4,1.0,1 bath,...,22,38,68,343,4.98,4.92,f,2,0,0
3,2010-08-24,t,Coyoacán,19.354480,-99.162170,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,2,2,10,285,4.96,4.92,f,2,1,0
4,2011-05-31,f,Coyoacán,19.354160,-99.164880,Private room,Private room,2,NaN,1 private bath,...,0,0,0,0,NaN,NaN,f,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26276,2020-09-26,f,Miguel Hidalgo,19.436998,-99.196733,Room in hotel,Private room,2,1.0,1 private bath,...,29,59,89,363,NaN,NaN,t,0,12,0
26277,2023-07-13,f,Cuauhtémoc,19.449230,-99.136170,Entire rental unit,Entire home/apt,3,1.0,1 bath,...,30,60,90,365,NaN,NaN,t,1,0,0
26278,2019-09-10,f,Coyoacán,19.316820,-99.116781,Shared room in rental unit,Shared room,6,2.0,2 shared baths,...,30,60,90,365,NaN,NaN,t,0,5,3
26279,2015-06-07,t,Miguel Hidalgo,19.400096,-99.172981,Entire rental unit,Entire home/apt,9,3.0,3 baths,...,24,54,84,359,NaN,NaN,t,31,0,0
26280,2020-02-02,t,Cuauhtémoc,19.427799,-99.163842,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,26,56,86,325,NaN,NaN,t,182,1,0

In [ ]:
#Cuantifica valores faltantes por columna.
print('Missing values in data')
valores = df_DIC.isnull().sum()

Missing values in data

In [ ]:
valores.head(50)

host_since                                         3
host_is_superhost                               1382
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                       3804
bathrooms_text                                    28
bedrooms                                         951
beds                                            3825
amenities                                          0
price                                           3815
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
review_scores_location                          3297
review_scores_value                             3297
instant_bookable                                   0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
dtype: int64

In [ ]:
unique_values_count = df_DIC.nunique()
unique_values_df = pd.DataFrame(unique_values_count, columns=['Unique Values Count'])
display(unique_values_df)

                                              Unique Values Count
host_since                                                   4090
host_is_superhost                                               2
neighbourhood_cleansed                                         16
latitude                                                    17285
longitude                                                   16114
property_type                                                  83
room_type                                                       4
accommodates                                                   16
bathrooms                                                      36
bathrooms_text                                                 58
bedrooms                                                       24
beds                                                           31
amenities                                                   24446
price                                                        4118
minimum_nights                                                 71
maximum_nights                                                199
minimum_minimum_nights                                         76
maximum_minimum_nights                                         75
minimum_maximum_nights                                        162
maximum_maximum_nights                                        163
minimum_nights_avg_ntm                                        212
maximum_nights_avg_ntm                                        536
availability_30                                                31
availability_60                                                61
availability_90                                                91
availability_365                                              366
review_scores_location                                        136
review_scores_value                                           150
instant_bookable                                                2
calculated_host_listings_count_entire_homes                    57
calculated_host_listings_count_private_rooms                   33
calculated_host_listings_count_shared_rooms                     9

In [ ]:
import pandas as pd
import numpy as np

# --- Columnas Numéricas ---
# Seleccionamos las columnas que son de tipo numérico (incluye enteros y flotantes)
columnas_numericas = df_DIC.select_dtypes(include=np.number).columns.tolist()

# --- Columnas Categóricas ---
# 'category', que son los tipos más comunes para datos categóricos.
columnas_categoricas = df_DIC.select_dtypes(include=['object', 'category']).columns.tolist()

print("✅ Columnas Numéricas:")
print(columnas_numericas)

print("\n-------------------------\n")

print("✅ Columnas Categóricas:")
print(columnas_categoricas)

✅ Columnas Numéricas:
['latitude', 'longitude', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'number_of_reviews', 'review_scores_rating', 'review_scores_location', 'review_scores_value', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms']

-------------------------

✅ Columnas Categóricas:
['host_since', 'host_location', 'host_is_superhost', 'neighbourhood_cleansed', 'property_type', 'room_type', 'bathrooms_text', 'amenities', 'price', 'instant_bookable']

In [ ]:

# Sobrescribir la columna con solo el año
df_DIC["host_since"] = pd.to_datetime(df_DIC["host_since"], format="%Y-%m-%d", errors="coerce")\
                       .dt.year.astype("Int64")
df_DIC["host_since"] = 2025 - df_DIC["host_since"]

In [ ]:
df_DIC["host_since"]

0        15
1        15
2        14
3        15
4        14
         ..
26276     5
26277     2
26278     6
26279    10
26280     5
Name: host_since, Length: 26281, dtype: Int64

In [ ]:
df_DIC['host_is_superhost'] = (df_DIC['host_is_superhost'] == 't').astype(int)

In [ ]:
df_DIC['instant_bookable'] = (df_DIC['instant_bookable'] == 't').astype(int)

In [ ]:
#Llimpieza de la columna de precios
df_DIC['price'] = df_DIC['price'].replace({'\$': '', ',': ''}, regex=True).astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipython-input-2236709188.py:2: SyntaxWarning: invalid escape sequence '\$'
  df_DIC['price'] = df_DIC['price'].replace({'\$': '', ',': ''}, regex=True).astype(float)

In [ ]:
# Extraer el número de la columna de texto (ejemplo simple)
df_DIC['bathrooms_text'] = df_DIC['bathrooms_text'].str.extract('(\d+\.?\d*)').astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipython-input-704646771.py:2: SyntaxWarning: invalid escape sequence '\d'
  df_DIC['bathrooms_text'] = df_DIC['bathrooms_text'].str.extract('(\d+\.?\d*)').astype(float)

In [ ]:
df_DIC['latitude'] = pd.to_numeric(df_DIC['latitude'], errors='coerce')
df_DIC['longitude'] = pd.to_numeric(df_DIC['longitude'], errors='coerce')

In [ ]:
import pandas as pd
import numpy as np

# --- Columnas Numéricas ---
# Seleccionamos las columnas que son de tipo numérico (incluye enteros y flotantes)
columnas_numericas = df_DIC.select_dtypes(include=np.number).columns.tolist()

# --- Columnas Categóricas ---

# 'category', que son los tipos más comunes para datos categóricos.
columnas_categoricas = df_DIC.select_dtypes(include=['object', 'category']).columns.tolist()

print("✅ Columnas Numéricas:")
print(columnas_numericas)

print("\n-------------------------\n")

print("✅ Columnas Categóricas:")
print(columnas_categoricas)

✅ Columnas Numéricas:
['host_since', 'host_is_superhost', 'latitude', 'longitude', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms', 'beds', 'price', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'number_of_reviews', 'review_scores_rating', 'review_scores_location', 'review_scores_value', 'instant_bookable', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms']

-------------------------

✅ Columnas Categóricas:
['host_location', 'neighbourhood_cleansed', 'property_type', 'room_type', 'amenities']

In [ ]:
unique_values_count = df_DIC.nunique()
unique_values_df_DIC = pd.DataFrame(unique_values_count, columns=['Unique Values Count'])
display(unique_values_df_DIC)

                                              Unique Values Count
host_since                                                     16
host_location                                                 408
host_is_superhost                                               2
neighbourhood_cleansed                                         16
latitude                                                    17285
longitude                                                   16114
property_type                                                  83
room_type                                                       4
accommodates                                                   16
bathrooms                                                      36
bathrooms_text                                                 36
bedrooms                                                       24
beds                                                           31
amenities                                                   24446
price                                                        4118
minimum_nights                                                 71
maximum_nights                                                199
minimum_minimum_nights                                         76
maximum_minimum_nights                                         75
minimum_maximum_nights                                        162
maximum_maximum_nights                                        163
minimum_nights_avg_ntm                                        212
maximum_nights_avg_ntm                                        536
availability_30                                                31
availability_60                                                61
availability_90                                                91
availability_365                                              366
number_of_reviews                                             552
review_scores_rating                                          143
review_scores_location                                        136
review_scores_value                                           150
instant_bookable                                                2
calculated_host_listings_count_entire_homes                    57
calculated_host_listings_count_private_rooms                   33
calculated_host_listings_count_shared_rooms                     9

In [ ]:
df_DIC

,host_since,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,...,availability_30,availability_60,availability_90,availability_365,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,2010,0,Cuajimalpa de Morelos,19.382830,-99.271780,Entire villa,Entire home/apt,2,1.0,1.0,...,28,58,88,363,NaN,NaN,0,1,0,0
1,2010,1,Cuauhtémoc,19.411620,-99.177940,Entire home,Entire home/apt,14,5.5,5.5,...,22,52,82,357,4.98,4.48,0,4,1,0
2,2011,1,Cuauhtémoc,19.411520,-99.168570,Entire rental unit,Entire home/apt,4,1.0,1.0,...,22,38,68,343,4.98,4.92,0,2,0,0
3,2010,1,Coyoacán,19.354480,-99.162170,Entire rental unit,Entire home/apt,2,1.0,1.0,...,2,2,10,285,4.96,4.92,0,2,1,0
4,2011,0,Coyoacán,19.354160,-99.164880,Private room,Private room,2,NaN,1.0,...,0,0,0,0,NaN,NaN,0,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26276,2020,0,Miguel Hidalgo,19.436998,-99.196733,Room in hotel,Private room,2,1.0,1.0,...,29,59,89,363,NaN,NaN,1,0,12,0
26277,2023,0,Cuauhtémoc,19.449230,-99.136170,Entire rental unit,Entire home/apt,3,1.0,1.0,...,30,60,90,365,NaN,NaN,1,1,0,0
26278,2019,0,Coyoacán,19.316820,-99.116781,Shared room in rental unit,Shared room,6,2.0,2.0,...,30,60,90,365,NaN,NaN,1,0,5,3
26279,2015,1,Miguel Hidalgo,19.400096,-99.172981,Entire rental unit,Entire home/apt,9,3.0,3.0,...,24,54,84,359,NaN,NaN,1,31,0,0
26280,2020,1,Cuauhtémoc,19.427799,-99.163842,Entire rental unit,Entire home/apt,2,1.0,1.0,...,26,56,86,325,NaN,NaN,1,182,1,0

In [ ]:
#Cuantifica valores faltantes por columna.
print('Missing values in data')
valores = df_DIC.isnull().sum()

Missing values in data

In [ ]:
valores

host_since                                         3
host_is_superhost                                  0
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                       3804
bathrooms_text                                   108
bedrooms                                         951
beds                                            3825
amenities                                          0
price                                           3815
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
review_scores_location                          3297
review_scores_value                             3297
instant_bookable                                   0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
dtype: int64

#SEP 2024

In [ ]:
listings_gz_SEP = pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /25 SEP 24/listings.csv.gz")

In [ ]:
calendar_gz_SEP =  pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /25 SEP 24/calendar.csv.gz")

In [ ]:
output_path = '/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/listings_gz_SEP.csv'

listings_gz_SEP.to_csv(output_path, index=False)

print(f"Attempting to save df_MAR to {output_path}")

Attempting to save df_MAR to /content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/listings_gz_SEP.csv

In [ ]:
listings_gz_SEP.to_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/listings_gz_SEP.csv", index=False)

In [ ]:
df_SEP = listings_gz_SEP.copy()

In [ ]:
df_SEP.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [ ]:
cols_to_drop = [
    "id",
    "listing_url",
    "scrape_id",
    "last_scraped",
    "name",
    "picture_url",
    "host_id",
    "host_url",
    "host_name",
    "host_response_time",
    "host_response_rate",
    "host_acceptance_rate",
    "host_thumbnail_url",
    "host_picture_url",
    "host_listings_count",
    "ost_listings_count",
    "host_total_listings_count",
    "host_verifications",
    "host_has_profile_pic",
    "host_identity_verified",
    "neighbourhood",
    "calendar_updated",
    "calendar_last_scraped",
   # "number_of_reviews",
    "number_of_reviews_ltm",
    "number_of_reviews_l30d",
    "availability_eoy",
    "number_of_reviews_ly",
    "first_review",
    "last_review",
   # "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "calculated_host_listings_count",
    "reviews_per_month",
    "neighbourhood_group_cleansed",
    "license",
    "description",
    "neighborhood_overview",
    "host_about",
    "host_neighbourhood",
    "source",
    "has_availability",
    'host_location', # Se agrego esta columna puesto que en la limpieza de sus valores nuelos me percate que solo toma el valor de ciudad de mexico, es decir, una columna de un solo valor.
    "bathrooms"


]

In [ ]:
df_SEP.drop(columns=cols_to_drop, inplace=True, errors="ignore")

In [ ]:
df_SEP

,host_since,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,...,availability_30,availability_60,availability_90,availability_365,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,2010-06-28,f,Cuajimalpa de Morelos,19.383820,-99.273340,Entire villa,Entire home/apt,2,1.0,1 bath,...,28,58,88,363,NaN,NaN,f,1,0,0
1,2010-08-09,t,Cuauhtémoc,19.411620,-99.177940,Entire home,Entire home/apt,14,NaN,5.5 baths,...,1,24,54,325,4.98,4.48,f,4,1,0
2,2011-01-04,t,Cuauhtémoc,19.411520,-99.168570,Entire rental unit,Entire home/apt,4,1.0,1 bath,...,3,20,50,325,4.98,4.91,f,2,0,0
3,2010-08-24,t,Coyoacán,19.356140,-99.163080,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,7,27,57,257,4.96,4.92,f,2,1,0
4,2011-04-27,t,Miguel Hidalgo,19.432110,-99.193270,Entire loft,Entire home/apt,2,1.5,1.5 baths,...,9,9,20,275,4.91,4.82,f,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26577,2016-04-16,t,Miguel Hidalgo,19.387329,-99.246731,Private room in guesthouse,Private room,4,1.0,1 private bath,...,30,60,90,365,NaN,NaN,t,14,23,0
26578,2024-08-13,f,Miguel Hidalgo,19.432687,-99.197736,Room in hotel,Private room,2,1.0,1 private bath,...,0,0,0,177,NaN,NaN,t,8,8,0
26579,2024-08-13,f,Miguel Hidalgo,19.432687,-99.197736,Room in hotel,Private room,2,1.0,1 private bath,...,0,0,0,177,NaN,NaN,t,8,8,0
26580,2024-08-13,f,Miguel Hidalgo,19.432687,-99.197736,Room in hotel,Private room,2,1.0,1 private bath,...,0,0,0,177,NaN,NaN,t,8,8,0
26581,2013-05-22,t,Miguel Hidalgo,19.443476,-99.201748,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,18,48,78,150,NaN,NaN,t,4,0,0

In [ ]:
#Cuantifica valores faltantes por columna.
print('Missing values in data')
valores = df_SEP.isnull().sum()

Missing values in data

In [ ]:
valores.head(50)

host_since                                         0
host_is_superhost                               1509
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                       2915
bathrooms_text                                    26
bedrooms                                         866
beds                                            2953
amenities                                          0
price                                           2927
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
review_scores_location                          3657
review_scores_value                             3657
instant_bookable                                   0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
dtype: int64

In [ ]:
unique_values_count = df_SEP.nunique()
unique_values_df = pd.DataFrame(unique_values_count, columns=['Unique Values Count'])
display(unique_values_df)

                                              Unique Values Count
host_since                                                   4050
host_location                                                 400
host_is_superhost                                               2
neighbourhood_cleansed                                         16
latitude                                                    17470
longitude                                                   16197
property_type                                                  92
room_type                                                       4
accommodates                                                   16
bathrooms                                                      38
bathrooms_text                                                 58
bedrooms                                                       24
beds                                                           31
amenities                                                   24698
price                                                        3511
minimum_nights                                                 76
maximum_nights                                                191
minimum_minimum_nights                                         79
maximum_minimum_nights                                         79
minimum_maximum_nights                                        153
maximum_maximum_nights                                        157
minimum_nights_avg_ntm                                        209
maximum_nights_avg_ntm                                        526
availability_30                                                31
availability_60                                                61
availability_90                                                91
availability_365                                              366
number_of_reviews                                             524
review_scores_rating                                          142
review_scores_location                                        136
review_scores_value                                           148
instant_bookable                                                2
calculated_host_listings_count_entire_homes                    53
calculated_host_listings_count_private_rooms                   31
calculated_host_listings_count_shared_rooms                    14

In [ ]:
import pandas as pd
import numpy as np

# --- Columnas Numéricas ---
# Seleccionamos las columnas que son de tipo numérico (incluye enteros y flotantes)
columnas_numericas = df_SEP.select_dtypes(include=np.number).columns.tolist()

# --- Columnas Categóricas ---
# 'category', que son los tipos más comunes para datos categóricos.
columnas_categoricas = df_SEP.select_dtypes(include=['object', 'category']).columns.tolist()

print("✅ Columnas Numéricas:")
print(columnas_numericas)

print("\n-------------------------\n")

print("✅ Columnas Categóricas:")
print(columnas_categoricas)

✅ Columnas Numéricas:
['latitude', 'longitude', 'accommodates', 'bedrooms', 'beds', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'number_of_reviews', 'review_scores_rating', 'review_scores_location', 'review_scores_value', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms']

-------------------------

✅ Columnas Categóricas:
['host_since', 'host_is_superhost', 'neighbourhood_cleansed', 'property_type', 'room_type', 'bathrooms_text', 'amenities', 'price', 'instant_bookable']

In [ ]:

# Sobrescribir la columna con solo el año
df_SEP["host_since"] = pd.to_datetime(df_SEP["host_since"], format="%Y-%m-%d", errors="coerce")\
                       .dt.year.astype("Int64")
df_SEP["host_since"] = 2025 - df_SEP["host_since"]

In [ ]:
df_SEP["host_since"]

0        15
1        15
2        14
3        15
4        14
         ..
26577     9
26578     1
26579     1
26580     1
26581    12
Name: host_since, Length: 26582, dtype: Int64

In [ ]:
df_SEP['host_is_superhost'] = (df_SEP['host_is_superhost'] == 't').astype(int)

In [ ]:
df_SEP['instant_bookable'] = (df_SEP['instant_bookable'] == 't').astype(int)

In [ ]:
#Llimpieza de la columna de precios
df_SEP['price'] = df_SEP['price'].replace({'\$': '', ',': ''}, regex=True).astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipython-input-3691941686.py:2: SyntaxWarning: invalid escape sequence '\$'
  df_SEP['price'] = df_SEP['price'].replace({'\$': '', ',': ''}, regex=True).astype(float)

In [ ]:
# Extraer el número de la columna de texto (ejemplo simple)
df_SEP['bathrooms_text'] = df_SEP['bathrooms_text'].str.extract('(\d+\.?\d*)').astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipython-input-2158994678.py:2: SyntaxWarning: invalid escape sequence '\d'
  df_SEP['bathrooms_text'] = df_SEP['bathrooms_text'].str.extract('(\d+\.?\d*)').astype(float)

In [ ]:
df_SEP['latitude'] = pd.to_numeric(df_SEP['latitude'], errors='coerce')
df_SEP['longitude'] = pd.to_numeric(df_SEP['longitude'], errors='coerce')

In [ ]:
import pandas as pd
import numpy as np

# --- Columnas Numéricas ---
# Seleccionamos las columnas que son de tipo numérico (incluye enteros y flotantes)
columnas_numericas = df_SEP.select_dtypes(include=np.number).columns.tolist()

# --- Columnas Categóricas ---

# 'category', que son los tipos más comunes para datos categóricos.
columnas_categoricas = df_SEP.select_dtypes(include=['object', 'category']).columns.tolist()

print("✅ Columnas Numéricas:")
print(columnas_numericas)

print("\n-------------------------\n")

print("✅ Columnas Categóricas:")
print(columnas_categoricas)

✅ Columnas Numéricas:
['host_since', 'host_is_superhost', 'latitude', 'longitude', 'accommodates', 'bathrooms_text', 'bedrooms', 'beds', 'price', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'number_of_reviews', 'review_scores_rating', 'review_scores_location', 'review_scores_value', 'instant_bookable', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms']

-------------------------

✅ Columnas Categóricas:
['neighbourhood_cleansed', 'property_type', 'room_type', 'amenities']

In [ ]:
unique_values_count = df_SEP.nunique()
unique_values_df_SEP = pd.DataFrame(unique_values_count, columns=['Unique Values Count'])
display(unique_values_df_SEP)

                                              Unique Values Count
host_since                                                     16
host_is_superhost                                               2
neighbourhood_cleansed                                         16
latitude                                                    17470
longitude                                                   16197
property_type                                                  92
room_type                                                       4
accommodates                                                   16
bathrooms                                                      38
bathrooms_text                                                 37
bedrooms                                                       24
beds                                                           31
amenities                                                   24698
price                                                        3511
minimum_nights                                                 76
maximum_nights                                                191
minimum_minimum_nights                                         79
maximum_minimum_nights                                         79
minimum_maximum_nights                                        153
maximum_maximum_nights                                        157
minimum_nights_avg_ntm                                        209
maximum_nights_avg_ntm                                        526
availability_30                                                31
availability_60                                                61
availability_90                                                91
availability_365                                              366
review_scores_location                                        136
review_scores_value                                           148
instant_bookable                                                2
calculated_host_listings_count_entire_homes                    53
calculated_host_listings_count_private_rooms                   31
calculated_host_listings_count_shared_rooms                    14

In [ ]:
df_SEP

,host_since,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,...,availability_30,availability_60,availability_90,availability_365,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,2010,0,Cuajimalpa de Morelos,19.383820,-99.273340,Entire villa,Entire home/apt,2,1.0,1.0,...,28,58,88,363,NaN,NaN,0,1,0,0
1,2010,1,Cuauhtémoc,19.411620,-99.177940,Entire home,Entire home/apt,14,NaN,5.5,...,1,24,54,325,4.98,4.48,0,4,1,0
2,2011,1,Cuauhtémoc,19.411520,-99.168570,Entire rental unit,Entire home/apt,4,1.0,1.0,...,3,20,50,325,4.98,4.91,0,2,0,0
3,2010,1,Coyoacán,19.356140,-99.163080,Entire rental unit,Entire home/apt,2,1.0,1.0,...,7,27,57,257,4.96,4.92,0,2,1,0
4,2011,1,Miguel Hidalgo,19.432110,-99.193270,Entire loft,Entire home/apt,2,1.5,1.5,...,9,9,20,275,4.91,4.82,0,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26577,2016,1,Miguel Hidalgo,19.387329,-99.246731,Private room in guesthouse,Private room,4,1.0,1.0,...,30,60,90,365,NaN,NaN,1,14,23,0
26578,2024,0,Miguel Hidalgo,19.432687,-99.197736,Room in hotel,Private room,2,1.0,1.0,...,0,0,0,177,NaN,NaN,1,8,8,0
26579,2024,0,Miguel Hidalgo,19.432687,-99.197736,Room in hotel,Private room,2,1.0,1.0,...,0,0,0,177,NaN,NaN,1,8,8,0
26580,2024,0,Miguel Hidalgo,19.432687,-99.197736,Room in hotel,Private room,2,1.0,1.0,...,0,0,0,177,NaN,NaN,1,8,8,0
26581,2013,1,Miguel Hidalgo,19.443476,-99.201748,Entire rental unit,Entire home/apt,2,1.0,1.0,...,18,48,78,150,NaN,NaN,1,4,0,0

In [ ]:
#Cuantifica valores faltantes por columna.
print('Missing values in data')
valores = df_SEP.isnull().sum()

Missing values in data

In [ ]:
valores

host_since                                         0
host_is_superhost                                  0
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                       2915
bathrooms_text                                    98
bedrooms                                         866
beds                                            2953
amenities                                          0
price                                           2927
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
review_scores_location                          3657
review_scores_value                             3657
instant_bookable                                   0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
dtype: int64

#UNION ARCHIVOS

In [ ]:
"estimated_occupancy_l365d"

In [ ]:
listings_gz_MAR.drop(columns=["estimated_occupancy_l365d"], inplace=True, errors="ignore")
listings_gz_JUN.drop(columns=["estimated_occupancy_l365d"], inplace=True, errors="ignore")

In [ ]:
UNION = pd.concat([listings_gz_SEP, listings_gz_DIC, listings_gz_MAR, listings_gz_JUN], ignore_index=True)

In [ ]:
UNION.drop_duplicates(inplace=True)

In [ ]:
UNION = pd.read_csv('/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/UNION.csv')

In [ ]:
print(UNION.columns.tolist())

['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name', 'description', 'neighborhood_overview', 'picture_url', 'host_id', 'host_url', 'host_name', 'host_since', 'host_location', 'host_about', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude', 'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review', 'last_review', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'reviews_per_month', 'availability_eoy', 'number_of_reviews_ly', 'estimated_revenue_l365d']

In [ ]:
listing_AirbnbMX = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/AirbnbMX/listings.csv")

/tmp/ipython-input-299357948.py:1: DtypeWarning: Columns (61,62) have mixed types. Specify dtype option on import or set low_memory=False.
  listing_AirbnbMX = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/AirbnbMX/listings.csv")

In [ ]:
listing_AirbnbMX

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,availability_eoy,number_of_reviews_ly,estimated_revenue_l365d
0,35797,https://www.airbnb.com/rooms/35797,20200620031232,2020-06-23,<NA>,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Centro comercial Santa Fe, parque interlomas y...",https://a0.muscache.com/im/pictures/201492/ef4...,153786,...,NaN,f,1,1,0,0,NaN,<NA>,<NA>,<NA>
1,56074,https://www.airbnb.com/rooms/56074,20200620031232,2020-06-26,<NA>,Great space in historical San Rafael,This great apartment is located in one of the ...,Very traditional neighborhood with all service...,https://a0.muscache.com/im/pictures/3005118/60...,265650,...,NaN,t,2,2,0,0,1.89,<NA>,<NA>,<NA>
2,61792,https://www.airbnb.com/rooms/61792,20200620031232,2020-06-20,<NA>,Spacious Clean Quiet room (own bath) in la Con...,"Located in La Condesa, one of the best neighbo...",You are going to be in one of the nicest neigh...,https://a0.muscache.com/im/pictures/45f23965-0...,299558,...,NaN,f,2,0,2,0,1.62,<NA>,<NA>,<NA>
3,70644,https://www.airbnb.com/rooms/70644,20200620031232,2020-06-21,<NA>,Beautiful light Studio Coyoacan- full equipped !,COYOACAN designer studio quiet & safe! well eq...,Coyoacan is a beautiful neighborhood famous fo...,https://a0.muscache.com/im/pictures/f397d2da-d...,212109,...,NaN,f,3,2,1,0,1.00,<NA>,<NA>,<NA>
4,107078,https://www.airbnb.com/rooms/107078,20200620031232,2020-06-21,<NA>,NEW DESIGNER LOFT,"Is the best ever place triple L Location, qua...","Is located in the best area of Mexico City, Po...",https://a0.muscache.com/im/pictures/bd64f86d-4...,540705,...,NaN,t,2,2,0,0,0.20,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21819,43856289,https://www.airbnb.com/rooms/43856289,20200620031232,2020-06-21,<NA>,Condesa Luxury Family Room w/private bathroom,Located in Condesa inside an old house recentl...,"The neighborhood, characterized by its art dec...",https://a0.muscache.com/im/pictures/e97929d2-7...,63979434,...,NaN,t,5,1,4,0,NaN,<NA>,<NA>,<NA>
21820,43856833,https://www.airbnb.com/rooms/43856833,20200620031232,2020-06-20,<NA>,"3 RECÁMARAS 2 BAÑOS, GYM, CÉNTRICO","El departamento está ubicado MUY CERCA de ""Pas...",La ubicación del apartamento es en mi opinión ...,https://a0.muscache.com/im/pictures/614a11a5-2...,35255741,...,NaN,t,7,7,0,0,NaN,<NA>,<NA>,<NA>
21821,43858230,https://www.airbnb.com/rooms/43858230,20200620031232,2020-06-23,<NA>,Departamento Galaxia San Angel,Departamento de 3 recamaras con 2 baños comple...,A 5 min de Televisa San Angel A 10 min del ITA...,https://a0.muscache.com/im/pictures/24ff0f24-5...,85020390,...,NaN,f,2,2,0,0,NaN,<NA>,<NA>,<NA>
21822,43858765,https://www.airbnb.com/rooms/43858765,20200620031232,2020-06-21,<NA>,"location savvy, stylish,comfortable renovated ...","Make yourself comfortable in this cozy, fully ...",Cuauhtémoc neighborhood is a classic Mexico Ci...,https://a0.muscache.com/im/pictures/8cf19581-f...,264767749,...,NaN,t,1,1,0,0,NaN,<NA>,<NA>,<NA>
21823,43859282,https://www.airbnb.com/rooms/43859282,20200620031232,2020-06-21,<NA>,Pebbles' Home,Bello depto ideal para extranjeros que vengan ...,A 5 mn de Polanco centros comerciales y av imp...,https://a0.muscache.com/im/pictures/87e3b4c6-a...,139156115,...,NaN,t,4,3,1,0,NaN,<NA>,<NA>,<NA>

In [ ]:
# --- Mantener solo las columnas especificadas en listing_AirbnbMX ---
# Asumo que ya tienes un DataFrame llamado listing_AirbnbMX

allowed_cols = [
    'id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name', 'description',
    'neighborhood_overview', 'picture_url', 'host_id', 'host_url', 'host_name',
    'host_since', 'host_location', 'host_about', 'host_response_time', 'host_response_rate',
    'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
    'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications',
    'host_has_profile_pic', 'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed',
    'neighbourhood_group_cleansed', 'latitude', 'longitude', 'property_type', 'room_type',
    'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
    'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights',
    'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm',
    'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability', 'availability_30',
    'availability_60', 'availability_90', 'availability_365', 'calendar_last_scraped',
    'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
    'last_review', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness',
    'review_scores_checkin', 'review_scores_communication', 'review_scores_location',
    'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count',
    'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms',
    'calculated_host_listings_count_shared_rooms', 'reviews_per_month', 'availability_eoy',
    'number_of_reviews_ly', 'estimated_revenue_l365d'
]

# Quitar duplicados y respetar el orden dado
allowed_cols = list(dict.fromkeys(allowed_cols))

# Columnas que sí existen en el DF (para evitar KeyError) respetando el orden de allowed_cols
cols_to_keep = [c for c in allowed_cols if c in listing_AirbnbMX.columns]

# Filtrar
listing_AirbnbMX = listing_AirbnbMX.loc[:, cols_to_keep].copy()

# (Opcional) Diagnóstico rápido:
missing_in_df = [c for c in allowed_cols if c not in listing_AirbnbMX.columns]
dropped_cols = sorted(set(listing_AirbnbMX.columns) ^ set(cols_to_keep))  # normalmente vacío tras el loc

print(f"Columnas conservadas: {len(cols_to_keep)}")
if missing_in_df:
    print("No se encontraron en el DataFrame (se omitieron sin error):", missing_in_df)

# (Opcional) Guardar a CSV
listing_AirbnbMX.to_csv('listing_AirbnbMX_filtrado.csv', index=False)

Columnas conservadas: 72
No se encontraron en el DataFrame (se omitieron sin error): ['source', 'bathrooms_text', 'number_of_reviews_l30d', 'availability_eoy', 'number_of_reviews_ly', 'estimated_revenue_l365d']

In [ ]:
import pandas as pd

# Columnas a crear con NA (excepto bathrooms_text)
to_add_na = [
    'source', 'number_of_reviews_l30d', 'availability_eoy',
    'number_of_reviews_ly', 'estimated_revenue_l365d'
]

for col in to_add_na:
    if col not in listing_AirbnbMX.columns:
        listing_AirbnbMX[col] = pd.NA

# bathrooms_text: copiar desde "bathrooms" si existe; si no, crear como NA
if 'bathrooms_text' not in listing_AirbnbMX.columns:
    if 'bathrooms' in listing_AirbnbMX.columns:
        listing_AirbnbMX['bathrooms_text'] = listing_AirbnbMX['bathrooms']
    else:
        listing_AirbnbMX['bathrooms_text'] = pd.NA
else:
    # Si ya existe, rellenar nulos con bathrooms cuando esté disponible
    if 'bathrooms' in listing_AirbnbMX.columns:
        listing_AirbnbMX['bathrooms_text'] = listing_AirbnbMX['bathrooms_text'].fillna(
            listing_AirbnbMX['bathrooms']
        )

# (Opcional) si definiste allowed_cols antes, reordenar columnas
try:
    cols_order = [c for c in allowed_cols if c in listing_AirbnbMX.columns]
    listing_AirbnbMX = listing_AirbnbMX.reindex(columns=cols_order)
except NameError:
    pass

# Chequeo rápido
created = [c for c in to_add_na + ['bathrooms_text'] if c in listing_AirbnbMX.columns]
print("Columnas agregadas o actualizadas:", created)
print(listing_AirbnbMX[created].isna().sum())

Columnas agregadas o actualizadas: ['source', 'number_of_reviews_l30d', 'availability_eoy', 'number_of_reviews_ly', 'estimated_revenue_l365d', 'bathrooms_text']
source                     21824
number_of_reviews_l30d     21824
availability_eoy           21824
number_of_reviews_ly       21824
estimated_revenue_l365d    21824
bathrooms_text                26
dtype: int64

In [ ]:
listing_AirbnbMX.to_csv('listing_AirbnbMX_78.csv', index=False) #segundo trimstre 2020

In [ ]:
#Se puede unir con UNION 78 columnas.
listings_2021 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2020-2021/listings 2021.csv")
#listings1 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Mexico city Airbnb/listings1.csv") ES EL MISMO

In [ ]:
import pandas as pd

In [ ]:
listings1_2021 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Mexico city Airbnb/listings1.csv")

listings_2023q1 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2023/listings/listings_q1.csv")
listings_2023q2 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2023/listings/listings_q2.csv")
listings_2023q3 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2023/listings/listings_q3.csv")
listings_2023q4 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2023/listings/listings_q4.csv")

In [ ]:
listing_dic_24 =  pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /27 DIC 24/listings.csv")
listing_sep_24 =  pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /25 SEP 24/listings.csv")
listing_mar_25 =  pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/listings.csv")
listing_jun_25 =  pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /25 JUN 2025/listings.csv")

In [ ]:
UNION_gz = pd.concat([listing_AirbnbMX, listings_2021, UNION], ignore_index=True)

/tmp/ipython-input-925250666.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  UNION_gz = pd.concat([listing_AirbnbMX, listings_2021, UNION], ignore_index=True)

In [ ]:
UNION_gz

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,availability_eoy,number_of_reviews_ly,estimated_revenue_l365d
0,35797,https://www.airbnb.com/rooms/35797,20200620031232,2020-06-23,NaN,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Centro comercial Santa Fe, parque interlomas y...",https://a0.muscache.com/im/pictures/201492/ef4...,153786,...,NaN,f,1,1,0,0,NaN,NaN,NaN,NaN
1,56074,https://www.airbnb.com/rooms/56074,20200620031232,2020-06-26,NaN,Great space in historical San Rafael,This great apartment is located in one of the ...,Very traditional neighborhood with all service...,https://a0.muscache.com/im/pictures/3005118/60...,265650,...,NaN,t,2,2,0,0,1.89,NaN,NaN,NaN
2,61792,https://www.airbnb.com/rooms/61792,20200620031232,2020-06-20,NaN,Spacious Clean Quiet room (own bath) in la Con...,"Located in La Condesa, one of the best neighbo...",You are going to be in one of the nicest neigh...,https://a0.muscache.com/im/pictures/45f23965-0...,299558,...,NaN,f,2,0,2,0,1.62,NaN,NaN,NaN
3,70644,https://www.airbnb.com/rooms/70644,20200620031232,2020-06-21,NaN,Beautiful light Studio Coyoacan- full equipped !,COYOACAN designer studio quiet & safe! well eq...,Coyoacan is a beautiful neighborhood famous fo...,https://a0.muscache.com/im/pictures/f397d2da-d...,212109,...,NaN,f,3,2,1,0,1.00,NaN,NaN,NaN
4,107078,https://www.airbnb.com/rooms/107078,20200620031232,2020-06-21,NaN,NEW DESIGNER LOFT,"Is the best ever place triple L Location, qua...","Is located in the best area of Mexico City, Po...",https://a0.muscache.com/im/pictures/bd64f86d-4...,540705,...,NaN,t,2,2,0,0,0.20,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147215,1450299137475327273,https://www.airbnb.com/rooms/1450299137475327273,20250625031918,2025-07-01,city scrape,Central 68 Arena CDMX Aduana Pantaco Ind Vallejo,New 60-meter luxury apartment with two spaciou...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,170416107,...,NaN,t,1,1,0,0,1.00,178.0,0.0,6480.0
147216,1450300528106131951,https://www.airbnb.com/rooms/1450300528106131951,20250625031918,2025-06-26,city scrape,CDMX | Business Class Flat,Experience elevated business travel in our bea...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,358250534,...,NaN,t,14,14,0,0,NaN,188.0,0.0,0.0
147217,1450345027980478127,https://www.airbnb.com/rooms/1450345027980478127,20250625031918,2025-07-01,city scrape,Corazón CDMX Roma norte/Reforma,"Apartment in the heart of Mexico City, 2 minut...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,594251711,...,NaN,f,6,3,3,0,NaN,183.0,0.0,0.0
147218,1450394952972090126,https://www.airbnb.com/rooms/1450394952972090126,20250625031918,2025-07-01,city scrape,Chic Loft + Lap Pool & Gym,Stay in a chic loft inside a restored historic...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,24161895,...,NaN,f,1,1,0,0,NaN,160.0,0.0,0.0
147219,1450438287340754798,https://www.airbnb.com/rooms/1450438287340754798,20250625031918,2025-07-01,city scrape,Stylish 3 BR & Terrace near Reforma,Enjoy a stylish stay in this spacious 3BR apar...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,703177347,...,NaN,f,1,1,0,0,NaN,184.0,0.0,0.0

In [ ]:
UNION_18C = pd.concat([listings1_2021, listings_2023q1, listings_2023q2, listings_2023q3, listings_2023q4, listing_dic_24, listing_sep_24, listing_mar_25, listing_jun_25], ignore_index=True)

In [ ]:
UNION_18C

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,14714,Private room c/ bathroom . Colonia Juarez.,57785,Diego,NaN,Cuauhtémoc,19.430350,-99.155110,Private room,478.0,2,0,NaN,NaN,2,327,NaN,NaN
1,22787,"Sunny suite w/ queen size bed, inside boutique...",87973,Diego,NaN,Cuauhtémoc,19.440760,-99.163240,Private room,1969.0,1,57,2019-05-27,0.52,9,355,NaN,NaN
2,33681,Couple of Rooms,145672,Edubiel,NaN,Tlalpan,19.272150,-99.218480,Private room,1740.0,1,0,NaN,NaN,1,365,NaN,NaN
3,35797,Villa Dante,153786,Dici,NaN,Cuajimalpa de Morelos,19.383990,-99.273350,Entire home/apt,3823.0,1,0,NaN,NaN,2,363,NaN,NaN
4,44616,CONDESA HAUS B&B,196253,Condesa Haus Bed & Breakfast CDMX,NaN,Cuauhtémoc,19.410060,-99.176450,Private room,1893.0,1,39,2019-05-02,0.42,10,334,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227083,1450299137475327273,Central 68 Arena CDMX Aduana Pantaco Ind Vallejo,170416107,Vicente,NaN,Azcapotzalco,19.490670,-99.174150,Entire home/apt,1080.0,1,1,2025-06-29,1.00,1,359,1.0,NaN
227084,1450300528106131951,CDMX | Business Class Flat,358250534,Inperio,NaN,Benito Juárez,19.391438,-99.181881,Entire home/apt,982.0,1,0,NaN,NaN,14,364,0.0,NaN
227085,1450345027980478127,Corazón CDMX Roma norte/Reforma,594251711,Guadalupe,NaN,Cuauhtémoc,19.419767,-99.175294,Entire home/apt,1612.0,1,0,NaN,NaN,6,364,0.0,NaN
227086,1450394952972090126,Chic Loft + Lap Pool & Gym,24161895,Alexis,NaN,Cuauhtémoc,19.441713,-99.161810,Entire home/apt,627.0,2,0,NaN,NaN,1,341,0.0,NaN
227087,1450438287340754798,Stylish 3 BR & Terrace near Reforma,703177347,Priscilla,NaN,Miguel Hidalgo,19.427570,-99.175410,Entire home/apt,3070.0,3,0,NaN,NaN,1,270,0.0,NaN

In [ ]:
UNION_18C.to_csv('UNION_18C.csv', index=False)

In [ ]:
UNION_gz

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,availability_eoy,number_of_reviews_ly,estimated_revenue_l365d
0,35797,https://www.airbnb.com/rooms/35797,20200620031232,2020-06-23,NaN,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Centro comercial Santa Fe, parque interlomas y...",https://a0.muscache.com/im/pictures/201492/ef4...,153786,...,NaN,f,1,1,0,0,NaN,NaN,NaN,NaN
1,56074,https://www.airbnb.com/rooms/56074,20200620031232,2020-06-26,NaN,Great space in historical San Rafael,This great apartment is located in one of the ...,Very traditional neighborhood with all service...,https://a0.muscache.com/im/pictures/3005118/60...,265650,...,NaN,t,2,2,0,0,1.89,NaN,NaN,NaN
2,61792,https://www.airbnb.com/rooms/61792,20200620031232,2020-06-20,NaN,Spacious Clean Quiet room (own bath) in la Con...,"Located in La Condesa, one of the best neighbo...",You are going to be in one of the nicest neigh...,https://a0.muscache.com/im/pictures/45f23965-0...,299558,...,NaN,f,2,0,2,0,1.62,NaN,NaN,NaN
3,70644,https://www.airbnb.com/rooms/70644,20200620031232,2020-06-21,NaN,Beautiful light Studio Coyoacan- full equipped !,COYOACAN designer studio quiet & safe! well eq...,Coyoacan is a beautiful neighborhood famous fo...,https://a0.muscache.com/im/pictures/f397d2da-d...,212109,...,NaN,f,3,2,1,0,1.00,NaN,NaN,NaN
4,107078,https://www.airbnb.com/rooms/107078,20200620031232,2020-06-21,NaN,NEW DESIGNER LOFT,"Is the best ever place triple L Location, qua...","Is located in the best area of Mexico City, Po...",https://a0.muscache.com/im/pictures/bd64f86d-4...,540705,...,NaN,t,2,2,0,0,0.20,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147215,1450299137475327273,https://www.airbnb.com/rooms/1450299137475327273,20250625031918,2025-07-01,city scrape,Central 68 Arena CDMX Aduana Pantaco Ind Vallejo,New 60-meter luxury apartment with two spaciou...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,170416107,...,NaN,t,1,1,0,0,1.00,178.0,0.0,6480.0
147216,1450300528106131951,https://www.airbnb.com/rooms/1450300528106131951,20250625031918,2025-06-26,city scrape,CDMX | Business Class Flat,Experience elevated business travel in our bea...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,358250534,...,NaN,t,14,14,0,0,NaN,188.0,0.0,0.0
147217,1450345027980478127,https://www.airbnb.com/rooms/1450345027980478127,20250625031918,2025-07-01,city scrape,Corazón CDMX Roma norte/Reforma,"Apartment in the heart of Mexico City, 2 minut...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,594251711,...,NaN,f,6,3,3,0,NaN,183.0,0.0,0.0
147218,1450394952972090126,https://www.airbnb.com/rooms/1450394952972090126,20250625031918,2025-07-01,city scrape,Chic Loft + Lap Pool & Gym,Stay in a chic loft inside a restored historic...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,24161895,...,NaN,f,1,1,0,0,NaN,160.0,0.0,0.0
147219,1450438287340754798,https://www.airbnb.com/rooms/1450438287340754798,20250625031918,2025-07-01,city scrape,Stylish 3 BR & Terrace near Reforma,Enjoy a stylish stay in this spacious 3BR apar...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,703177347,...,NaN,f,1,1,0,0,NaN,184.0,0.0,0.0

In [ ]:
UNION_gz.to_csv('UNION_GZ.csv', index=False)

In [ ]:
listings_2023q1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24224 entries, 0 to 24223
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              24224 non-null  int64
 1   name                            24223 non-null  object
 2   host_id                         24224 non-null  int64
 3   host_name                       24224 non-null  object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   24224 non-null  object
 6   latitude                        24224 non-null  float64
 7   longitude                       24224 non-null  float64
 8   room_type                       24224 non-null  object
 9   price                           24224 non-null  int64
 10  minimum_nights                  24224 non-null  int64
 11  number_of_reviews               24224 non-null  int64
 12  last_review                     20628 non-null  object
 13  reviews_per_month               20628 non-null  float64
 14  calculated_host_listings_count  24224 non-null  int64
 15  availability_365                24224 non-null  int64
 16  number_of_reviews_ltm           24224 non-null  int64
 17  license                         0 non-null      float64
dtypes: float64(5), int64(8), object(5)
memory usage: 3.3+ MB

In [ ]:
listing_dic_24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26281 entries, 0 to 26280
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              26281 non-null  int64
 1   name                            26281 non-null  object
 2   host_id                         26281 non-null  int64
 3   host_name                       26278 non-null  object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   26281 non-null  object
 6   latitude                        26281 non-null  float64
 7   longitude                       26281 non-null  float64
 8   room_type                       26281 non-null  object
 9   price                           22466 non-null  float64
 10  minimum_nights                  26281 non-null  int64
 11  number_of_reviews               26281 non-null  int64
 12  last_review                     22985 non-null  object
 13  reviews_per_month               22985 non-null  float64
 14  calculated_host_listings_count  26281 non-null  int64
 15  availability_365                26281 non-null  int64
 16  number_of_reviews_ltm           26281 non-null  int64
 17  license                         0 non-null      float64
dtypes: float64(6), int64(7), object(5)
memory usage: 3.6+ MB

In [ ]:
AIRBNB_SERIE = UNION[["neighbourhood_cleansed", "price", "last_scraped", "property_type", "host_since"]]
display(AIRBNB_SERIE.head())

,neighbourhood_cleansed,price,last_scraped,property_type,host_since
0,Cuajimalpa de Morelos,"$3,865.00",2024-09-25,Entire villa,2010-06-28
1,Cuauhtémoc,NaN,2024-09-26,Entire home,2010-08-09
2,Cuauhtémoc,"$2,029.00",2024-09-26,Entire rental unit,2011-01-04
3,Coyoacán,"$1,140.00",2024-09-25,Entire rental unit,2010-08-24
4,Miguel Hidalgo,"$3,633.00",2024-09-25,Entire loft,2011-04-27

In [ ]:
# Remove '$' and ',' from the 'price' column and convert it to numeric
AIRBNB_SERIE['price'] = AIRBNB_SERIE['price'].replace({'\$': '', ',': ''}, regex=True).astype(float)

# Display the number of missing values in the 'price' column
print("Missing values in 'price' column:", AIRBNB_SERIE['price'].isnull().sum())

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipython-input-3940174507.py:2: SyntaxWarning: invalid escape sequence '\$'
  AIRBNB_SERIE['price'] = AIRBNB_SERIE['price'].replace({'\$': '', ',': ''}, regex=True).astype(float)

Missing values in 'price' column: 14015

/tmp/ipython-input-3940174507.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AIRBNB_SERIE['price'] = AIRBNB_SERIE['price'].replace({'\$': '', ',': ''}, regex=True).astype(float)

In [ ]:
# Calculate the mean price for each neighborhood
mean_price_by_neighborhood = AIRBNB_SERIE.groupby('neighbourhood_cleansed')['price'].transform('mean')

# Fill the missing values in the 'price' column with the calculated means
AIRBNB_SERIE['price'].fillna(mean_price_by_neighborhood, inplace=True)

# Display the number of missing values in the 'price' column after imputation
print("Missing values in 'price' column after imputation:", AIRBNB_SERIE['price'].isnull().sum())

Missing values in 'price' column after imputation: 0

/tmp/ipython-input-3959178797.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  AIRBNB_SERIE['price'].fillna(mean_price_by_neighborhood, inplace=True)
/tmp/ipython-input-3959178797.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AIRBNB_SERIE['price'].fillna(mean_price_by_neighborhood, inplace=True)

In [ ]:
# Define the desired output path and filename in the Colab environment
output_path = 'AIRBNB_SERIE.csv'

# Save the DataFrame to a CSV file
AIRBNB_SERIE.to_csv(output_path, index=False)

print(f"Successfully saved AIRBNB_SERIE to {output_path}")

Successfully saved AIRBNB_SERIE to AIRBNB_SERIE.csv

In [ ]:
UNION[UNION["last_scraped"] == 35797]

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,availability_eoy,number_of_reviews_ly,estimated_revenue_l365d
0,35797,https://www.airbnb.com/rooms/35797,20240925021012,2024-09-25,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Santa Fe Mall, Interloma Park and the Lion Des...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,NaN,f,1,1,0,0,NaN,NaN,NaN,NaN
26582,35797,https://www.airbnb.com/rooms/35797,20241227033128,2024-12-27,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Santa Fe Shopping Mall, Interlomas Park and th...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,NaN,f,1,1,0,0,NaN,NaN,NaN,NaN
52863,35797,https://www.airbnb.com/rooms/35797,20250319150644,2025-03-21,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Santa Fe Shopping Mall, Interlomas Park and th...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,NaN,f,1,1,0,0,NaN,284.0,0.0,0.0
78930,35797,https://www.airbnb.com/rooms/35797,20250625031918,2025-06-26,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Santa Fe Shopping Mall, Interlomas Park and th...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,NaN,f,1,1,0,0,NaN,188.0,0.0,0.0

In [ ]:


output_path = '/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/UNION.csv'

UNION.to_csv(output_path, index=False)

print(f"Successfully concatenated dataframes and saved to {output_path}")

Successfully concatenated dataframes and saved to /content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/UNION.csv

In [ ]:
BD_1C

,host_since,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,...,availability_90,availability_365,number_of_reviews,review_scores_rating,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,2010-06-28,f,Cuajimalpa de Morelos,19.383820,-99.273340,Entire villa,Entire home/apt,2,1.0,1 bath,...,88,363,0,NaN,NaN,NaN,f,1,0,0
1,2010-08-09,t,Cuauhtémoc,19.411620,-99.177940,Entire home,Entire home/apt,14,NaN,5.5 baths,...,54,325,64,4.58,4.98,4.48,f,4,1,0
2,2011-01-04,t,Cuauhtémoc,19.411520,-99.168570,Entire rental unit,Entire home/apt,4,1.0,1 bath,...,50,325,49,4.90,4.98,4.91,f,2,0,0
3,2010-08-24,t,Coyoacán,19.356140,-99.163080,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,57,257,127,4.91,4.96,4.92,f,2,1,0
4,2011-04-27,t,Miguel Hidalgo,19.432110,-99.193270,Entire loft,Entire home/apt,2,1.5,1.5 baths,...,20,275,11,4.91,4.91,4.82,f,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105326,2018-01-28,f,Azcapotzalco,19.490670,-99.174150,Entire condo,Entire home/apt,6,1.0,1 bath,...,84,359,1,5.00,4.00,5.00,t,1,0,0
105327,2020-07-24,NaN,Benito Juárez,19.391438,-99.181881,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,89,364,0,NaN,NaN,NaN,t,14,0,0
105328,2024-08-04,t,Cuauhtémoc,19.419767,-99.175294,Entire rental unit,Entire home/apt,4,1.0,1 bath,...,89,364,0,NaN,NaN,NaN,f,3,3,0
105329,2014-11-25,f,Cuauhtémoc,19.441713,-99.161810,Entire loft,Entire home/apt,2,1.0,1 bath,...,66,341,0,NaN,NaN,NaN,f,1,0,0
105330,2025-06-24,f,Miguel Hidalgo,19.427570,-99.175410,Entire rental unit,Entire home/apt,6,2.0,2 baths,...,90,270,0,NaN,NaN,NaN,f,1,0,0

#Resumen de valores faltantes.

In [ ]:
unique_values_df_SEP

                                              Unique Values Count
host_since                                                     16
host_location                                                 400
host_is_superhost                                               2
neighbourhood_cleansed                                         16
latitude                                                    17470
longitude                                                   16197
property_type                                                  92
room_type                                                       4
accommodates                                                   16
bathrooms                                                      38
bathrooms_text                                                 37
bedrooms                                                       24
beds                                                           31
amenities                                                   24698
price                                                        3511
minimum_nights                                                 76
maximum_nights                                                191
minimum_minimum_nights                                         79
maximum_minimum_nights                                         79
minimum_maximum_nights                                        153
maximum_maximum_nights                                        157
minimum_nights_avg_ntm                                        209
maximum_nights_avg_ntm                                        526
availability_30                                                31
availability_60                                                61
availability_90                                                91
availability_365                                              366
review_scores_location                                        136
review_scores_value                                           148
instant_bookable                                                2
calculated_host_listings_count_entire_homes                    53
calculated_host_listings_count_private_rooms                   31
calculated_host_listings_count_shared_rooms                    14

In [ ]:
unique_values_df_DIC

                                              Unique Values Count
host_since                                                     16
host_location                                                 408
host_is_superhost                                               2
neighbourhood_cleansed                                         16
latitude                                                    17285
longitude                                                   16114
property_type                                                  83
room_type                                                       4
accommodates                                                   16
bathrooms                                                      36
bathrooms_text                                                 36
bedrooms                                                       24
beds                                                           31
amenities                                                   24446
price                                                        4118
minimum_nights                                                 71
maximum_nights                                                199
minimum_minimum_nights                                         76
maximum_minimum_nights                                         75
minimum_maximum_nights                                        162
maximum_maximum_nights                                        163
minimum_nights_avg_ntm                                        212
maximum_nights_avg_ntm                                        536
availability_30                                                31
availability_60                                                61
availability_90                                                91
availability_365                                              366
review_scores_location                                        136
review_scores_value                                           150
instant_bookable                                                2
calculated_host_listings_count_entire_homes                    57
calculated_host_listings_count_private_rooms                   33
calculated_host_listings_count_shared_rooms                     9

In [ ]:
unique_values_df_MAR

                                              Unique Values Count
host_since                                                     17
host_is_superhost                                               2
neighbourhood_cleansed                                         16
latitude                                                    17167
longitude                                                   16091
property_type                                                  82
room_type                                                       4
accommodates                                                   16
bathrooms                                                      34
bathrooms_text                                                 34
bedrooms                                                       24
beds                                                           30
amenities                                                   24260
price                                                        4068
minimum_nights                                                 72
maximum_nights                                                201
minimum_minimum_nights                                         74
maximum_minimum_nights                                         75
minimum_maximum_nights                                        165
maximum_maximum_nights                                        170
minimum_nights_avg_ntm                                        205
maximum_nights_avg_ntm                                        554
availability_30                                                31
availability_60                                                61
availability_90                                                91
availability_365                                              366
review_scores_location                                        136
review_scores_value                                           150
instant_bookable                                                2
calculated_host_listings_count_entire_homes                    54
calculated_host_listings_count_private_rooms                   36
calculated_host_listings_count_shared_rooms                    10

In [ ]:
unique_values_df_JUN

                                              Unique Values Count
host_since                                                     17
host_is_superhost                                               2
neighbourhood_cleansed                                         16
latitude                                                    17536
longitude                                                   16455
property_type                                                  80
room_type                                                       4
accommodates                                                   16
bathrooms                                                      34
bathrooms_text                                                 34
bedrooms                                                       24
beds                                                           32
amenities                                                   25044
price                                                        3957
minimum_nights                                                 69
maximum_nights                                                192
minimum_minimum_nights                                         72
maximum_minimum_nights                                         75
minimum_maximum_nights                                        163
maximum_maximum_nights                                        167
minimum_nights_avg_ntm                                        204
maximum_nights_avg_ntm                                        605
availability_30                                                31
availability_60                                                61
availability_90                                                91
availability_365                                              366
review_scores_location                                        128
review_scores_value                                           155
instant_bookable                                                2
calculated_host_listings_count_entire_homes                    54
calculated_host_listings_count_private_rooms                   34
calculated_host_listings_count_shared_rooms                    13

In [ ]:
import pandas as pd

def take_counts(uv_df, label):
    s = uv_df['Unique Values Count'].copy()
    s.name = label
    return s

# 1) Tabla comparativa de # valores únicos por mes
counts = pd.concat([
    take_counts(unique_values_df_JUN, 'JUN'),
    take_counts(unique_values_df_MAR, 'MAR'),
    take_counts(unique_values_df_DIC, 'DIC'),
    take_counts(unique_values_df_SEP, 'SEP'),
], axis=1).sort_index()

# 2) Columnas que NO tienen el mismo conteo en todos los meses
diff_cols = counts[counts.nunique(axis=1) > 1].copy()

# (opcional) Métricas para ordenar/inspeccionar
diff_cols['min'] = diff_cols.min(axis=1)
diff_cols['max'] = diff_cols.max(axis=1)
diff_cols['spread'] = diff_cols['max'] - diff_cols['min']
diff_cols = diff_cols.sort_values('spread', ascending=False)

# 3) (opcional) Columnas idénticas en todos los meses
same_cols = counts[counts.nunique(axis=1) == 1].copy()

# 4) (opcional) Columnas que faltan en algún mes (NaN)
missing_in_some = counts.index[counts.isna().any(axis=1)]

# Muestra resultados
print("Columnas con distinto # de valores únicos:")
print(diff_cols)

Columnas con distinto # de valores únicos:
                                                  JUN      MAR    DIC    SEP  \
amenities                                     25044.0  24260.0  24446  24698
price                                          3957.0   4068.0   4118   3511
latitude                                      17536.0  17167.0  17285  17470
longitude                                     16455.0  16091.0  16114  16197
maximum_nights_avg_ntm                          605.0    554.0    536    526
maximum_maximum_nights                          167.0    170.0    163    157
minimum_maximum_nights                          163.0    165.0    162    153
property_type                                    80.0     82.0     83     92
maximum_nights                                  192.0    201.0    199    191
review_scores_location                          128.0    136.0    136    136
minimum_nights_avg_ntm                          204.0    205.0    212    209
host_location                                     NaN      NaN    408    400
review_scores_value                             155.0    150.0    150    148
minimum_nights                                   69.0     72.0     71     76
minimum_minimum_nights                           72.0     74.0     76     79
calculated_host_listings_count_shared_rooms      13.0     10.0      9     14
calculated_host_listings_count_private_rooms     34.0     36.0     33     31
bathrooms                                        34.0     34.0     36     38
calculated_host_listings_count_entire_homes      54.0     54.0     57     53
maximum_minimum_nights                           75.0     75.0     75     79
bathrooms_text                                   34.0     34.0     36     37
beds                                             32.0     30.0     31     31
host_since                                       17.0     17.0     16     16

                                                  min      max  spread
amenities                                     24260.0  25044.0   784.0
price                                          3511.0   4118.0   607.0
latitude                                      17167.0  17536.0   369.0
longitude                                     16091.0  16455.0   364.0
maximum_nights_avg_ntm                          526.0    605.0    79.0
maximum_maximum_nights                          157.0    170.0    13.0
minimum_maximum_nights                          153.0    165.0    12.0
property_type                                    80.0     92.0    12.0
maximum_nights                                  191.0    201.0    10.0
review_scores_location                          128.0    136.0     8.0
minimum_nights_avg_ntm                          204.0    212.0     8.0
host_location                                   400.0    408.0     8.0
review_scores_value                             148.0    155.0     7.0
minimum_nights                                   69.0     76.0     7.0
minimum_minimum_nights                           72.0     79.0     7.0
calculated_host_listings_count_shared_rooms       9.0     14.0     5.0
calculated_host_listings_count_private_rooms     31.0     36.0     5.0
bathrooms                                        34.0     38.0     4.0
calculated_host_listings_count_entire_homes      53.0     57.0     4.0
maximum_minimum_nights                           75.0     79.0     4.0
bathrooms_text                                   34.0     37.0     3.0
beds                                             30.0     32.0     2.0
host_since                                       16.0     17.0     1.0

#REVISON UNION

In [ ]:
import pandas as pd

In [ ]:
BASE = pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/BD_2C.csv")

/tmp/ipython-input-1936990759.py:1: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  BASE = pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/BD_2C.csv")

In [ ]:
BASE

,host_since,host_is_superhost,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,...,number_of_reviews,review_scores_rating,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,host_location,bathrooms
0,15.0,0,Cuajimalpa de Morelos,19.383820,-99.273340,Entire villa,Entire home/apt,2,1.0,1.0,...,0,NaN,NaN,NaN,0,1,0,0,NaN,NaN
1,15.0,1,Cuauhtémoc,19.411620,-99.177940,Entire home,Entire home/apt,14,5.5,5.0,...,64,4.58,4.98,4.48,0,4,1,0,NaN,NaN
2,14.0,1,Cuauhtémoc,19.411520,-99.168570,Entire rental unit,Entire home/apt,4,1.0,2.0,...,49,4.90,4.98,4.91,0,2,0,0,NaN,NaN
3,15.0,1,Coyoacán,19.356140,-99.163080,Entire rental unit,Entire home/apt,2,1.0,1.0,...,127,4.91,4.96,4.92,0,2,1,0,NaN,NaN
4,14.0,1,Miguel Hidalgo,19.432110,-99.193270,Entire loft,Entire home/apt,2,1.5,1.0,...,11,4.91,4.91,4.82,0,3,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105326,7.0,0,Azcapotzalco,19.490670,-99.174150,Entire condo,Entire home/apt,6,1.0,2.0,...,1,5.00,4.00,5.00,1,1,0,0,NaN,NaN
105327,5.0,0,Benito Juárez,19.391438,-99.181881,Entire rental unit,Entire home/apt,2,1.0,1.0,...,0,NaN,NaN,NaN,1,14,0,0,NaN,NaN
105328,1.0,1,Cuauhtémoc,19.419767,-99.175294,Entire rental unit,Entire home/apt,4,1.0,2.0,...,0,NaN,NaN,NaN,0,3,3,0,NaN,NaN
105329,11.0,0,Cuauhtémoc,19.441713,-99.161810,Entire loft,Entire home/apt,2,1.0,1.0,...,0,NaN,NaN,NaN,0,1,0,0,NaN,NaN
105330,0.0,0,Miguel Hidalgo,19.427570,-99.175410,Entire rental unit,Entire home/apt,6,2.0,3.0,...,0,NaN,NaN,NaN,0,1,0,0,NaN,NaN

## **Hasta aquí llega la primera limpieza sobre los datos a trabajar, en el siguiente notebook procederemos a analizar las variables que quedaron y su relevancia para el modelo y análisis descriptivo.**

In [ ]:
UNION = pd.read_csv('/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/UNION.csv', encoding="utf-8", on_bad_lines="skip")

In [ ]:
calendar_gz_MAR

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,287940,2025-03-20,f,$50.00,NaN,1.0,1125.0
1,287940,2025-03-21,f,$50.00,NaN,1.0,1125.0
2,287940,2025-03-22,f,$50.00,NaN,1.0,1125.0
3,287940,2025-03-23,f,$50.00,NaN,1.0,1125.0
4,287940,2025-03-24,f,$50.00,NaN,1.0,1125.0
...,...,...,...,...,...,...,...
9514712,1376984085881365289,2026-03-15,t,"$1,000.00",NaN,1.0,365.0
9514713,1376984085881365289,2026-03-16,t,"$1,000.00",NaN,1.0,365.0
9514714,1376984085881365289,2026-03-17,t,"$1,000.00",NaN,1.0,365.0
9514715,1376984085881365289,2026-03-18,t,"$1,000.00",NaN,1.0,365.0
9514716,1376984085881365289,2026-03-19,f,"$1,000.00",NaN,1.0,365.0

In [ ]:
CALENDAR = pd.concat([calendar_gz_SEP, calendar_gz_DIC, calendar_gz_MAR, calendar_gz_JUN], ignore_index=True)

In [ ]:
CALENDAR

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,1001517,2024-09-26,f,"$2,270.00",NaN,2.0,365.0
1,1001517,2024-09-27,f,"$2,270.00",NaN,2.0,365.0
2,1001517,2024-09-28,f,"$2,270.00",NaN,2.0,365.0
3,1001517,2024-09-29,f,"$2,270.00",NaN,2.0,365.0
4,1001517,2024-09-30,f,"$2,270.00",NaN,2.0,365.0
...,...,...,...,...,...,...,...
38446257,1446435219088525505,2026-06-27,f,NaN,NaN,1.0,365.0
38446258,1446435219088525505,2026-06-28,f,NaN,NaN,1.0,365.0
38446259,1446435219088525505,2026-06-29,f,NaN,NaN,1.0,365.0
38446260,1446435219088525505,2026-06-30,f,NaN,NaN,1.0,365.0
38446261,1446435219088525505,2026-07-01,f,NaN,NaN,1.0,365.0

In [ ]:
CALENDAR.drop_duplicates(inplace=True)

In [ ]:
CALENDAR.head(50)

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,1001517,2024-09-26,f,"$2,270.00",NaN,2.0,365.0
1,1001517,2024-09-27,f,"$2,270.00",NaN,2.0,365.0
2,1001517,2024-09-28,f,"$2,270.00",NaN,2.0,365.0
3,1001517,2024-09-29,f,"$2,270.00",NaN,2.0,365.0
4,1001517,2024-09-30,f,"$2,270.00",NaN,2.0,365.0
5,1001517,2024-10-01,f,"$2,270.00",NaN,2.0,365.0
6,1001517,2024-10-02,f,"$2,270.00",NaN,2.0,365.0
7,1001517,2024-10-03,f,"$2,270.00",NaN,2.0,365.0
8,1001517,2024-10-04,f,"$2,270.00",NaN,2.0,365.0
9,1001517,2024-10-05,f,"$2,270.00",NaN,2.0,365.0
10,1001517,2024-10-06,f,"$2,270.00",NaN,2.0,365.0
11,1001517,2024-10-07,f,"$2,270.00",NaN,2.0,365.0
12,1001517,2024-10-08,f,"$2,270.00",NaN,2.0,365.0
13,1001517,2024-10-09,f,"$2,270.00",NaN,2.0,365.0
14,1001517,2024-10-10,f,"$2,270.00",NaN,2.0,365.0
15,1001517,2024-10-11,f,"$2,270.00",NaN,2.0,365.0
16,1001517,2024-10-12,f,"$2,270.00",NaN,2.0,365.0
17,1001517,2024-10-13,f,"$2,270.00",NaN,2.0,365.0
18,1001517,2024-10-14,f,"$2,270.00",NaN,2.0,365.0
19,1001517,2024-10-15,f,"$2,270.00",NaN,2.0,365.0
20,1001517,2024-10-16,f,"$2,270.00",NaN,2.0,365.0
21,1001517,2024-10-17,f,"$2,270.00",NaN,2.0,365.0
22,1001517,2024-10-18,f,"$2,270.00",NaN,2.0,365.0
23,1001517,2024-10-19,f,"$2,270.00",NaN,2.0,365.0
24,1001517,2024-10-20,f,"$2,270.00",NaN,2.0,365.0
25,1001517,2024-10-21,f,"$2,270.00",NaN,2.0,365.0
26,1001517,2024-10-22,f,"$2,270.00",NaN,2.0,365.0
27,1001517,2024-10-23,f,"$2,270.00",NaN,2.0,365.0
28,1001517,2024-10-24,f,"$2,270.00",NaN,2.0,365.0
29,1001517,2024-10-25,f,"$2,270.00",NaN,2.0,365.0
30,1001517,2024-10-26,f,"$2,270.00",NaN,2.0,365.0
31,1001517,2024-10-27,f,"$2,270.00",NaN,2.0,365.0
32,1001517,2024-10-28,f,"$2,270.00",NaN,2.0,365.0
33,1001517,2024-10-29,f,"$2,270.00",NaN,2.0,365.0
34,1001517,2024-10-30,f,"$2,270.00",NaN,2.0,365.0
35,1001517,2024-10-31,f,"$2,270.00",NaN,2.0,365.0
36,1001517,2024-11-01,f,"$2,270.00",NaN,2.0,365.0
37,1001517,2024-11-02,f,"$2,270.00",NaN,2.0,365.0
38,1001517,2024-11-03,f,"$2,270.00",NaN,2.0,365.0
39,1001517,2024-11-04,f,"$2,270.00",NaN,2.0,365.0
40,1001517,2024-11-05,f,"$2,270.00",NaN,2.0,365.0
41,1001517,2024-11-06,f,"$2,270.00",NaN,2.0,365.0
42,1001517,2024-11-07,f,"$2,270.00",NaN,2.0,365.0
43,1001517,2024-11-08,f,"$2,270.00",NaN,2.0,365.0
44,1001517,2024-11-09,f,"$2,270.00",NaN,2.0,365.0
45,1001517,2024-11-10,f,"$2,270.00",NaN,2.0,365.0
46,1001517,2024-11-11,f,"$2,270.00",NaN,2.0,365.0
47,1001517,2024-11-12,f,"$2,270.00",NaN,2.0,365.0
48,1001517,2024-11-13,f,"$2,270.00",NaN,2.0,365.0
49,1001517,2024-11-14,f,"$2,270.00",NaN,2.0,365.0

In [ ]:
output_path = 'AIRBNB_SERIE_CALENDAR.csv'

# Save the DataFrame to a CSV file
CALENDAR.to_csv(output_path, index=False)

In [ ]:
UNION

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,availability_eoy,number_of_reviews_ly,estimated_revenue_l365d
0,35797,https://www.airbnb.com/rooms/35797,20240925021012,2024-09-25,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Santa Fe Mall, Interloma Park and the Lion Des...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,NaN,f,1,1,0,0,NaN,NaN,NaN,NaN
1,44616,https://www.airbnb.com/rooms/44616,20240925021012,2024-09-26,previous scrape,Condesa Haus,A new concept of hosting in mexico through a b...,NaN,https://a0.muscache.com/pictures/251410/ec75fe...,196253,...,NaN,f,8,4,1,0,0.41,NaN,NaN,NaN
2,67703,https://www.airbnb.com/rooms/67703,20240925021012,2024-09-26,city scrape,"2 bedroom apt. deco bldg, Condesa","Comfortably furnished, sunny, 2 bedroom apt., ...",NaN,https://a0.muscache.com/pictures/3281720/6f078...,334451,...,NaN,f,2,2,0,0,0.31,NaN,NaN,NaN
3,70644,https://www.airbnb.com/rooms/70644,20240925021012,2024-09-25,city scrape,Beautiful light Studio Coyoacan- full equipped !,COYOACAN designer studio quiet & safe! well eq...,Coyoacan is a beautiful neighborhood famous fo...,https://a0.muscache.com/pictures/f397d2da-d045...,212109,...,NaN,f,3,2,1,0,0.83,NaN,NaN,NaN
4,107078,https://www.airbnb.com/rooms/107078,20240925021012,2024-09-25,city scrape,NEW DESIGNER LOFT,Is the best ever place triple L <br />Location...,"Is located in the best area of Mexico City, Po...",https://a0.muscache.com/pictures/bd64f86d-4931...,540705,...,NaN,f,3,3,0,0,0.11,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105326,1450299137475327273,https://www.airbnb.com/rooms/1450299137475327273,20250625031918,2025-07-01,city scrape,Central 68 Arena CDMX Aduana Pantaco Ind Vallejo,New 60-meter luxury apartment with two spaciou...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,170416107,...,NaN,t,1,1,0,0,1.00,178.0,0.0,6480.0
105327,1450300528106131951,https://www.airbnb.com/rooms/1450300528106131951,20250625031918,2025-06-26,city scrape,CDMX | Business Class Flat,Experience elevated business travel in our bea...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,358250534,...,NaN,t,14,14,0,0,NaN,188.0,0.0,0.0
105328,1450345027980478127,https://www.airbnb.com/rooms/1450345027980478127,20250625031918,2025-07-01,city scrape,Corazón CDMX Roma norte/Reforma,"Apartment in the heart of Mexico City, 2 minut...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,594251711,...,NaN,f,6,3,3,0,NaN,183.0,0.0,0.0
105329,1450394952972090126,https://www.airbnb.com/rooms/1450394952972090126,20250625031918,2025-07-01,city scrape,Chic Loft + Lap Pool & Gym,Stay in a chic loft inside a restored historic...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,24161895,...,NaN,f,1,1,0,0,NaN,160.0,0.0,0.0
105330,1450438287340754798,https://www.airbnb.com/rooms/1450438287340754798,20250625031918,2025-07-01,city scrape,Stylish 3 BR & Terrace near Reforma,Enjoy a stylish stay in this spacious 3BR apar...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,703177347,...,NaN,f,1,1,0,0,NaN,184.0,0.0,0.0

In [ ]:
listings_MAR = pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/listings.csv")
listings_JUN = pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /25 JUN 2025/listings.csv")
listings_DIC = pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /27 DIC 24/listings.csv")
listings_SEP = pd.read_csv("/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /25 SEP 24/listings.csv")

In [ ]:
del listings_MAR
del listings_JUN
del listings_DIC
del listings_SEP

In [ ]:
del UNION2

In [ ]:

UNION = UNION[["id", "neighbourhood_cleansed", "room_type", "minimum_nights"]]
display(UNION.head())

       id neighbourhood_cleansed        room_type  minimum_nights
0   35797  Cuajimalpa de Morelos  Entire home/apt               1
1   44616             Cuauhtémoc  Entire home/apt               1
2   67703             Cuauhtémoc  Entire home/apt               2
3   70644               Coyoacán  Entire home/apt               5
4  107078         Miguel Hidalgo  Entire home/apt               1

In [ ]:
CALENDAR = pd.read_csv("/content/AIRBNB_SERIE_CALENDAR.csv")

/tmp/ipython-input-4134375703.py:1: DtypeWarning: Columns (3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  CALENDAR = pd.read_csv("/content/AIRBNB_SERIE_CALENDAR.csv")

In [ ]:
CALENDAR

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,1001517,2024-09-26,f,"$2,270.00",NaN,2.0,365.0
1,1001517,2024-09-27,f,"$2,270.00",NaN,2.0,365.0
2,1001517,2024-09-28,f,"$2,270.00",NaN,2.0,365.0
3,1001517,2024-09-29,f,"$2,270.00",NaN,2.0,365.0
4,1001517,2024-09-30,f,"$2,270.00",NaN,2.0,365.0
...,...,...,...,...,...,...,...
29964092,1446435219088525505,2026-06-27,f,NaN,NaN,1.0,365.0
29964093,1446435219088525505,2026-06-28,f,NaN,NaN,1.0,365.0
29964094,1446435219088525505,2026-06-29,f,NaN,NaN,1.0,365.0
29964095,1446435219088525505,2026-06-30,f,NaN,NaN,1.0,365.0
29964096,1446435219088525505,2026-07-01,f,NaN,NaN,1.0,365.0

In [ ]:
import pandas as pd
import numpy as np
import re

# ========= CONFIG =========
ROOM_TYPE_KEEP   = "Entire home/apt"
MAX_MIN_NIGHTS   = 30
# Rellena las rutas de tus 4 cortes (usa los nombres reales en tu Drive):
FILES = {
    "2024Q3": {"calendar": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /25 SEP 24/calendar.csv.gz", "listings": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /25 SEP 24/listings.csv.gz"},
    "2024Q4": {"calendar": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /27 DIC 24/calendar.csv.gz", "listings": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /27 DIC 24/listings.csv.gz"},
    "2025Q1": {"calendar": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/calendar.csv.gz", "listings": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/listings.csv.gz"},
    "2025Q2": {"calendar": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /25 JUN 2025/calendar.csv.gz", "listings": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /25 JUN 2025/listings.csv.gz"},
}

# ========= HELPERS =========
def to_num_price(s):
    return pd.to_numeric(pd.Series(s, dtype=str).str.replace(r"[^\d\.\-]", "", regex=True), errors="coerce")

def winsor_clip(s, p1=0.01, p99=0.99):
    lo, hi = s.quantile(p1), s.quantile(p99)
    return s.clip(lo, hi)

def load_listings_minimal(path):
    use_cols = ["id", "neighbourhood_cleansed", "room_type", "minimum_nights"]
    dtypes   = {"id": "int64", "neighbourhood_cleansed": "category", "room_type": "category"}
    df = pd.read_csv(path, usecols=use_cols, dtype=dtypes, low_memory=False)
    df["minimum_nights"] = pd.to_numeric(df["minimum_nights"], errors="coerce")
    return df

def process_quarter(cal_path, lis_path):
    # --- listings (chico) ---
    L = load_listings_minimal(lis_path)

    # --- calendar (sólo columnas necesarias) ---
    use_cols = ["listing_id", "date", "available", "price", "minimum_nights"]
    C = pd.read_csv(cal_path, usecols=use_cols, low_memory=False)
    C["listing_id"] = pd.to_numeric(C["listing_id"], errors="coerce")
    C["date"]       = pd.to_datetime(C["date"], errors="coerce")
    C["price"]      = to_num_price(C["price"])
    C = C[C["price"].notna() & (C["price"] > 0)]
    C["available"]  = C["available"].astype(str).str.lower()
    C = C.rename(columns={"minimum_nights": "cal_min_nights"})

    # --- merge y filtros ligeros ---
    df = C.merge(L, left_on="listing_id", right_on="id", how="left", validate="m:1")
    del C, L

    df["min_nights_final"] = df["cal_min_nights"].fillna(df["minimum_nights"])
    df = df[
        (df["room_type"] == ROOM_TYPE_KEEP) &
        (df["min_nights_final"].fillna(999) <= MAX_MIN_NIGHTS) &
        df["neighbourhood_cleansed"].notna()
    ].copy()

    # --- features mínimos para serie ---
    df["occ"] = (df["available"] == "f").astype("int8")
    df["log_price_w"] = winsor_clip(np.log(df["price"]), 0.01, 0.99)

    # periodos
    df["period_quarter"] = df["date"].dt.to_period("Q")
    # df["period_month"]   = df["date"].dt.to_period("M")     # <- mensual (descomenta si lo usarás)

    # --- agregación TRIMESTRAL (ligera) ---
    ts_q = (df.groupby(["neighbourhood_cleansed", "period_quarter"], observed=True)
              .agg(med_log_price=("log_price_w","median"),
                   med_price=("price","median"),
                   occ_proxy=("occ","mean"),
                   listings=("listing_id","nunique"),
                   obs=("listing_id","size"))
              .reset_index())
    ts_q["period_quarter_start"] = ts_q["period_quarter"].dt.to_timestamp(how="start")

    # --- (OPCIONAL) agregación MENSUAL ---
    # ts_m = (df.groupby(["neighbourhood_cleansed", "period_month"], observed=True)
    #           .agg(med_log_price=("log_price_w","median"),
    #                med_price=("price","median"),
    #                occ_proxy=("occ","mean"),
    #                listings=("listing_id","nunique"),
    #                obs=("listing_id","size"))
    #           .reset_index())
    # ts_m["period_month_start"] = ts_m["period_month"].dt.to_timestamp()

    return ts_q  # , ts_m

# ========= LOOP por trimestres (baja memoria) =========
res_quarter = []
# res_month   = []   # <- si usaras mensual

for k, paths in FILES.items():
    print(f"Procesando {k} ...")
    ts_q = process_quarter(paths["calendar"], paths["listings"])
    ts_q["cut"] = k
    res_quarter.append(ts_q)

    # ts_m = process_quarter(paths["calendar"], paths["listings"])[1]
    # ts_m["cut"] = k
    # res_month.append(ts_m)

# ========= CONCAT final (muy pequeño) =========
ts_quarter_all = pd.concat(res_quarter, ignore_index=True).sort_values(["neighbourhood_cleansed","period_quarter"])
print("Trimestral listo:", ts_quarter_all.shape)
ts_quarter_all.head()

# ts_month_all = pd.concat(res_month, ignore_index=True).sort_values(["neighbourhood_cleansed","period_month"])
# print("Mensual listo:", ts_month_all.shape)

# (Opcional) guardar
# ts_quarter_all.to_csv("airbnb_cdmx_quarter_panel.csv", index=False)
# ts_month_all.to_csv("airbnb_cdmx_month_panel.csv", index=False)

Procesando 2024Q3 ...
Procesando 2024Q4 ...
Procesando 2025Q1 ...
Procesando 2025Q2 ...
Trimestral listo: (240, 9)

,neighbourhood_cleansed,period_quarter,med_log_price,med_price,occ_proxy,listings,obs,period_quarter_start,cut
0,Azcapotzalco,2024Q3,6.551080,700.0,0.712264,214,1272,2024-07-01,2024Q3
1,Azcapotzalco,2024Q4,6.551794,700.5,0.283574,214,19688,2024-10-01,2024Q3
80,Azcapotzalco,2024Q4,6.552508,701.0,0.750700,218,1071,2024-10-01,2024Q4
2,Azcapotzalco,2025Q1,6.551794,700.5,0.168536,214,19260,2025-01-01,2024Q3
81,Azcapotzalco,2025Q1,6.551794,700.5,0.244444,218,19620,2025-01-01,2024Q4

In [ ]:
ts_quarter_all

,neighbourhood_cleansed,period_quarter,med_log_price,med_price,occ_proxy,listings,obs,period_quarter_start,cut
0,Azcapotzalco,2024Q3,6.551080,700.0,0.712264,214,1272,2024-07-01,2024Q3
1,Azcapotzalco,2024Q4,6.551794,700.5,0.283574,214,19688,2024-10-01,2024Q3
80,Azcapotzalco,2024Q4,6.552508,701.0,0.750700,218,1071,2024-10-01,2024Q4
2,Azcapotzalco,2025Q1,6.551794,700.5,0.168536,214,19260,2025-01-01,2024Q3
81,Azcapotzalco,2025Q1,6.551794,700.5,0.244444,218,19620,2025-01-01,2024Q4
...,...,...,...,...,...,...,...,...,...
158,Álvaro Obregón,2025Q3,6.903747,996.0,0.344573,548,50416,2025-07-01,2024Q4
237,Álvaro Obregón,2025Q3,6.897705,990.0,0.277536,525,48300,2025-07-01,2025Q1
159,Álvaro Obregón,2025Q4,6.904751,997.0,0.428559,548,47739,2025-10-01,2024Q4
238,Álvaro Obregón,2025Q4,6.897705,990.0,0.358903,525,48300,2025-10-01,2025Q1
239,Álvaro Obregón,2026Q1,6.897705,990.0,0.425246,525,41456,2026-01-01,2025Q1

In [ ]:
import pandas as pd
import numpy as np
import re

# ========= CONFIG =========
ROOM_TYPE_KEEP   = "Entire home/apt"
MAX_MIN_NIGHTS   = 30
# Rellena las rutas de tus 4 cortes (usa los nombres reales en tu Drive):
FILES = {
    "2024Q3": {"calendar": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /25 SEP 24/calendar.csv.gz", "listings": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /25 SEP 24/listings.csv.gz"},
    "2024Q4": {"calendar": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /27 DIC 24/calendar.csv.gz", "listings": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /27 DIC 24/listings.csv.gz"},
    "2025Q1": {"calendar": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/calendar.csv.gz", "listings": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/listings.csv.gz"},
    "2025Q2": {"calendar": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /25 JUN 2025/calendar.csv.gz", "listings": "/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /25 JUN 2025/listings.csv.gz"},
}

# ========= HELPERS =========
def to_num_price(s):
    return pd.to_numeric(pd.Series(s, dtype=str).str.replace(r"[^\d\.\-]", "", regex=True), errors="coerce")

def winsor_clip(s, p1=0.01, p99=0.99):
    lo, hi = s.quantile(p1), s.quantile(p99)
    return s.clip(lo, hi)

def load_listings_minimal(path):
    use_cols = ["id", "neighbourhood_cleansed", "room_type", "minimum_nights"]
    dtypes   = {"id": "int64", "neighbourhood_cleansed": "category", "room_type": "category"}
    df = pd.read_csv(path, usecols=use_cols, dtype=dtypes, low_memory=False)
    df["minimum_nights"] = pd.to_numeric(df["minimum_nights"], errors="coerce")
    return df

def process_quarter(cal_path, lis_path):
    # --- listings (chico) ---
    L = load_listings_minimal(lis_path)

    # --- calendar (sólo columnas necesarias) ---
    use_cols = ["listing_id", "date", "available", "price", "minimum_nights"]
    C = pd.read_csv(cal_path, usecols=use_cols, low_memory=False)
    C["listing_id"] = pd.to_numeric(C["listing_id"], errors="coerce")
    C["date"]       = pd.to_datetime(C["date"], errors="coerce")
    C["price"]      = to_num_price(C["price"])
    C = C[C["price"].notna() & (C["price"] > 0)]
    C["available"]  = C["available"].astype(str).str.lower()
    C = C.rename(columns={"minimum_nights": "cal_min_nights"})

    # --- merge y filtros ligeros ---
    df = C.merge(L, left_on="listing_id", right_on="id", how="left", validate="m:1")
    del C, L

    df["min_nights_final"] = df["cal_min_nights"].fillna(df["minimum_nights"])
    df = df[
        (df["room_type"] == ROOM_TYPE_KEEP) &
        (df["min_nights_final"].fillna(999) <= MAX_MIN_NIGHTS) &
        df["neighbourhood_cleansed"].notna()
    ].copy()

    # --- features mínimos para serie ---
    df["occ"] = (df["available"] == "f").astype("int8")
    df["log_price_w"] = winsor_clip(np.log(df["price"]), 0.01, 0.99)

    # periodos
    #df["period_quarter"] = df["date"].dt.to_period("Q")
    df["period_month"]   = df["date"].dt.to_period("M")     # <- mensual (descomenta si lo usarás)

    # --- agregación TRIMESTRAL (ligera) ---
    #ts_q = (df.groupby(["neighbourhood_cleansed", "period_quarter"], observed=True)
       #       .agg(med_log_price=("log_price_w","median"),
        #           med_price=("price","median"),
         #          occ_proxy=("occ","mean"),
          #         listings=("listing_id","nunique"),
           #        obs=("listing_id","size"))
            #  .reset_index())
    #ts_q["period_quarter_start"] = ts_q["period_quarter"].dt.to_timestamp(how="start")

    # --- (OPCIONAL) agregación MENSUAL ---
    ts_m = (df.groupby(["neighbourhood_cleansed", "period_month"], observed=True)
               .agg(med_log_price=("log_price_w","median"),
                    med_price=("price","median"),
                    occ_proxy=("occ","mean"),
                    listings=("listing_id","nunique"),
                    obs=("listing_id","size"))
               .reset_index())
    ts_m["period_month_start"] = ts_m["period_month"].dt.to_timestamp()

    return ts_m # , ts_q

# ========= LOOP por trimestres (baja memoria) =========
#res_quarter = []
res_month   = []   # <- si usaras mensual

for k, paths in FILES.items():
    print(f"Procesando {k} ...")
    #ts_q = process_quarter(paths["calendar"], paths["listings"])
    #ts_q["cut"] = k
    #res_quarter.append(ts_q)

    ts_m = process_quarter(paths["calendar"], paths["listings"]) # Corrected function call
    ts_m["cut"] = k
    res_month.append(ts_m)

# ========= CONCAT final (muy pequeño) =========
#ts_quarter_all = pd.concat(res_quarter, ignore_index=True).sort_values(["neighbourhood_cleansed","period_quarter"])
#print("Trimestral listo:", ts_quarter_all.shape)
#ts_quarter_all.head()

ts_month_all = pd.concat(res_month, ignore_index=True).sort_values(["neighbourhood_cleansed","period_month"])
print("Mensual listo:", ts_month_all.shape)

# (Opcional) guardar
# ts_quarter_all.to_csv("airbnb_cdmx_quarter_panel.csv", index=False)
# ts_month_all.to_csv("airbnb_cdmx_month_panel.csv", index=False)

Procesando 2024Q3 ...
Procesando 2024Q4 ...
Procesando 2025Q1 ...
Procesando 2025Q2 ...
Mensual listo: (624, 9)

In [ ]:
ts_month_all

,neighbourhood_cleansed,period_month,med_log_price,med_price,occ_proxy,listings,obs,period_month_start,cut
0,Azcapotzalco,2024-09,6.551080,700.0,0.712264,214,1272,2024-09-01,2024Q3
1,Azcapotzalco,2024-10,6.551794,700.5,0.416943,214,6634,2024-10-01,2024Q3
2,Azcapotzalco,2024-11,6.551794,700.5,0.276947,214,6420,2024-11-01,2024Q3
3,Azcapotzalco,2024-12,6.551794,700.5,0.156617,214,6634,2024-12-01,2024Q3
208,Azcapotzalco,2024-12,6.552508,701.0,0.750700,218,1071,2024-12-01,2024Q4
...,...,...,...,...,...,...,...,...,...
415,Álvaro Obregón,2025-12,6.904751,997.0,0.428761,548,14311,2025-12-01,2024Q4
620,Álvaro Obregón,2025-12,6.897705,990.0,0.389800,525,16275,2025-12-01,2025Q1
621,Álvaro Obregón,2026-01,6.897705,990.0,0.425868,525,16275,2026-01-01,2025Q1
622,Álvaro Obregón,2026-02,6.897705,990.0,0.424762,525,14700,2026-02-01,2025Q1
623,Álvaro Obregón,2026-03,6.897705,990.0,0.424959,525,10481,2026-03-01,2025Q1

In [ ]:
#ts_month_all
output_path = 'AIRBNB_SERIE_MENSUAL.csv'

# Save the DataFrame to a CSV file
ts_month_all.to_csv(output_path, index=False)

In [ ]:
#ts_quarter_all
output_path = 'AIRBNB_SERIE_TRIMESTRAL.csv'

# Save the DataFrame to a CSV file
ts_quarter_all.to_csv(output_path, index=False)