In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# importing necessary packages
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import missingno as msno
%matplotlib inline

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#Airbnb Mexico City - 2020-2021
listings_2021 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2020-2021/listings 2021.csv")
calendar_2021 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2020-2021/calendar 2021.csv")
reviews_2021 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2020-2021/reviews.csv")

#Airbnb Mexico City - 2023
listings_2023q1 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2023/listings/listings_q1.csv")
listings_2023q2 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2023/listings/listings_q2.csv")
listings_2023q3 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2023/listings/listings_q3.csv")
listings_2023q4 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2023/listings/listings_q4.csv")

reviews_2023q1 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2023/reviews/detailed_reviewsQ1.csv")
reviews_2023q2 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2023/reviews/detailed_reviewsQ2.csv")
reviews_2023q3 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2023/reviews/detailed_reviewsQ3.csv")
reviews_2023q4 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2023/reviews/detailed_reviewsQ4.csv")

#dictionari = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2023/data_dictionary.csv") #ñaaaaaaa

#Proyecto Github Guia ANALIZAR A PROFUNDIDAD.
listing = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Proyecto Github Guia/listings.csv")
meters = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Proyecto Github Guia/meters_per_neighbourhood.csv")
neighbourhoods = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Proyecto Github Guia/neighbourhoods.csv")
proces_aribnb = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Proyecto Github Guia/processed_aribnb_data.csv")
reviews = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Proyecto Github Guia/reviews.csv")

#AirBnB_Price_Prediction
listings_final =  pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/AirBnB_Price_Prediction/AirBnb-listings_final.csv")
DATA_FINAL = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/AirBnB_Price_Prediction/DATA_FINAL.csv")
amenities = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/AirBnB_Price_Prediction/amenities.csv")

#AirbnbMX
listing_AirbnbMX = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/AirbnbMX/listings.csv")

#Analisis-espacial-precios-Airbnb
listingANALISIS = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Analisis-espacial-precios-Airbnb/inside_abnb_clean_4.csv", encoding='latin1')

#DIC 2023
listings_2023 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/DIC 2023/listings.csv")

#Housing prices
housing_prices = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Housing prices/housing_data_CDMX.csv")
housing_prices2 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Housing prices/housing_data_CDMX_v2.csv")

#Mexico city Airbnb
listings1 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Mexico city Airbnb/listings1.csv")

#pf_airbnb
prueba = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/pf_airbnb/prueba.csv")

/tmp/ipython-input-164857083.py:32: DtypeWarning: Columns (61,62) have mixed types. Specify dtype option on import or set low_memory=False.
  listing_AirbnbMX = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/AirbnbMX/listings.csv")

###Airbnb Mexico City - 2020-2021

In [ ]:
listings_2021

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,35797,https://www.airbnb.com/rooms/35797,20210223160913,2021-02-23,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Centro comercial Santa Fe, parque interlomas y...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,https://www.airbnb.com/users/show/153786,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
1,44616,https://www.airbnb.com/rooms/44616,20210223160913,2021-02-24,CONDESA HAUS B&B,A new concept of hosting in mexico through a b...,NaN,https://a0.muscache.com/pictures/251410/ec75fe...,196253,https://www.airbnb.com/users/show/196253,...,10.0,10.0,9.0,NaN,f,10,2,1,0,0.43
2,56074,https://www.airbnb.com/rooms/56074,20210223160913,2021-02-24,Great space in historical San Rafael,This great apartment is located in one of the ...,Very traditional neighborhood with all service...,https://a0.muscache.com/pictures/3005118/60dac...,265650,https://www.airbnb.com/users/show/265650,...,10.0,10.0,10.0,NaN,t,2,2,0,0,0.46
3,58955,https://www.airbnb.com/rooms/58955,20210223160913,2021-02-24,Entire beautiful duplex in la Roma,"This beautiful apartment is centrally located,...",La Roma Norte is a beautiful bohemian and arts...,https://a0.muscache.com/pictures/83292812/1fe9...,282620,https://www.airbnb.com/users/show/282620,...,10.0,10.0,10.0,NaN,f,1,1,0,0,0.38
4,61792,https://www.airbnb.com/rooms/61792,20210223160913,2021-02-24,Spacious Clean Quiet room (own bath) in la Con...,"Located in La Condesa, one of the best neighbo...",You are going to be in one of the nicest neigh...,https://a0.muscache.com/pictures/45f23965-0194...,299558,https://www.airbnb.com/users/show/299558,...,10.0,10.0,10.0,NaN,f,2,0,2,0,1.29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20060,48287522,https://www.airbnb.com/rooms/48287522,20210223160913,2021-02-24,DEPARTAMENTO EN CENTRO HISTORICO CERCA DE CATE...,"Departamento en zona céntrica, a cinco cuadras...",NaN,https://a0.muscache.com/pictures/e350c018-f59e...,389716512,https://www.airbnb.com/users/show/389716512,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
20061,48287621,https://www.airbnb.com/rooms/48287621,20210223160913,2021-02-25,3 CULTURAS-Entire Apartment on the heart of Me...,<b>The space</b><br />Departamento ubicado muy...,NaN,https://a0.muscache.com/pictures/3e990cea-2ed4...,383788083,https://www.airbnb.com/users/show/383788083,...,NaN,NaN,NaN,NaN,t,2,1,0,1,NaN
20062,48287640,https://www.airbnb.com/rooms/48287640,20210223160913,2021-02-25,Residencial Danyval,"Cómodo y céntrico departamento, conectado con ...",A escasos metros del hospital la raza y plaza ...,https://a0.muscache.com/pictures/89ddfa59-a759...,103144327,https://www.airbnb.com/users/show/103144327,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
20063,48287826,https://www.airbnb.com/rooms/48287826,20210223160913,2021-02-24,Hostel in Roma Norte CDMX,NaN,NaN,https://a0.muscache.com/pictures/5ae81144-6423...,383788083,https://www.airbnb.com/users/show/383788083,...,NaN,NaN,NaN,NaN,t,2,1,0,1,NaN
20064,48287915,https://www.airbnb.com/rooms/48287915,20210223160913,2021-02-25,Privada con escritorio a un costado de Santa Fe,Habitación privada con lugar para estacionamie...,NaN,https://a0.muscache.com/pictures/88e8afaf-b1cb...,389720737,https://www.airbnb.com/users/show/389720737,...,NaN,NaN,NaN,NaN,t,1,0,1,0,NaN

###Airbnb Mexico City - 2023

In [ ]:
listings_2023q1

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,35797,Villa Dante,153786,Dici,NaN,Cuajimalpa de Morelos,19.382830,-99.271780,Entire home/apt,3658,1,0,NaN,NaN,1,363,0,NaN
1,696037,"3 Bedrooms, 2 blocks from Polanco - ALL RENOVA...",3531879,Gonzalo & Sandra,NaN,Miguel Hidalgo,19.441800,-99.184020,Entire home/apt,1469,24,39,2022-12-21,0.31,3,87,2,NaN
2,2056638,Amplio y luminoso loft en Coyoacán,10531228,Maria,NaN,Coyoacán,19.353530,-99.162990,Entire home/apt,1434,1,21,2018-06-24,0.19,3,324,0,NaN
3,44616,CONDESA HAUS B&B,196253,Condesa Haus Bed & Breakfast CDMX,NaN,Cuauhtémoc,19.411620,-99.177940,Entire home/apt,18000,1,64,2023-03-26,0.46,12,357,12,NaN
4,2072354,Coyoacan Historic Studio Apartment,16840050,Mónica,NaN,Coyoacán,19.353580,-99.169480,Entire home/apt,830,3,61,2022-11-04,0.54,2,346,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24219,856500768752084103,Explore Roma Condesa Amazing Apt,503585895,Ricardo,NaN,Cuauhtémoc,19.419472,-99.155539,Entire home/apt,1100,1,0,NaN,NaN,37,340,0,NaN
24220,856503637034407689,A 5 min de Televisa san ángel,143832783,Joselyne,NaN,Álvaro Obregón,19.340434,-99.205927,Entire home/apt,447,1,0,NaN,NaN,1,350,0,NaN
24221,856513330497669167,House in The Heart of North Rome,445250346,Jesus Manuel,NaN,Cuauhtémoc,19.419651,-99.164570,Entire home/apt,3240,3,0,NaN,NaN,4,365,0,NaN
24222,856517572363814533,3BR Apartment at Roma - Condesa,503585895,Ricardo,NaN,Cuauhtémoc,19.419472,-99.155539,Entire home/apt,1106,1,0,NaN,NaN,37,347,0,NaN
24223,856541228449710883,"Location , security, cozy, new",20440301,Hugo,NaN,Cuauhtémoc,19.453877,-99.155087,Entire home/apt,1029,1,0,NaN,NaN,3,364,0,NaN

Nota eliminar las columnas que no nos sirven y luego eliminar duplicados.
Si hay registros que variaron de precio, la pregunta es, porque?

In [ ]:
listings_2023q1[listings_2023q1["host_id"] == 153786]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,35797,Villa Dante,153786,Dici,NaN,Cuajimalpa de Morelos,19.38283,-99.27178,Entire home/apt,3658,1,0,NaN,NaN,1,363,0,NaN

In [ ]:
listings_2023q2[listings_2023q2["host_id"] == 153786]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,35797,Villa in Mexico City · 1 bedroom · 1 bed · 1 bath,153786,Dici,NaN,Cuajimalpa de Morelos,19.38283,-99.27178,Entire home/apt,3428,1,0,NaN,NaN,1,363,0,NaN

In [ ]:
listings_2023q3[listings_2023q3["host_id"] == 153786]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,35797,Villa in Mexico City · 1 bedroom · 1 bed · 1 bath,153786,Dici,NaN,Cuajimalpa de Morelos,19.38283,-99.27178,Entire home/apt,3437,1,0,NaN,NaN,1,363,0,NaN

In [ ]:
listings_2023q4[listings_2023q4["host_id"] == 153786]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,35797,Villa in Mexico City · 1 bedroom · 1 bed · 1 bath,153786,Dici,NaN,Cuajimalpa de Morelos,19.38283,-99.27178,Entire home/apt,3390.0,1,0,NaN,NaN,1,363,0,NaN

In [ ]:
listings_2023q2

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,35797,Villa in Mexico City · 1 bedroom · 1 bed · 1 bath,153786,Dici,NaN,Cuajimalpa de Morelos,19.382830,-99.271780,Entire home/apt,3428,1,0,NaN,NaN,1,363,0,NaN
1,44616,Home in Mexico City · ★4.58 · 5 bedrooms · 8 b...,196253,Condesa Haus Bed & Breakfast CDMX,NaN,Cuauhtémoc,19.411620,-99.177940,Entire home/apt,18000,1,64,2023-03-26,0.45,12,358,8,NaN
2,56074,Condo in Mexico City · ★4.87 · 1 bedroom · 1 b...,265650,Maris,NaN,Cuauhtémoc,19.439770,-99.156050,Entire home/apt,651,3,84,2023-01-21,0.56,1,235,12,NaN
3,58955,Loft in Mexico City · ★5.0 · 1 bedroom · 1 bed...,282620,Laura,NaN,Cuauhtémoc,19.421130,-99.159550,Entire home/apt,1779,3,48,2023-05-22,0.34,1,16,3,NaN
4,61792,Home in Mexico City · ★4.92 · 1 bedroom · 1 be...,299558,Roberto,NaN,Cuauhtémoc,19.410830,-99.180570,Private room,1026,2,62,2022-12-31,0.90,2,180,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25420,922615517882448708,Rental unit in Mexico City · ★New · 2 bedrooms...,16148871,Juan,NaN,Cuauhtémoc,19.419366,-99.169692,Entire home/apt,1776,1,0,NaN,NaN,111,358,0,NaN
25421,922629845859818252,Rental unit in Mexico City · ★New · 1 bedroom ...,16148871,Juan,NaN,Miguel Hidalgo,19.436320,-99.203620,Entire home/apt,2269,1,0,NaN,NaN,111,365,0,NaN
25422,922645196642484731,Rental unit in Mexico City · ★New · 1 bedroom ...,16148871,Juan,NaN,Miguel Hidalgo,19.437033,-99.202206,Entire home/apt,2269,1,0,NaN,NaN,111,365,0,NaN
25423,922654608908172867,Rental unit in Mexico City · ★New · 1 bedroom ...,16148871,Juan,NaN,Miguel Hidalgo,19.438205,-99.202108,Entire home/apt,2557,1,0,NaN,NaN,111,363,0,NaN
25424,922686334194891376,Rental unit in Mexico City · ★New · 2 bedrooms...,454330571,Lorenza,NaN,Cuauhtémoc,19.410884,-99.180126,Entire home/apt,1967,2,0,NaN,NaN,15,362,0,NaN

In [ ]:
listings_2023q3

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,35797,Villa in Mexico City · 1 bedroom · 1 bed · 1 bath,153786,Dici,NaN,Cuajimalpa de Morelos,19.382830,-99.271780,Entire home/apt,3437,1,0,NaN,NaN,1,363,0,NaN
1,44616,Home in Mexico City · ★4.58 · 5 bedrooms · 8 b...,196253,Condesa Haus Bed & Breakfast CDMX,NaN,Cuauhtémoc,19.411620,-99.177940,Entire home/apt,18000,1,64,2023-03-26,0.44,13,358,5,NaN
2,61792,Home in Mexico City · ★4.92 · 1 bedroom · 1 be...,299558,Roberto,NaN,Cuauhtémoc,19.410830,-99.180570,Private room,1031,2,63,2023-08-27,0.88,2,180,5,NaN
3,67703,Rental unit in Mexico City · ★4.89 · 2 bedroom...,334451,Nicholas,NaN,Cuauhtémoc,19.411520,-99.168570,Entire home/apt,1890,4,47,2023-01-01,0.33,2,307,4,NaN
4,70644,Rental unit in Mexico City · ★4.91 · 1 bedroom...,212109,Trisha,NaN,Coyoacán,19.354480,-99.162170,Entire home/apt,737,5,120,2023-09-16,0.85,3,158,8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26313,985673895001471605,Rental unit in Mexico City · ★New · 2 bedrooms...,200235979,Bamboo,NaN,Cuauhtémoc,19.409586,-99.166383,Entire home/apt,1525,1,0,NaN,NaN,5,269,0,NaN
26314,985676768542852342,Hotel in Mexico City · ★New · 1 bedroom · 1 be...,538290721,Invaluable,NaN,Cuauhtémoc,19.409086,-99.170103,Private room,1360,1,0,NaN,NaN,1,356,0,NaN
26315,985758830966947800,Rental unit in Mexico City · ★New · 3 bedrooms...,498096522,Virtual,NaN,Cuauhtémoc,19.424403,-99.162281,Entire home/apt,2400,1,0,NaN,NaN,62,352,0,NaN
26316,985775761856052521,Rental unit in Mexico City · ★New · 4 bedrooms...,498096522,Virtual,NaN,Miguel Hidalgo,19.439136,-99.201918,Entire home/apt,3401,1,0,NaN,NaN,62,355,0,NaN
26317,985780693129316227,Rental unit in Mexico City · ★New · 2 bedrooms...,498096522,Virtual,NaN,Cuauhtémoc,19.426129,-99.155407,Entire home/apt,1183,1,0,NaN,NaN,62,287,0,NaN

In [ ]:
reviews_2023q1

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,44616,706908,2011-11-09,634733,Lindsay,Forget staying in a hotel. Stay at condesa hau...
1,2056638,9623913,2014-01-03,6743067,Nora Carolina,"El sitio es precioso, está muy bien ubicado al..."
2,2056638,10085314,2014-01-29,267280,Andres,The host are amazing!!!!... The whole family i...
3,44616,2006160,2012-08-16,3087087,Samuel,"Fantastic location, great place, friendly host..."
4,44616,3174954,2012-12-28,3234920,Anna,I would highly recommend Condesa Haus for anyo...
...,...,...,...,...,...,...
886235,856097336186057624,858037363275058890,2023-03-29,507345923,Nil,"Un gran lugar, pese a que es pequeñito. Es tod..."
886236,851636712199463780,855878054198106096,2023-03-26,155265743,Francisco Romario,Excelente lugar para pasar unos días de descan...
886237,852054569324852029,855168835862691872,2023-03-25,384134271,Vanne,"cool, we love the place, Will come back soo. ❤️"
886238,853066443231508045,855877051505407080,2023-03-26,503774001,Angeles,"Cindy, siempre al pendiente de lo que se neces..."
886239,853138507789476424,855829489752557891,2023-03-26,173179751,Alejandra,Excelente ubicación y comunicación por parte d...

In [ ]:
reviews_2023q2

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,44616,706908,2011-11-09,634733,Lindsay,Forget staying in a hotel. Stay at condesa hau...
1,44616,2006160,2012-08-16,3087087,Samuel,"Fantastic location, great place, friendly host..."
2,44616,3174954,2012-12-28,3234920,Anna,I would highly recommend Condesa Haus for anyo...
3,44616,3271579,2013-01-04,2199822,Shelley And Pall,Great stay. Thanks. Highly recommend.
4,44616,3841065,2013-03-19,2423825,Leonardo,This was not a very good experience I am afrai...
...,...,...,...,...,...,...
932792,918149419011745088,921867321847052532,2023-06-25,171322279,Juan,"Un excelente sitio por su ubicación, comodidad..."
932793,918163961716062777,921802313184327478,2023-06-25,61874511,Wicho,Amazing apartment in Santa Fe. Everything was ...
932794,920191338598495125,922496427028485392,2023-06-26,76299273,Jennifer,"Lo recomiendo 💯 súper céntrico, lugar seguro ,..."
932795,920342548873897977,921851299915011423,2023-06-25,396105246,Alondra,"¡Excelente! Todo muy cómodo y privado, el trat..."
932796,921398526309780297,923221808008106219,2023-06-27,159410010,Roldan,"Jorge, siempre fué muy atento; su depa esta ge..."

In [ ]:
reviews_2023q3

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,44616,706908,2011-11-09,634733,Lindsay,Forget staying in a hotel. Stay at condesa hau...
1,44616,2006160,2012-08-16,3087087,Samuel,"Fantastic location, great place, friendly host..."
2,44616,3174954,2012-12-28,3234920,Anna,I would highly recommend Condesa Haus for anyo...
3,44616,3271579,2013-01-04,2199822,Shelley And Pall,Great stay. Thanks. Highly recommend.
4,44616,3841065,2013-03-19,2423825,Leonardo,This was not a very good experience I am afrai...
...,...,...,...,...,...,...
980904,979260326635095030,986335289962723993,2023-09-22,500316056,Yendy Marley,Buena atención
980905,981272038976363554,985619987952007421,2023-09-21,409027571,Cecilia Guadalupe,"Isabel tiene una calidad increíble, me hizo se..."
980906,981272038976363554,986378776401484925,2023-09-22,527838688,Fiorela,Excelente lugar. Isabel tiene un departamento ...
980907,981980135927839592,985609699508860773,2023-09-21,475824762,Jannet,"Verónica excelente anfitriona, el lugar tal co..."
980908,979296894865351923,983478741744919946,2023-09-18,283502069,Priscilla,Lucía es una persona maravillosa que me ayudo ...

In [ ]:
reviews_2023q4

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,44616,706908,2011-11-09,634733,Lindsay,Forget staying in a hotel. Stay at condesa hau...
1,44616,2006160,2012-08-16,3087087,Samuel,"Fantastic location, great place, friendly host..."
2,44616,3174954,2012-12-28,3234920,Anna,I would highly recommend Condesa Haus for anyo...
3,44616,3271579,2013-01-04,2199822,Shelley And Pall,Great stay. Thanks. Highly recommend.
4,607833,7570893,2013-09-24,8531917,Daniel,We had a great stay with Omar. We know DF ver...
...,...,...,...,...,...,...
1050468,1037222040791048239,1049362234901451865,2023-12-18,448952949,Karelia,Excelente ubicación y el llegar luce igual que...
1050469,1037222040791048239,1053041324336031888,2023-12-23,230095923,Mercedes,Todo estuvo excelente y los host siempre estuv...
1050470,1037590303647923918,1047197129700463792,2023-12-15,31748420,Javier,Recomiendo mucho quedarse con Emmanuel!
1050471,1037609176080808563,1038697679092723795,2023-12-03,18517563,Angie,"Pésimo host, nunca respondió los mensajes. No ..."
1050472,1037609176080808563,1043579403245937641,2023-12-10,380865335,Norma,El departamento es tal cual como aparece en la...

###Proyecto Github Guia

In [ ]:
listing #18 columnas SEP 2024 YA LO TENEMOS

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,35797,Villa Dante,153786,Dici,NaN,Cuajimalpa de Morelos,19.383820,-99.273340,Entire home/apt,3865.0,1,0,NaN,NaN,1,363,0,NaN
1,44616,Condesa Haus,196253,Fernando,NaN,Cuauhtémoc,19.411620,-99.177940,Entire home/apt,NaN,1,64,2023-03-26,0.41,8,325,0,NaN
2,67703,"2 bedroom apt. deco bldg, Condesa",334451,Nicholas,NaN,Cuauhtémoc,19.411520,-99.168570,Entire home/apt,2029.0,2,49,2024-05-05,0.31,2,325,4,NaN
3,70644,Beautiful light Studio Coyoacan- full equipped !,212109,Trisha,NaN,Coyoacán,19.356140,-99.163080,Entire home/apt,1140.0,5,127,2024-09-22,0.83,3,257,7,NaN
4,107078,NEW DESIGNER LOFT,540705,Andrea,NaN,Miguel Hidalgo,19.432110,-99.193270,Entire home/apt,3633.0,1,11,2023-08-16,0.11,3,275,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26577,1252159821531694005,Suite King | District Polanco,596009321,Luis Angel,NaN,Miguel Hidalgo,19.432687,-99.197736,Private room,2800.0,1,0,NaN,NaN,16,177,0,NaN
26578,1252185591721328995,Suite King | District Polanco,596009321,Luis Angel,NaN,Miguel Hidalgo,19.432687,-99.197736,Private room,2700.0,1,0,NaN,NaN,16,177,0,NaN
26579,1252218347521498445,Suite Queen | District Polanco,596009321,Luis Angel,NaN,Miguel Hidalgo,19.432687,-99.197736,Private room,2600.0,1,0,NaN,NaN,16,177,0,NaN
26580,1252229157495978163,"Pretty, well centered, amenities",6522855,Salvador,NaN,Miguel Hidalgo,19.443476,-99.201748,Entire home/apt,1353.0,1,0,NaN,NaN,4,150,0,NaN
26581,1252932787720304495,w* | Spectacular Loft w/ Perfect View in Roma ...,16148871,Juan,NaN,Cuauhtémoc,19.420141,-99.166998,Entire home/apt,1440.0,1,0,NaN,NaN,148,365,0,NaN

In [ ]:
meters

,neighbourhood,Low,Medium,High,Very_High,Luxury
0,Cuajimalpa de Morelos,20-30 m²,40-60 m²,80-120 m²,150-250 m²,300+ m²
1,Cuauhtémoc,25-35 m²,50-70 m²,90-150 m²,200-350 m²,400+ m²
2,Coyoacán,20-30 m²,40-60 m²,80-120 m²,150-250 m²,300+ m²
3,Miguel Hidalgo,30-40 m²,60-80 m²,100-200 m²,250-400 m²,500+ m²
4,Benito Juárez,25-35 m²,50-70 m²,90-150 m²,200-350 m²,400+ m²
5,Tlalpan,20-30 m²,40-60 m²,80-120 m²,150-250 m²,300+ m²
6,Venustiano Carranza,20-30 m²,40-60 m²,70-100 m²,120-200 m²,250+ m²
7,Gustavo A. Madero,15-25 m²,30-50 m²,60-90 m²,100-180 m²,200+ m²
8,Xochimilco,30-50 m²,60-100 m²,120-200 m²,250-400 m²,500+ m²
9,La Magdalena Contreras,25-35 m²,50-70 m²,90-150 m²,200-350 m²,400+ m²
10,Álvaro Obregón,25-35 m²,50-70 m²,90-150 m²,200-350 m²,400+ m²
11,Azcapotzalco,20-30 m²,40-60 m²,70-100 m²,120-200 m²,250+ m²
12,Iztacalco,20-30 m²,40-60 m²,70-100 m²,120-200 m²,250+ m²
13,Iztapalapa,15-25 m²,30-50 m²,60-90 m²,100-180 m²,200+ m²
14,Tláhuac,30-50 m²,60-100 m²,120-200 m²,250-400 m²,500+ m²
15,Milpa Alta,30-50 m²,60-100 m²,120-200 m²,250-400 m²,500+ m²

In [ ]:
neighbourhoods #naaaaaaaaa

    neighbourhood_group           neighbourhood
0                   NaN          Álvaro Obregón
1                   NaN            Azcapotzalco
2                   NaN           Benito Juárez
3                   NaN                Coyoacán
4                   NaN   Cuajimalpa de Morelos
5                   NaN              Cuauhtémoc
6                   NaN       Gustavo A. Madero
7                   NaN               Iztacalco
8                   NaN              Iztapalapa
9                   NaN  La Magdalena Contreras
10                  NaN          Miguel Hidalgo
11                  NaN              Milpa Alta
12                  NaN                 Tláhuac
13                  NaN                 Tlalpan
14                  NaN     Venustiano Carranza
15                  NaN              Xochimilco

In [ ]:
proces_aribnb

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,...,density_university,density_subway,density_restaurant,dis_to_tourist_point_per_neighborhood,cluster_geo,price_per_cluster,disponibility_cat,disponibility_per_review,min_nights_cat,average_measure
0,35797,Villa Dante,153786,Dici,Cuajimalpa de Morelos,19.383820,-99.273340,Entire home/apt,3865.0,1,...,0.000000,0.000000,0.000000,8.659602,15,1454.504348,high,0,shor_term,150-250 m²
1,67703,"2 bedroom apt. deco bldg, Condesa",334451,Nicholas,Cuauhtémoc,19.411520,-99.168570,Entire home/apt,2029.0,2,...,0.000000,0.000000,0.000000,3.895025,8,1775.377953,high,15925,shor_term,90-150 m²
2,70644,Beautiful light Studio Coyoacan- full equipped !,212109,Trisha,Coyoacán,19.356140,-99.163080,Entire home/apt,1140.0,5,...,1.029412,0.698529,0.220588,0.140610,11,1029.543619,high,32639,shor_term,40-60 m²
3,107078,NEW DESIGNER LOFT,540705,Andrea,Miguel Hidalgo,19.432110,-99.193270,Entire home/apt,3633.0,1,...,0.000000,0.000000,0.000000,1.778827,9,1883.109571,high,3025,shor_term,250-400 m²
4,165772,BEST 5 Bedroom HOUSE IN S. Miguel Chapultepec,790208,Francisco Carlos,Miguel Hidalgo,19.408260,-99.186590,Entire home/apt,3671.0,2,...,0.000000,0.299145,0.128205,1.458166,8,1775.377953,high,82110,shor_term,250-400 m²
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23635,1252159821531694005,Suite King | District Polanco,596009321,Luis Angel,Miguel Hidalgo,19.432687,-99.197736,Private room,2800.0,1,...,0.000000,0.000000,0.000000,2.167865,9,1883.109571,medium,0,shor_term,100-200 m²
23636,1252185591721328995,Suite King | District Polanco,596009321,Luis Angel,Miguel Hidalgo,19.432687,-99.197736,Private room,2700.0,1,...,0.000000,0.000000,0.000000,2.167865,9,1883.109571,medium,0,shor_term,100-200 m²
23637,1252218347521498445,Suite Queen | District Polanco,596009321,Luis Angel,Miguel Hidalgo,19.432687,-99.197736,Private room,2600.0,1,...,0.000000,0.000000,0.000000,2.167865,9,1883.109571,medium,0,shor_term,100-200 m²
23638,1252229157495978163,"Pretty, well centered, amenities",6522855,Salvador,Miguel Hidalgo,19.443476,-99.201748,Entire home/apt,1353.0,1,...,0.000000,0.000000,0.000000,3.315198,9,1883.109571,medium,0,shor_term,60-80 m²
23639,1252932787720304495,w* | Spectacular Loft w/ Perfect View in Roma ...,16148871,Juan,Cuauhtémoc,19.420141,-99.166998,Entire home/apt,1440.0,1,...,0.000000,0.000000,0.000000,3.181562,0,1596.396252,high,0,shor_term,50-70 m²

In [ ]:
reviews

                  listing_id        date
0                      44616  2011-11-09
1                      44616  2012-08-16
2                      44616  2012-12-28
3                      44616  2013-01-04
4                      44616  2013-03-19
...                      ...         ...
1208666  1248038152510103663  2024-09-22
1208667  1248050671878145686  2024-09-22
1208668  1248058667744084823  2024-09-23
1208669  1248147029043222680  2024-09-20
1208670  1248147029043222680  2024-09-22

[1208671 rows x 2 columns]

In [ ]:
calendar = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Proyecto Github Guia/calendar.csv")

/tmp/ipython-input-1473565371.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  calendar = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Proyecto Github Guia/calendar.csv")

In [ ]:
calendar

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,1001517,2024-09-26,f,"$2,270.00",NaN,2.0,365.0
1,1001517,2024-09-27,f,"$2,270.00",NaN,2.0,365.0
2,1001517,2024-09-28,f,"$2,270.00",NaN,2.0,365.0
3,1001517,2024-09-29,f,"$2,270.00",NaN,2.0,365.0
4,1001517,2024-09-30,f,"$2,270.00",NaN,2.0,365.0
...,...,...,...,...,...,...,...
9702527,1252229157495978163,2025-09-20,t,$70.00,NaN,1.0,365.0
9702528,1252229157495978163,2025-09-21,t,$70.00,NaN,1.0,365.0
9702529,1252229157495978163,2025-09-22,t,$70.00,NaN,1.0,365.0
9702530,1252229157495978163,2025-09-23,t,$70.00,NaN,1.0,365.0
9702531,1252229157495978163,2025-09-24,t,$70.00,NaN,1.0,365.0

###AirBnB_Price_Prediction

In [ ]:
listings_final #gz

,Consecutivo,id,listing_url,name,description,host_id,host_name,host_since,host_response_time,host_response_rate,...,number_of_reviews,review_scores_rating,cancellation_policy,neighbourhood_cleansed,state,zipcode,country_code,country,latitude,longitude
0,1,14714,https://www.airbnb.com/rooms/14714,Private room c/ bathroom . Colonia Juarez.,"Departamento ubicado a dos cuadras de Reforma,...",57785,Diego,11/26/2009,within a few hours,70%,...,0,NaN,strict_14_with_grace_period,Cuauhtémoc,Ciudad de México,6600.0,MX,Mexico,19.43035,-99.15511
1,2,22787,https://www.airbnb.com/rooms/22787,"Sunny suite w/ queen size bed, inside boutique...",This suite inside El Patio 77 - an eco-friendl...,87973,Diego,3/3/2010,within an hour,100%,...,57,98.0,strict_14_with_grace_period,Cuauhtémoc,Ciudad de México,6470.0,MX,Mexico,19.44076,-99.16324
2,3,33681,https://www.airbnb.com/rooms/33681,Couple of Rooms,You will get the best view of one of the bigge...,145672,Edubiel,6/16/2010,NaN,NaN,...,0,NaN,flexible,Tlalpan,Ciudad de México,14220.0,MX,Mexico,19.27215,-99.21848
3,4,35797,https://www.airbnb.com/rooms/35797,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...",153786,Dici,6/28/2010,NaN,NaN,...,0,NaN,flexible,Cuajimalpa de Morelos,Ciudad de México,NaN,MX,Mexico,19.38399,-99.27335
4,5,44616,https://www.airbnb.com/rooms/44616,CONDESA HAUS B&B,A new concept of hosting in mexico through a b...,196253,Condesa Haus Bed & Breakfast CDMX,8/9/2010,within a few hours,90%,...,39,89.0,strict_14_with_grace_period,Cuauhtémoc,Ciudad de México,6140.0,MX,Mexico,19.41006,-99.17645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19025,19026,35990295,https://www.airbnb.com/rooms/35990295,Departamento a 1km del aeropuerto Internaciona...,A 1 km del aeropuerto Internacional de la Ciud...,3283631,Ana,8/16/2012,within an hour,100%,...,0,NaN,flexible,Venustiano Carranza,Ciudad de México,NaN,MX,Mexico,19.43852,-99.08991
19026,19027,35996816,https://www.airbnb.com/rooms/35996816,HabitaciÃ³n para profesionistas o estudiantes,Amplia habitaciÃ³n con estudio integrado bien ...,128869391,MarÃ­a ConcepciÃ³n,5/4/2017,NaN,NaN,...,0,NaN,flexible,Tlalpan,Ciudad de México,6000.0,MX,Mexico,19.29351,-99.13170
19027,19028,35997871,https://www.airbnb.com/rooms/35997871,RecÃ¡mara priv. a 10 minutos del centro de Coy...,RecÃ¡mara con cuarto de baÃ±o privado a 10 min...,203369782,Andrea,7/18/2018,NaN,NaN,...,0,NaN,moderate,Coyoacán,Ciudad de México,4100.0,MX,Mexico,19.33495,-99.15413
19028,19029,36001346,https://www.airbnb.com/rooms/36001346,Cuarto privado cerca de Polanco,El departamento se encuentra en un residencial...,94436130,Samantha,9/10/2016,NaN,NaN,...,0,NaN,flexible,Miguel Hidalgo,Ciudad de México,NaN,MX,Mexico,19.45079,-99.18456
19029,19030,36001745,https://www.airbnb.com/rooms/36001745,Hermoso cuarto dentro de una casa mÃ¡gica,Con muchÃ­simo gusto comparto contigo un cuart...,29791582,Zavelia,3/22/2015,NaN,NaN,...,0,NaN,flexible,Miguel Hidalgo,Ciudad de México,11850.0,MX,Mexico,19.41475,-99.18706

In [ ]:
DATA_FINAL

,Consecutivo,id,neighbourhood_b,property_type,room_type,accommodates,bathrooms,bedrooms,beds,price,...,Long_term_stays_allowed,Pets allowed/cat(s)/dog(s)/pets live on this property/other pet(s),Private_entrance,Self_check-in,Smoking_allowed,"Step-free access/wheelchair accessible, or anything containing 'accessible'",Suitable_for_events,Unnamed: 27,total_paid_amount,host_days_active
0,1,14714,Juarez,Apartment,Private room,2,1.0,1,1,478,...,1,0,0,0,1,0,0,NaN,765,3497
1,2,22787,San Rafael,Hotel,Private room,2,1.0,1,1,1969,...,0,0,0,1,0,0,0,NaN,1969,3400
2,5,44616,Condesa,Hotel,Private room,16,9.0,9,1,1893,...,0,0,0,0,0,0,0,NaN,1893,3241
3,6,58955,Roma Norte,Apartment,Entire home/apt,2,1.5,1,1,1625,...,0,0,0,0,0,1,0,NaN,2103,3149
4,7,61792,Condesa,House,Private room,2,1.0,1,1,956,...,0,0,0,1,0,0,0,NaN,1243,3132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14454,19024,35986946,San Rafael,Apartment,Entire home/apt,3,1.5,1,1,1491,...,1,0,1,0,0,0,0,NaN,1491,1939
14455,19025,35987035,Anzures,Apartment,Private room,2,1.0,1,1,497,...,0,0,0,0,1,0,1,NaN,497,2036
14456,19027,35996816,Centro Historico,House,Private room,2,1.5,1,2,191,...,0,0,0,0,1,0,0,NaN,191,781
14457,19028,35997871,Coyoacan,House,Private room,2,1.5,1,1,382,...,0,0,0,0,0,0,0,NaN,382,341
14458,19030,36001745,San Miguel Chapultepec,House,Private room,2,1.0,1,1,497,...,0,0,0,0,0,0,0,NaN,497,1555

In [ ]:
amenities

,id,Internet,No_stairs_or_steps_to_enter,Heat_lamps,Full_kitchen,Keypad,Baby_bath,Shared_hot_tub,Paid_parking_off_premises,Dishes_and_silverware,...,Convection_oven,Dryer,First_aid_kit,Exercise_equipment,Toilet_paper,Dog(s),Pets_allowed,Pack_’n_Play/travel_crib,Ceiling_hoist,sum
0,14714,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,21
1,22787,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,17
2,33681,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,1,0,0,11
3,35797,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
4,44616,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19025,35990295,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
19026,35996816,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,11
19027,35997871,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,10
19028,36001346,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,11
19029,36001745,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7

##AirbnbMX

In [ ]:
listing_AirbnbMX #Revisar columnas.

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,35797,https://www.airbnb.com/rooms/35797,20200620031232,2020-06-23,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...",please go to (URL HIDDEN) and see the place a...,"Dentro de Villa un estudio de arte con futon, ...",none,"Centro comercial Santa Fe, parque interlomas y...",...,f,f,flexible,f,f,1,1,0,0,NaN
1,56074,https://www.airbnb.com/rooms/56074,20200620031232,2020-06-26,Great space in historical San Rafael,This great apartment is located in one of the ...,"Very nice furnished apartment, 7th floor, nice...",This great apartment is located in one of the ...,none,Very traditional neighborhood with all service...,...,t,f,moderate,f,f,2,2,0,0,1.89
2,61792,https://www.airbnb.com/rooms/61792,20200620031232,2020-06-20,Spacious Clean Quiet room (own bath) in la Con...,"Located in La Condesa, one of the best neighbo...","i am a graphic designer, i like simple things ...","Located in La Condesa, one of the best neighbo...",none,You are going to be in one of the nicest neigh...,...,f,f,moderate,f,f,2,0,2,0,1.62
3,70644,https://www.airbnb.com/rooms/70644,20200620031232,2020-06-21,Beautiful light Studio Coyoacan- full equipped !,COYOACAN designer studio quiet & safe! well eq...,"LIGHT, SPACIOUS, QUIET, FRIENDLY LOCATION. YOU...",COYOACAN designer studio quiet & safe! well eq...,none,Coyoacan is a beautiful neighborhood famous fo...,...,f,f,moderate,f,f,3,2,1,0,1.00
4,107078,https://www.airbnb.com/rooms/107078,20200620031232,2020-06-21,NEW DESIGNER LOFT,"Is the best ever place triple L Location, qua...",Es de la Mejores propiedades en la zona de Pol...,"Is the best ever place triple L Location, qua...",none,"Is located in the best area of Mexico City, Po...",...,t,f,strict_14_with_grace_period,f,f,2,2,0,0,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21819,43856289,https://www.airbnb.com/rooms/43856289,20200620031232,2020-06-21,Condesa Luxury Family Room w/private bathroom,Located in Condesa inside an old house recentl...,"We know these are difficult times, but Casa Ca...",Located in Condesa inside an old house recentl...,none,"The neighborhood, characterized by its art dec...",...,t,f,flexible,f,f,5,1,4,0,NaN
21820,43856833,https://www.airbnb.com/rooms/43856833,20200620031232,2020-06-20,"3 RECÁMARAS 2 BAÑOS, GYM, CÉNTRICO","El departamento está ubicado MUY CERCA de ""Pas...",------ Respuestas a Preguntas Frecuentes -----...,"El departamento está ubicado MUY CERCA de ""Pas...",none,La ubicación del apartamento es en mi opinión ...,...,t,f,strict_14_with_grace_period,f,f,7,7,0,0,NaN
21821,43858230,https://www.airbnb.com/rooms/43858230,20200620031232,2020-06-23,Departamento Galaxia San Angel,Departamento de 3 recamaras con 2 baños comple...,Departamento de 3 recamaras con 2 baños comple...,Departamento de 3 recamaras con 2 baños comple...,none,A 5 min de Televisa San Angel A 10 min del ITA...,...,f,f,strict_14_with_grace_period,f,f,2,2,0,0,NaN
21822,43858765,https://www.airbnb.com/rooms/43858765,20200620031232,2020-06-21,"location savvy, stylish,comfortable renovated ...","Make yourself comfortable in this cozy, fully ...",The building is an iconic example of Mexico's ...,"Make yourself comfortable in this cozy, fully ...",none,Cuauhtémoc neighborhood is a classic Mexico Ci...,...,t,f,flexible,f,f,1,1,0,0,NaN
21823,43859282,https://www.airbnb.com/rooms/43859282,20200620031232,2020-06-21,Pebbles' Home,Bello depto ideal para extranjeros que vengan ...,El departamento es completamente privado,Bello depto ideal para extranjeros que vengan ...,none,A 5 mn de Polanco centros comerciales y av imp...,...,t,f,flexible,f,f,4,3,1,0,NaN

In [ ]:
listing_AirbnbMX.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21824 entries, 0 to 21823
Columns: 106 entries, id to reviews_per_month
dtypes: float64(20), int64(23), object(63)
memory usage: 17.6+ MB

##Analisis-espacial-precios-Airbnb

In [4]:
listingANALISIS = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Analisis-espacial-precios-Airbnb/inside_abnb_clean_4.csv", encoding='latin1')

In [5]:
listingANALISIS

,id,index,host_is_superhost,host_total_listings_count,host_identity_verified,colonia,alcaldía,código_postal,latitude,longitude,...,pool,smoking_allowed,hot_tub,ad_duration,Entire home/apt,ln_price,nombre_x,pi_dist,nombre_y,metro_distance
0,58955,17,0,1,1,Roma Norte,Cuauhtémoc,6700,19.42292,-99.15775,...,0,0,0,90.646625,1,7.385851,Arena México,0.679148,Cuauhtémoc_1_2,0.452856
1,67703,44,1,4,1,Hipódromo,Cuauhtémoc,6100,19.41375,-99.17028,...,0,0,0,91.927966,1,7.496652,La Condesa,0.717691,Sevilla,0.906474
2,70644,80,1,4,1,Coyoacán,Coyoacán,4100,19.35601,-99.16167,...,0,0,0,89.003881,1,6.949856,Museo Frida Kahlo,0.125432,Coyoacán,1.110375
3,171109,104,1,2,0,Nápoles,Benito Juárez,NaN,19.39549,-99.17616,...,0,0,0,63.935604,0,5.652489,La Condesa,2.075343,San Pedro de Los Pinos,1.109405
4,180808,141,1,2,1,Juárez,Cuauhtémoc,6600,19.42428,-99.16843,...,0,0,0,86.671184,1,6.931472,Monumento a los Héroes de la Independencia,0.315716,Sevilla,0.358963
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6126,36422535,183795,1,7,0,Anzures,Miguel Hidalgo,11310,19.44461,-99.18204,...,0,0,0,0.295694,1,6.553933,Polanco,1.851774,San Joaquín,1.007846
6127,36448395,183836,0,1,0,Atlampa,Azcapotzalco,2970,19.46381,-99.15610,...,0,0,0,0.262839,1,6.408529,Plaza de las tres culturas,2.362496,Tlatelolco_1,1.666005
6128,36484872,183851,0,0,0,Centro Histórico,Cuauhtémoc,6000,19.43432,-99.14985,...,0,0,0,0.164274,1,7.442493,Paseo de la Reforma,0.283785,Juárez_1_3,0.247251
6129,36565865,183885,0,0,1,Polanco,Miguel Hidalgo,NaN,19.44006,-99.20628,...,1,1,1,0.131420,0,6.855409,Polanco,1.311269,San Joaquín,1.653224
6130,36668049,183928,1,4,0,Zona Rosa,Cuauhtémoc,6600,19.42539,-99.16362,...,0,0,0,0.098565,1,7.132498,Reforma 222,0.441634,Insurgentes_1_5,0.203105

In [6]:
listingANALISIS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6131 entries, 0 to 6130
Data columns (total 43 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         6131 non-null   int64
 1   index                      6131 non-null   int64
 2   host_is_superhost          6131 non-null   int64
 3   host_total_listings_count  6131 non-null   int64
 4   host_identity_verified     6131 non-null   int64
 5   colonia                    5452 non-null   object
 6   alcaldía                   6131 non-null   object
 7   código_postal              6052 non-null   object
 8   latitude                   6131 non-null   float64
 9   longitude                  6131 non-null   float64
 10  accommodates               6131 non-null   int64
 11  bathrooms                  6131 non-null   float64
 12  bedrooms                   6131 non-null   int64
 13  beds                       6131 non-null   int64
 14  precio                     6131 non-null   int64
 15  security_deposit           6131 non-null   int64
 16  cleaning_fee               6131 non-null   int64
 17  guests_included            6131 non-null   int64
 18  extra_people               6131 non-null   int64
 19  number_of_reviews          6131 non-null   int64
 20  first_review               6131 non-null   object
 21  last_review                6131 non-null   object
 22  review_scores_rating       6131 non-null   int64
 23  insta_book                 6131 non-null   int64
 24  flexible_cancel            6131 non-null   int64
 25  Tipo Listado               6131 non-null   int64
 26  pets_allowed               6131 non-null   int64
 27  gym                        6131 non-null   int64
 28  breakfast                  6131 non-null   int64
 29  washer                     6131 non-null   int64
 30  dryer                      6131 non-null   int64
 31  parking                    6131 non-null   int64
 32  elevator                   6131 non-null   int64
 33  pool                       6131 non-null   int64
 34  smoking_allowed            6131 non-null   int64
 35  hot_tub                    6131 non-null   int64
 36  ad_duration                6131 non-null   float64
 37  Entire home/apt            6131 non-null   int64
 38  ln_price                   6131 non-null   float64
 39  nombre_x                   6131 non-null   object
 40  pi_dist                    6131 non-null   float64
 41  nombre_y                   6131 non-null   object
 42  metro_distance             6131 non-null   float64
dtypes: float64(7), int64(29), object(7)
memory usage: 2.0+ MB

##Housing prices

In [ ]:
housing_prices

,property_type,places,lat-lon,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2
0,apartment,MiguelHidalgo,"23.634501,-102.552788",5500000.0,MXN,5450245.50,289775.66,54.0,54.0,5366.215926,101851.851900
1,house,Iztapalapa,"19.31033,-99.068557",1512000.0,MXN,1498321.97,79661.96,80.0,80.0,995.774500,18900.000000
2,apartment,Tlalpan,"19.279771,-99.234597",926667.0,MXN,918284.00,48822.82,100.0,100.0,488.228200,9266.670000
3,apartment,MiguelHidalgo,"23.634501,-102.552788",6410000.0,MXN,6352013.39,337720.36,135.0,135.0,2501.632296,47481.481480
4,apartment,MiguelHidalgo,"19.432657,-99.177444",4416000.0,MXN,4376051.62,232663.51,87.0,87.0,2674.293218,50758.620690
...,...,...,...,...,...,...,...,...,...,...,...
18229,apartment,Coyoacan,"19.336994,-99.162355",4154400.0,MXN,4116818.02,218880.72,157.0,157.0,1394.144713,26461.146500
18230,house,AlvaroObregon,"19.342911,-99.224472",706448.0,MXN,700223.15,37229.08,105.0,105.0,354.562667,6728.076190
18231,apartment,Cuauhtemoc,"19.408758,-99.129474",621880.0,MXN,616254.29,32764.67,130.0,130.0,252.035923,4783.692308
18232,house,MiguelHidalgo,"19.401079,-99.24807",13000000.0,MXN,12885453.38,685086.71,316.0,350.0,2167.995918,37142.857140
18233,apartment,Cuauhtemoc,"19.441646,-99.151884",6500000.0,MXN,6442726.59,342543.35,120.0,120.0,2854.527917,54166.666670

In [ ]:
housing_prices2

,property_type,places,lat-lon,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,lat,lon
0,apartment,MiguelHidalgo,"23.634501,-102.552788",5500000.0,MXN,5450245.50,289775.66,54.0,54.0,5366.215926,101851.851900,23.634501,-102.552788
1,house,Iztapalapa,"19.31033,-99.068557",1512000.0,MXN,1498321.97,79661.96,80.0,80.0,995.774500,18900.000000,19.310330,-99.068557
2,apartment,Tlalpan,"19.279771,-99.234597",926667.0,MXN,918284.00,48822.82,100.0,100.0,488.228200,9266.670000,19.279771,-99.234597
3,apartment,MiguelHidalgo,"23.634501,-102.552788",6410000.0,MXN,6352013.39,337720.36,135.0,135.0,2501.632296,47481.481480,23.634501,-102.552788
4,apartment,MiguelHidalgo,"19.432657,-99.177444",4416000.0,MXN,4376051.62,232663.51,87.0,87.0,2674.293218,50758.620690,19.432657,-99.177444
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18229,apartment,Coyoacan,"19.336994,-99.162355",4154400.0,MXN,4116818.02,218880.72,157.0,157.0,1394.144713,26461.146500,19.336994,-99.162355
18230,house,AlvaroObregon,"19.342911,-99.224472",706448.0,MXN,700223.15,37229.08,105.0,105.0,354.562667,6728.076190,19.342911,-99.224472
18231,apartment,Cuauhtemoc,"19.408758,-99.129474",621880.0,MXN,616254.29,32764.67,130.0,130.0,252.035923,4783.692308,19.408758,-99.129474
18232,house,MiguelHidalgo,"19.401079,-99.24807",13000000.0,MXN,12885453.38,685086.71,316.0,350.0,2167.995918,37142.857140,19.401079,-99.248070
18233,apartment,Cuauhtemoc,"19.441646,-99.151884",6500000.0,MXN,6442726.59,342543.35,120.0,120.0,2854.527917,54166.666670,19.441646,-99.151884

##Mexico city Airbnb

In [ ]:
listings1

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,14714,Private room c/ bathroom . Colonia Juarez.,57785,Diego,NaN,Cuauhtémoc,19.43035,-99.15511,Private room,478,2,0,NaN,NaN,2,327
1,22787,"Sunny suite w/ queen size bed, inside boutique...",87973,Diego,NaN,Cuauhtémoc,19.44076,-99.16324,Private room,1969,1,57,2019-05-27,0.52,9,355
2,33681,Couple of Rooms,145672,Edubiel,NaN,Tlalpan,19.27215,-99.21848,Private room,1740,1,0,NaN,NaN,1,365
3,35797,Villa Dante,153786,Dici,NaN,Cuajimalpa de Morelos,19.38399,-99.27335,Entire home/apt,3823,1,0,NaN,NaN,2,363
4,44616,CONDESA HAUS B&B,196253,Condesa Haus Bed & Breakfast CDMX,NaN,Cuauhtémoc,19.41006,-99.17645,Private room,1893,1,39,2019-05-02,0.42,10,334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19025,35990295,Departamento a 1km del aeropuerto Internaciona...,3283631,Ana,NaN,Venustiano Carranza,19.43852,-99.08991,Entire home/apt,421,2,0,NaN,NaN,3,3
19026,35996816,Habitación para profesionistas o estudiantes,128869391,María Concepción,NaN,Tlalpan,19.29351,-99.13170,Private room,191,1,0,NaN,NaN,1,365
19027,35997871,Recámara priv. a 10 minutos del centro de Coyo...,203369782,Andrea,NaN,Coyoacán,19.33495,-99.15413,Private room,382,1,0,NaN,NaN,1,365
19028,36001346,Cuarto privado cerca de Polanco,94436130,Samantha,NaN,Miguel Hidalgo,19.45079,-99.18456,Private room,249,1,0,NaN,NaN,1,166
19029,36001745,Hermoso cuarto dentro de una casa mágica,29791582,Zavelia,NaN,Miguel Hidalgo,19.41475,-99.18706,Private room,497,2,0,NaN,NaN,1,363

In [ ]:
calendar_2021

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,454693,2021-02-24,f,"$1,445.00","$1,445.00",10.0,1125.0
1,454693,2021-02-25,f,"$1,445.00","$1,445.00",10.0,1125.0
2,454693,2021-02-26,f,"$1,549.00","$1,549.00",10.0,1125.0
3,454693,2021-02-27,f,"$1,549.00","$1,549.00",10.0,1125.0
4,454693,2021-02-28,f,"$1,445.00","$1,445.00",10.0,1125.0
...,...,...,...,...,...,...,...
7323477,48245511,2022-02-18,t,"$1,100.00","$1,100.00",2.0,60.0
7323478,48245511,2022-02-19,t,"$1,100.00","$1,100.00",2.0,60.0
7323479,48245511,2022-02-20,t,$800.00,$800.00,2.0,60.0
7323480,48245511,2022-02-21,t,$800.00,$800.00,2.0,60.0
7323481,48245511,2022-02-22,t,$800.00,$800.00,2.0,60.0

In [ ]:
listings_2021 # GZ LO PODEMOS AGREGAR A UNION.

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,35797,https://www.airbnb.com/rooms/35797,20210223160913,2021-02-23,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Centro comercial Santa Fe, parque interlomas y...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,https://www.airbnb.com/users/show/153786,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
1,44616,https://www.airbnb.com/rooms/44616,20210223160913,2021-02-24,CONDESA HAUS B&B,A new concept of hosting in mexico through a b...,NaN,https://a0.muscache.com/pictures/251410/ec75fe...,196253,https://www.airbnb.com/users/show/196253,...,10.0,10.0,9.0,NaN,f,10,2,1,0,0.43
2,56074,https://www.airbnb.com/rooms/56074,20210223160913,2021-02-24,Great space in historical San Rafael,This great apartment is located in one of the ...,Very traditional neighborhood with all service...,https://a0.muscache.com/pictures/3005118/60dac...,265650,https://www.airbnb.com/users/show/265650,...,10.0,10.0,10.0,NaN,t,2,2,0,0,0.46
3,58955,https://www.airbnb.com/rooms/58955,20210223160913,2021-02-24,Entire beautiful duplex in la Roma,"This beautiful apartment is centrally located,...",La Roma Norte is a beautiful bohemian and arts...,https://a0.muscache.com/pictures/83292812/1fe9...,282620,https://www.airbnb.com/users/show/282620,...,10.0,10.0,10.0,NaN,f,1,1,0,0,0.38
4,61792,https://www.airbnb.com/rooms/61792,20210223160913,2021-02-24,Spacious Clean Quiet room (own bath) in la Con...,"Located in La Condesa, one of the best neighbo...",You are going to be in one of the nicest neigh...,https://a0.muscache.com/pictures/45f23965-0194...,299558,https://www.airbnb.com/users/show/299558,...,10.0,10.0,10.0,NaN,f,2,0,2,0,1.29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20060,48287522,https://www.airbnb.com/rooms/48287522,20210223160913,2021-02-24,DEPARTAMENTO EN CENTRO HISTORICO CERCA DE CATE...,"Departamento en zona céntrica, a cinco cuadras...",NaN,https://a0.muscache.com/pictures/e350c018-f59e...,389716512,https://www.airbnb.com/users/show/389716512,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
20061,48287621,https://www.airbnb.com/rooms/48287621,20210223160913,2021-02-25,3 CULTURAS-Entire Apartment on the heart of Me...,<b>The space</b><br />Departamento ubicado muy...,NaN,https://a0.muscache.com/pictures/3e990cea-2ed4...,383788083,https://www.airbnb.com/users/show/383788083,...,NaN,NaN,NaN,NaN,t,2,1,0,1,NaN
20062,48287640,https://www.airbnb.com/rooms/48287640,20210223160913,2021-02-25,Residencial Danyval,"Cómodo y céntrico departamento, conectado con ...",A escasos metros del hospital la raza y plaza ...,https://a0.muscache.com/pictures/89ddfa59-a759...,103144327,https://www.airbnb.com/users/show/103144327,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
20063,48287826,https://www.airbnb.com/rooms/48287826,20210223160913,2021-02-24,Hostel in Roma Norte CDMX,NaN,NaN,https://a0.muscache.com/pictures/5ae81144-6423...,383788083,https://www.airbnb.com/users/show/383788083,...,NaN,NaN,NaN,NaN,t,2,1,0,1,NaN
20064,48287915,https://www.airbnb.com/rooms/48287915,20210223160913,2021-02-25,Privada con escritorio a un costado de Santa Fe,Habitación privada con lugar para estacionamie...,NaN,https://a0.muscache.com/pictures/88e8afaf-b1cb...,389720737,https://www.airbnb.com/users/show/389720737,...,NaN,NaN,NaN,NaN,t,1,0,1,0,NaN

In [ ]:
listings_2023

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,35797,Villa Dante,153786,Dici,NaN,Cuajimalpa de Morelos,19.383990,-99.273350,Entire home/apt,4019,1,0,NaN,NaN,1,364
1,44616,CONDESA HAUS B&B,196253,Condesa Haus Bed & Breakfast CDMX,NaN,Cuauhtémoc,19.410060,-99.176450,Entire home/apt,8286,1,49,2020-10-25,0.44,10,364
2,56074,Great space in historical San Rafael,265650,Maris,NaN,Cuauhtémoc,19.437780,-99.155490,Entire home/apt,650,4,60,2019-07-24,1.59,2,0
3,58955,Entire beautiful duplex in la Roma,282620,Laura,NaN,Cuauhtémoc,19.422920,-99.157750,Entire home/apt,1447,15,42,2020-01-31,0.38,1,0
4,61792,Spacious Clean Quiet room (own bath) in la Con...,299558,Roberto,NaN,Cuauhtémoc,19.412590,-99.179590,Private room,1206,2,52,2019-11-03,1.36,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19847,47216226,De Lux Apartment Loft Polanco 402,377262235,Rosa Ma.,NaN,Miguel Hidalgo,19.431680,-99.182640,Entire home/apt,1061,2,0,NaN,NaN,3,365
19848,47216443,Loft pequeño con cocineta a pasos de Reforma,87544364,Antonio,NaN,Cuauhtémoc,19.433830,-99.153780,Entire home/apt,426,1,0,NaN,NaN,9,365
19849,47218209,Loft Deluxe Departamento Polanco 408,377262235,Rosa Ma.,NaN,Miguel Hidalgo,19.431540,-99.183100,Entire home/apt,1059,1,0,NaN,NaN,3,365
19850,47219108,Stuning apartment in Santa Fe 4beds/3baths,377662942,Susan,NaN,Cuajimalpa de Morelos,19.360834,-99.269901,Entire home/apt,1760,2,0,NaN,NaN,1,365
19851,47219520,Habitación a unos pasos de Bosques de Chapultepec,127885823,Sara,NaN,Miguel Hidalgo,19.434000,-99.208420,Private room,186,3,0,NaN,NaN,9,365

##pf_airbnb

In [ ]:
prueba

,c_host_response_rate,c_host_acceptance_rate,c_host_total_listings_count,c_zipcode,c_accommodates,c_bathrooms,c_bedrooms,c_beds,c_guests_included,c_minimum_nights,...,n_v_instant_bookable,n_v_cancellation_policy,c_num_host_verifications,ex_tgt_price,ex_,c_v_host_identity_verified,c_v_host_is_superhost,c_v_instant_bookable,c_v_is_location_exact,c_distancia_aeropuerto
0,100.0,100.0,0.0,11590.0,2.0,1.0,1.0,1.0,1.0,1.0,...,f,strict_14_with_grace_period,2.0,0,0,0,0,0,1,11.4831
1,100.0,100.0,0.0,11590.0,2.0,1.0,1.0,1.0,1.0,1.0,...,f,strict_14_with_grace_period,2.0,0,0,0,0,0,1,11.5455
2,100.0,98.0,15.0,6500.0,4.0,1.0,1.0,2.0,2.0,1.0,...,t,moderate,8.0,0,0,0,1,1,1,10.3684
3,100.0,100.0,0.0,11590.0,2.0,1.0,1.0,1.0,1.0,1.0,...,f,strict_14_with_grace_period,2.0,0,0,0,0,0,1,11.5771
4,100.0,98.0,15.0,6500.0,4.0,1.0,1.0,2.0,2.0,1.0,...,t,moderate,8.0,0,0,0,1,1,1,10.3173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,100.0,90.0,4.0,3100.0,4.0,1.0,1.0,1.0,3.0,1.0,...,f,moderate,7.0,0,0,0,0,0,1,11.7622
96,100.0,0.0,4.0,11550.0,2.0,1.0,1.0,1.0,1.0,1.0,...,t,flexible,6.0,0,0,0,0,1,1,13.7474
97,100.0,0.0,4.0,11550.0,2.0,1.0,1.0,1.0,1.0,1.0,...,f,strict_14_with_grace_period,6.0,0,0,0,0,0,1,13.9484
98,100.0,0.0,4.0,11550.0,1.0,1.0,1.0,1.0,1.0,1.0,...,f,strict_14_with_grace_period,6.0,0,0,0,0,0,1,13.9166
99,100.0,90.0,4.0,3100.0,4.0,1.0,1.0,1.0,3.0,1.0,...,f,moderate,7.0,0,0,0,0,0,1,11.7537

In [ ]:
calendar_2021 = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/Airbnb Mexico City - 2020-2021/calendar.csv")

In [ ]:
calendar_2021

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,454693,2021-02-24,f,"$1,445.00","$1,445.00",10.0,1125.0
1,454693,2021-02-25,f,"$1,445.00","$1,445.00",10.0,1125.0
2,454693,2021-02-26,f,"$1,549.00","$1,549.00",10.0,1125.0
3,454693,2021-02-27,f,"$1,549.00","$1,549.00",10.0,1125.0
4,454693,2021-02-28,f,"$1,445.00","$1,445.00",10.0,1125.0
...,...,...,...,...,...,...,...
7323477,48245511,2022-02-18,t,"$1,100.00","$1,100.00",2.0,60.0
7323478,48245511,2022-02-19,t,"$1,100.00","$1,100.00",2.0,60.0
7323479,48245511,2022-02-20,t,$800.00,$800.00,2.0,60.0
7323480,48245511,2022-02-21,t,$800.00,$800.00,2.0,60.0
7323481,48245511,2022-02-22,t,$800.00,$800.00,2.0,60.0

In [ ]:
num_unique_dates = calendar_2021['date'].nunique()
print(f"The number of unique dates in the 'date' column is: {num_unique_dates}")

The number of unique dates in the 'date' column is: 369

In [ ]:
date_counts = calendar_2021['date'].value_counts().sort_index()
display(date_counts)

date
2021-02-23     2556
2021-02-24    14120
2021-02-25    20042
2021-02-26    20042
2021-02-27    20062
              ...
2022-02-22    20062
2022-02-23    17633
2022-02-24     6660
2022-02-25       20
2022-02-26       20
Name: count, Length: 369, dtype: int64

In [ ]:
date_counts.head(50)

date
2021-02-23     2556
2021-02-24    14120
2021-02-25    20042
2021-02-26    20042
2021-02-27    20062
2021-02-28    20062
2021-03-01    20062
2021-03-02    20062
2021-03-03    20062
2021-03-04    20062
2021-03-05    20062
2021-03-06    20062
2021-03-07    20062
2021-03-08    20062
2021-03-09    20062
2021-03-10    20062
2021-03-11    20062
2021-03-12    20062
2021-03-13    20062
2021-03-14    20062
2021-03-15    20062
2021-03-16    20062
2021-03-17    20062
2021-03-18    20062
2021-03-19    20062
2021-03-20    20062
2021-03-21    20062
2021-03-22    20062
2021-03-23    20062
2021-03-24    20062
2021-03-25    20062
2021-03-26    20062
2021-03-27    20062
2021-03-28    20062
2021-03-29    20062
2021-03-30    20062
2021-03-31    20062
2021-04-01    20062
2021-04-02    20062
2021-04-03    20062
2021-04-04    20062
2021-04-05    20062
2021-04-06    20062
2021-04-07    20062
2021-04-08    20062
2021-04-09    20062
2021-04-10    20062
2021-04-11    20062
2021-04-12    20062
2021-04-13    20062
Name: count, dtype: int64

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/BUAP MAT APL/GENTRIFICACION 2025/DATOS AIRBNB /BASE M/UNION.csv', encoding="utf-8", on_bad_lines="skip")

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

# Diccionario: {fecha_del_scrape: ruta_al_calendar}
cal_paths = {

    "2024-09-25": r"/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /25 SEP 24/calendar.csv.gz",
    "2024-12-27": r"/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /27 DIC 24/calendar.csv.gz",
    "2025-03-19": r"/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/calendar.csv.gz",
    "2025-06-25": r"/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /25 JUN 2025/calendar.csv.gz",
}

cal_list = []

for snap_str, path in cal_paths.items():
    df = pd.read_csv(path, compression="infer")

    # Fecha del scrape (la misma para todo ese archivo)
    df["snapshot"] = pd.to_datetime(snap_str)

    # Limpieza básica consistente
    df["date"] = pd.to_datetime(df["date"])
    df["price_calendar"] = (
        df["price"]
          .astype(str)
          .str.replace("$", "", regex=False)
          .str.replace(",", "", regex=False)
          .str.strip()
    )
    df["price_calendar"] = pd.to_numeric(df["price_calendar"], errors="coerce")

    cal_list.append(df)

# Un solo DataFrame con todos los calendars
cal_all = pd.concat(cal_list, ignore_index=True)

/tmp/ipython-input-462212480.py:15: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression="infer")
/tmp/ipython-input-462212480.py:15: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression="infer")
/tmp/ipython-input-462212480.py:15: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression="infer")

In [3]:
# Ordenamos por listing, fecha de estancia y snapshot (más reciente al final)
cal_all = cal_all.sort_values(["listing_id", "date", "snapshot"])

# Nos quedamos con la observación más reciente para cada listing_id + date
#cal_nodup = cal_all.drop_duplicates(subset=["listing_id", "date"], keep="last")
cal_all.drop_duplicates(subset=["listing_id", "date"], keep="last")

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights,snapshot,price_calendar
731,35797,2024-09-25,f,$200.00,NaN,1.0,7.0,2024-09-25,200.0
732,35797,2024-09-26,f,$200.00,NaN,1.0,7.0,2024-09-25,200.0
733,35797,2024-09-27,t,$200.00,NaN,1.0,7.0,2024-09-25,200.0
734,35797,2024-09-28,t,$200.00,NaN,1.0,7.0,2024-09-25,200.0
735,35797,2024-09-29,t,$200.00,NaN,1.0,7.0,2024-09-25,200.0
...,...,...,...,...,...,...,...,...,...
38348948,1450438287340754798,2026-06-26,f,NaN,NaN,3.0,120.0,2025-06-25,NaN
38348949,1450438287340754798,2026-06-27,f,NaN,NaN,3.0,120.0,2025-06-25,NaN
38348950,1450438287340754798,2026-06-28,f,NaN,NaN,3.0,120.0,2025-06-25,NaN
38348951,1450438287340754798,2026-06-29,f,NaN,NaN,3.0,120.0,2025-06-25,NaN
38348952,1450438287340754798,2026-06-30,f,NaN,NaN,3.0,120.0,2025-06-25,NaN

In [4]:
del df

In [10]:
# Si quieres considerar solo días disponibles:
#cal_use = cal_nodup[cal_nodup["available"] == "t"].copy()

# Precio medio por noche en la ciudad (o en tu recorte espacial) por día de estancia
ts_daily = (
    cal_all.groupby("date")["price_calendar"]
           .mean()
           .sort_index()
)

# Si quieres un DataFrame en vez de Serie:
#ts_daily = ts_daily.to_frame(name="avg_price_city")

In [12]:
ts_daily
ts_daily.to_csv("serie_diaria.csv", encoding="utf-8")

In [13]:
# Asegurar índice de fecha
ts_daily.index = pd.to_datetime(ts_daily.index)

# Semanal (por semana calendario)
ts_weekly = ts_daily.resample("W").mean()

# Mensual
ts_monthly = ts_daily.resample("M").mean()

/tmp/ipython-input-426534582.py:8: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  ts_monthly = ts_daily.resample("M").mean()

In [16]:
ts_weekly
ts_weekly.to_csv("serie_semanal.csv", encoding="utf-8")

In [17]:
ts_monthly
ts_monthly.to_csv("serie_mensual.csv", encoding="utf-8")

In [5]:
list_paths = {

  "2024-09-25": r"/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /25 SEP 24/listings.csv.gz",
    "2024-12-27": r"/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /27 DIC 24/listings.csv.gz",
    "2025-03-19": r"/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /19 MARZ 25/listings.csv.gz",
    "2025-06-25": r"/content/drive/MyDrive/GENTRIFICACION 2025/DATOS AIRBNB /25 JUN 2025/listings.csv.gz",
}

lis_list = []

for snap_str, path in list_paths.items():
    df = pd.read_csv(path, compression="infer")
    df["snapshot"] = pd.to_datetime(snap_str)

    # Renombrar id para que coincida con listing_id
    df = df.rename(columns={"id": "listing_id"})

    # Precio base del listing (opcional)
    df["price_listing"] = (
        df["price"]
          .astype(str)
          .str.replace("$", "", regex=False)
          .str.replace(",", "", regex=False)
          .str.strip()
    )
    df["price_listing"] = pd.to_numeric(df["price_listing"], errors="coerce")

    lis_list.append(df)

lis_all = pd.concat(lis_list, ignore_index=True)

In [6]:
del df

In [7]:
cal_all.to_csv("cal_all.csv", encoding="utf-8")

In [8]:
del cal_all

In [9]:
cols_keep = [
    "snapshot", "listing_id",
    "neighbourhood_cleansed",
    "room_type", "property_type",
    "accommodates",
    "bedrooms", "bathrooms_text",
    "price_listing",
    # puedes añadir más columnas que te interesen
]

lis_all = lis_all[cols_keep]

lis_all.to_csv("lis_all.csv", encoding="utf-8")

In [2]:
import pandas as pd

In [7]:
call_all = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/cal_all.csv", encoding="utf-8")
display(call_all)

/tmp/ipython-input-3605835422.py:1: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  call_all = pd.read_csv("/content/drive/MyDrive/GENTRIFICACION 2025/NOTEBOOKS CARGADOS/cal_all.csv", encoding="utf-8")

,Unnamed: 0,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights,snapshot,price_calendar
0,731,35797,2024-09-25,f,$200.00,NaN,1.0,7.0,2024-09-25,200.0
1,732,35797,2024-09-26,f,$200.00,NaN,1.0,7.0,2024-09-25,200.0
2,733,35797,2024-09-27,t,$200.00,NaN,1.0,7.0,2024-09-25,200.0
3,734,35797,2024-09-28,t,$200.00,NaN,1.0,7.0,2024-09-25,200.0
4,735,35797,2024-09-29,t,$200.00,NaN,1.0,7.0,2024-09-25,200.0
...,...,...,...,...,...,...,...,...,...,...
38446257,38348948,1450438287340754798,2026-06-26,f,NaN,NaN,3.0,120.0,2025-06-25,NaN
38446258,38348949,1450438287340754798,2026-06-27,f,NaN,NaN,3.0,120.0,2025-06-25,NaN
38446259,38348950,1450438287340754798,2026-06-28,f,NaN,NaN,3.0,120.0,2025-06-25,NaN
38446260,38348951,1450438287340754798,2026-06-29,f,NaN,NaN,3.0,120.0,2025-06-25,NaN
38446261,38348952,1450438287340754798,2026-06-30,f,NaN,NaN,3.0,120.0,2025-06-25,NaN

In [4]:
lis_all = pd.read_csv("lis_all.csv", encoding="utf-8")
display(lis_all)

,Unnamed: 0,snapshot,listing_id,neighbourhood_cleansed,room_type,property_type,accommodates,bedrooms,bathrooms_text,price_listing
0,0,2024-09-25,35797,Cuajimalpa de Morelos,Entire home/apt,Entire villa,2,1.0,1 bath,3865.0
1,1,2024-09-25,44616,Cuauhtémoc,Entire home/apt,Entire home,14,5.0,5.5 baths,NaN
2,2,2024-09-25,67703,Cuauhtémoc,Entire home/apt,Entire rental unit,4,2.0,1 bath,2029.0
3,3,2024-09-25,70644,Coyoacán,Entire home/apt,Entire rental unit,2,1.0,1 bath,1140.0
4,4,2024-09-25,107078,Miguel Hidalgo,Entire home/apt,Entire loft,2,1.0,1.5 baths,3633.0
...,...,...,...,...,...,...,...,...,...,...
105326,105326,2025-06-25,1450299137475327273,Azcapotzalco,Entire home/apt,Entire condo,6,2.0,1 bath,1080.0
105327,105327,2025-06-25,1450300528106131951,Benito Juárez,Entire home/apt,Entire rental unit,2,1.0,1 bath,982.0
105328,105328,2025-06-25,1450345027980478127,Cuauhtémoc,Entire home/apt,Entire rental unit,4,2.0,1 bath,1612.0
105329,105329,2025-06-25,1450394952972090126,Cuauhtémoc,Entire home/apt,Entire loft,2,1.0,1 bath,627.0
105330,105330,2025-06-25,1450438287340754798,Miguel Hidalgo,Entire home/apt,Entire rental unit,6,3.0,2 baths,3070.0

In [ ]:
#cal_enriched =
call_all = call_all.merge(
    lis_all,
    on=["snapshot", "listing_id"],
    how="left"
)

#LINKS DE ARTICULOS

[Gentrificación periurbana y cambios socioterritoriales en la periferia de Puebla, México](https://www.scielo.cl/scielo.php?script=sci_arttext&pid=S0250-71612023000100006&lang=en)

[Gentrificación transnacional y nómadas digitales en la zona central de la Ciudad de México](https://www.scielo.cl/scielo.php?script=sci_arttext&pid=S0250-71612025000100010&lang=en)

[El privilegio a la ciudad: (dis)locaciones socioespaciales de Airbnb en la Ciudad de México](http://scielo.senescyt.gob.ec/scielo.php?script=sci_arttext&pid=S1390-86342025000100061&lang=en)